### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by Huvik** [weprovide/valet-plus#10]
Hey, 
i wanted to try out valet-plus, but there is missing stuff in readme. 

Problem with database:
* What is user and pass for database?
* How to import database without git repository? I can always do `mysql -u root -proot DBNAME < database.sql`

So far looking good keep it up! 🚀

**Comment by timneutkens** [comment]
Added username and password and `valet db import dump.sql DNAME`. Fixed in release `0.1.2`
