### ISSUE TITLE
Mysql: Failed to connect to database

### ISSUE THREAD

**Issue by Jensderond** [weprovide/valet-plus#101]
Hi, I just installed Valet and I'm having trouble importing my databases.

![6a7tg 02-01 iec5z](https://user-images.githubusercontent.com/6972822/34481218-24f93e5a-efb1-11e7-8a15-666d21552ef1.png)

I've removed mysql fully before installing valet+

**Comment by SanderAtom** [comment]
Hi, what happens when you type `mysql -u root -p root` in your terminal?
Can you check if `~/.my.cnf` exists with different login details than `localhost` and `root` for username and password?

**Comment by Jensderond** [comment]
`mysql -uroot -proot` worked. But `~/.my.cnf` did not exist.
Created it and now it works!

_Content of .my.cnf:_
```[client]
user=root
password=root
host=localhost

**Comment by rafaelstz** [comment]
I solved it running these commands:

```bash
valet uninstall
valet install 
valet fix
/usr/local/Cellar/mysql@5.7/5.7.29/bin/mysql.server start
```
