### ISSUE TITLE
Setting up Prestashop on valet+

### ISSUE THREAD

**Issue by kjugi** [weprovide/valet-plus#102]
Hi, 
Actually, I have added custom config in `nginx/valet` dir where We have also general config to valet or mailhog i.e. My config looks like [this](https://pastebin.com/zfeQZUsv). Nothing special in fact but I think it's not working so good (503 in install steps, redirecting website from admin panel to homepage when want to add a new product or blank homepage in 1.6.x version). Installed also on other machines with the same config but without valet+ and seems to work well.

I'm almost sure that is the wrong way to add a config to PrestaShop like this. Actually, I've started with creating new Valet custom driver for this but don't know what to do with rewrites in the config and what is necessary to include.

Some prototype of my `PrestashopValetDriver.php` (not working fine):
```
class PrestashopValetDriver extends BasicValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        return file_exists($sitePath . '/bin/doctrine');
    }

    public function isConfigExist() {
        return file_exists($sitePath.'/app/config/config.php');
    }

    public function isParametestExist() {
        return file_exists($sitePath.'/app/config/parameters.php');
    }

    public function installed($sitePath) {
        return $this->isConfigExist($sitePath) && $this->isParametestExist($sitePath);
    }
}
```

Is there any chance to add driver for it or just left it by custom config in nginx?

**Comment by samgranger** [comment]
Please take a look at: https://github.com/dalink/laravel-valet-drivers/blob/f4d363a02277624e27d3b10564dc16f5b53d6c12/PrestashopValetDriver.php

Hopefully this driver works for you.

**Comment by kjugi** [comment]
Checked this solution, must change a little bit with adding `index.php` on the end when it's necessary or not. Otherwise, it's looking good. Now I have a problem with listing all products on Catalog/Products but I think it not related to valet anymore. Will search for the solution or ask some Presta dudes for help. Thanks for this driver!

**Comment by samgranger** [comment]
Please let me know what the outcome is, and if you do end up tweaking the driver or not. Might be handy to add this to valet-plus so please feel free to shoot in a pull request!

Closing this ticket for now.
