### ISSUE TITLE
Magento 2 error pages not routing correctly

### ISSUE THREAD

**Issue by johnhughes1984** [weprovide/valet-plus#109]
## Overview
Magento 2's error pages do not route correctly and instead route to a standard Magento 404 page.

## Steps to reproduce
1. Try to visit an error page e.g. 'https://myproject.test/errors/503.php' (or 404/report.php etc.)

## Expected result
- Magento page from error theme should be returned

## Actual result
- Magento standard 404 page returned (not error theme 404 page)

**Comment by samgranger** [comment]
Thank you for your pull request, we will be testing this change and will try and get it included in a new release tomorrow.

**Comment by samgranger** [comment]
Merged - sorry that we didn't get this released as soon as we wanted to - this will be included in the next release.

**Comment by samgranger** [comment]
Thank you for your PR - and once again, sorry for taking so long to add this to a release @johnhughes1984 - this has been added to today's release!
