### ISSUE TITLE
Feature request: Pimcore driver

### ISSUE THREAD

**Issue by awojtczyk** [weprovide/valet-plus#112]
I'm looking for the Pimcore driver. Any help will be appreciated :) 
https://pimcore.com/en
https://pimcore.com/docs

**Comment by jellesiderius** [comment]
Would be nice :)

**Comment by stefan-h-singer** [comment]
For 5.x? I have something okish...

Den ons 18 apr. 2018 15:32Jelle Siderius <notifications@github.com> skrev:

**Comment by jellesiderius** [comment]
@stefan-h-singer,
Would be nice to see that, if it gets pimcore 5.x up and running.

**Comment by stefan-h-singer** [comment]
It's a bit of a hack, but works for us. 
LocalValetDriver.php (put this in /web since that's the directory you should link)
`<?php

/** Valet driver for Pimcore 5 */
class LocalValetDriver extends ValetDriver
{
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        if (file_exists($sitePath.'/pimcore')) {
             return true;
        }

        return false;
    }

    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        // remove cache busting part from url
        if(strpos($uri, '/cache-buster') === 0) {
            // https://stackoverflow.com/questions/25543974/how-to-get-string-after-second-slash-in-url-using-php
            $last = explode("/", $uri, 3);
            $uri = '/'.$last[2];
        }
        if (file_exists($staticFilePath = $sitePath.'/var/assets'.$uri) || file_exists($staticFilePath = $sitePath.$uri)) {
            return $staticFilePath;
        }

        return false;
    }

    /**
     * Get the fully resolved path to the application's front controller.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string
     */
    public function frontControllerPath($sitePath, $siteName, $uri)
    {
        if(strpos($uri, '/install') === 0) {
            return $sitePath.'/install.php'; 
        }

        return $sitePath.'/app.php';
    }
}
`

**Comment by jellesiderius** [comment]
Great, my 5.x is working now!

**Comment by Neodork** [comment]
@stefan-h-singer Could you provide a PR?

**Comment by stefan-h-singer** [comment]
If the above code is fine, sure!

Den tors 19 apr. 2018 18:57Lou van der Laarse <notifications@github.com>
skrev:

**Comment by Neodork** [comment]
@stefan-h-singer Yes, looks fine to me. Can't test it but going off the reactions in this thread I would say, yes fine to me.
