### ISSUE TITLE
Drupal driver missing $_SERVER['DOCUMENT_ROOT']

### ISSUE THREAD

**Issue by agileadam** [weprovide/valet-plus#113]
Hello,

I've been having a few issues with some Drupal sites due to not having the $_SERVER['DOCUMENT_ROOT'] environment variable.

Can you please add this to the Drupal driver?

Adding this line to the fallback section of the frontControllerPath() seems to work fine:

`$_SERVER['DOCUMENT_ROOT'] = $sitePath;`

**Comment by samgranger** [comment]
Thank you for reporting this issue. We will look at adding this change asap.

**Comment by Neodork** [comment]
I got a PR for this which I shall contribute soon.

**Comment by samgranger** [comment]
Thanks for your report! We have received and merged the PR that @Neodork provided us.
