### ISSUE TITLE
PHP 7.2 error: Unable to determine linked PHP

### ISSUE THREAD

**Issue by markitosgv** [weprovide/valet-plus#114]
Hi!

I'm trying to use Valet with PHP 7.2 but brew says me "Unable to determine linked PHP".

<img width="468" alt="imagen" src="https://user-images.githubusercontent.com/1706470/36886356-460028c0-1dec-11e8-91b5-df558e2c8c14.png">

With PHP 7.0 or 7.1 everything works perfect!

<img width="471" alt="imagen" src="https://user-images.githubusercontent.com/1706470/36886400-7e6d1bd2-1dec-11e8-81d3-13768802e6ad.png">

Thanks!

**Comment by TomMeijnaerts** [comment]
This is because brew installs php7.2 under the normal /usr/local/Cellar/php/7.2.xx instead of /usr/local/Cellar/php7.2/7.2.xxx

**Comment by TomMeijnaerts** [comment]
https://github.com/Homebrew/homebrew-php/commit/8771c68f3ddfee62d9e97177449010c2968f91d1#diff-4739b7cd74be3128a6b717288e740259

Homebrew migrated the php7.2 to the core php ... now valet is broken for 7.2

**Comment by cmaerz** [comment]
Somehow fixed this with some hardcoded (and broke the version switching). Looking forward for a "real" fix.

**Comment by TorbenL** [comment]
I'm facing the same issue. Anything new here? Or is there a workaround beside switching back to 7.1? Appreciate your support!

**Comment by remklov** [comment]
I have the same problem when switching from php70 to php7.1.

**Comment by vanpoppel** [comment]
Check if `which php` contains the correct php version. If it does, use `ln -s $(which php) /usr/local/bin/php` to link. (it's still a workaround, but it works)

**Comment by Neodork** [comment]
Related to https://github.com/weprovide/valet-plus/issues/127

**Comment by samgranger** [comment]
Please try our new release. After upgrading, please run ‘valet fix’ followed by ‘valet install’. Please open a new ticket or join our chat on gitter if you encounter any issues.
