### ISSUE TITLE
Mailhog doesn't work with custom TLD

### ISSUE THREAD

**Issue by markitosgv** [weprovide/valet-plus#115]
Hi,

I'm using my custom top level domain (TLD) for my local sites, everything works fine except Mailhog throws this message "Did not get front controller from driver. Please return a front controller to be executed."

If I put ".test" TLD domain it works.

**Comment by samgranger** [comment]
You are correct, this is currently hard coded. We will see if we can make this dynamic.

**Comment by Neodork** [comment]
I got a PR for this which I shall contribute soon.

**Comment by samgranger** [comment]
Thanks for reporting, closing this issue as @Neodork provided us with a PR that should solve this issue.
