### ISSUE TITLE
Use ghost blog local url

### ISSUE THREAD

**Issue by habnai** [weprovide/valet-plus#116]
ho I can sevrer ghost instal local when I try url I get :
 Did not get front controller from driver. Please return a front controller to be executed.
how I can make driver for ghost blog to server it via valet+

**Comment by samgranger** [comment]
Hi there.

 I assume you are referring to https://ghost.org/ - correct me if I'm wrong, but isn't this a NodeJS project? No reason to use Valet+. If you are referring to a different project, please let us know.

**Comment by habnai** [comment]
Yes I mean ghost nodejs project.thank you for reply,I use valet+ for other project and work great just I was I ask about ghost if possible.
