### ISSUE TITLE
$_SERVER['SERVER_NAME'] missing for xdebug to function properly

### ISSUE THREAD

**Issue by rasmuswikman** [weprovide/valet-plus#119]
According to the docs xdebug should work straight out of the box, but I'm having troubles getting it to work in PhpStorm.

Setting a server name in valet.conf works.

In the WordPress driver this is set in frontControllerPath.
https://github.com/weprovide/valet-plus/blob/master/cli/drivers/WordPressValetDriver.php#L30

I'm currently working on a Magento 2 project, and I guess it could be fixed by doing the same for the Magento 2 driver.

**Comment by rasmuswikman** [comment]
Solved by setting:
        fastcgi_param SERVER_NAME test;
in valet.conf.

Anybody come across this?

**Comment by samgranger** [comment]
Thanks for your report - seems like this will be simple to resolve!

**Comment by samgranger** [comment]
Closing this ticket as we have added this change to Valet+'s new 1.0.19 release!
