### ISSUE TITLE
Valet stoped working after a brew Upgrade :-(

### ISSUE THREAD

**Issue by allrude** [weprovide/valet-plus#122]
Hi after a "recommended" brew upgrade VALET-plus stoped working.

I tried a reinstall and ended in completely uninstalling Valet and Homebrew

Reinstall fails the problem seem to be a icu4c 61.1 compatibility

see:  https://github.com/Homebrew/homebrew-php/issues/4828

and
[https://bugs.php.net/bug.php?id=76153](https://bugs.php.net/bug.php?id=76153)  [http://source.icu-project.org/repos/icu/trunk/icu4c/readme.html#RecBuild](http://source.icu-project.org/repos/icu/trunk/icu4c/readme.html#RecBuild)

Any insights in how to get Valet-plus up and running again

Thanks Ruud

**Comment by remklov** [comment]
I had the same issue. Check this issue: https://github.com/Homebrew/homebrew-php/issues/4831
You have to add the icu4c 61.1 compatibility manually to your phpXX-intl file. Check the comment of Kyslik. This fixed the problem for me.

**Comment by Neodork** [comment]
Related to https://github.com/weprovide/valet-plus/issues/127

**Comment by samgranger** [comment]
We have created a new release that addresses this issue, solution provided by @Neodork

Please upgrade and run valet fix followed by valet install.

**Comment by allrude** [comment]
Nice to have all the post regarding the Homebrew and PHP problems closed, but since the problem has not been solved .....

**Comment by alexvandervegt** [comment]
You can downgrade icu4c following this:

http://hanxue-it.blogspot.com/2018/08/macos-homebrew-installing-older-version-of-software.html
