### ISSUE TITLE
PHP7.1 not working after Homebrew change

### ISSUE THREAD

**Issue by vanpoppel** [weprovide/valet-plus#123]
Homebrew has change the way PHP is installed. When you run `brew update` or `brew upgrade`, Valet will return an error: ` Unable to determine linked PHP`

The same issue is happening on default Valet, where there is also an issue with someone describing a temp fix:
https://github.com/laravel/valet/issues/544

I got Valet running properly again with the following changes. (same changes should work on Valet Plus)

In `$HOME/.composer/vendor/laravel/valet/cli/Valet/Brew.php`:
```
    function supportedPhpVersions()
    {
        return collect(['php', 'php72', 'php71', 'php70', 'php56', 'php@7.1']);
    }
```
In `$HOME/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php`:
```
    function fpmConfigPath()
    {
        $confLookup = [
            'php' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
            'php72' => '/usr/local/etc/php/7.2/php-fpm.d/www.conf',
            'php71' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf',
            'php70' => '/usr/local/etc/php/7.0/php-fpm.d/www.conf',
            'php56' => '/usr/local/etc/php/5.6/php-fpm.conf',
            'php@7.1' => '/usr/local/etc/php/7.1/php-fpm.d/www.conf'
        ];

        return $confLookup[$this->brew->linkedPhp()];
    }
```

Also in `$HOME/.composer/vendor/laravel/valet/cli/Valet/PhpFpm.php`,  in the `installExtensions()` function:
```
    if ('php@7.1' == $currentVersion) {
        info('['.$currentVersion.'] install modules (apcu, intl, mcrypt, opcache, geoip) separately using brew');
        continue;
    }
```

Also, make sure the symlink for php is set properly. Check if the path to your php is correct (`which php`) and set the symlink like this: `ln -s $(which php) /usr/local/bin/php`

I have not created a PR yet, for two reasons:
Because i stell have to symlink `/usr/local/bin/php` manually.
And because i am not sure why/how the modules can be installed automatically, but I know other people are having these issues so I hope this helps someone.

**Comment by Neodork** [comment]
Related to https://github.com/weprovide/valet-plus/issues/127

**Comment by samgranger** [comment]
We have created a new release that addresses this issue, solution provided by @Neodork

Please upgrade and run valet fix followed by valet install.

**Comment by Fgruntjes** [comment]
Thanks guys for the hard work on this!
