### ISSUE TITLE
Could not find installation path for: apc

### ISSUE THREAD

**Issue by guarinogabriel** [weprovide/valet-plus#131]
Hi everyone,

I appreciate the hard work from all the contributors that have been focused on resolving the homebrew/core issue.

I tried to install Valet+ from scratch on my Mac when the fix was merged into develop, but I found the following issues:

1. I followed the installation instructions but the **valet fix** command didn't work:
![1](https://user-images.githubusercontent.com/1928452/38571346-a71bfe56-3cc6-11e8-92bf-146a86c4655c.png)

2. I had to run **valet install** to proceed with the installation, but the following error happened during the installation:
![2](https://user-images.githubusercontent.com/1928452/38571390-c23d27f0-3cc6-11e8-822f-48b77214e2f5.png)

3. At that point I was able to run **valet fix**, but the following errors happened:
![3](https://user-images.githubusercontent.com/1928452/38571435-e22150fa-3cc6-11e8-803e-4be9936e9faa.png)

4. Then, I tried to run the install again by running **valet install**, but the following error happened:
![4](https://user-images.githubusercontent.com/1928452/38571489-051f9404-3cc7-11e8-9259-2398af1a361a.png)

Anyone else experiencing these issues?

**Comment by allrude** [comment]
I also tried a clean install, but my installation already crashes on de n98-magerun and the valet fix command ... is not defined, I removed everything, started again from scratch an got the same result'

Perhaps it works for upgrade but for me that ship was already sailed after trying again and again to get valet plus up and running.

So hoping that the guy who do all the (magic) good work will fix this too

**Comment by Neodork** [comment]
@guarinogabriel Looks like apcu_bc is failing to install could you run the following commands:

`php -v`
`pecl list`
`cat /usr/local/etc/php/{YOUR_VERSION}/php.ini`
if PHP 7.0 or greater: `pecl install apcu_bc` 
If PHP 5.6: `pecl install apc`

**Comment by guarinogabriel** [comment]
@Neodork - Thanks for your response. I confirm that I've run `pecl install apcu_bc`.

Unfortunately, the following issue is happening for both the `valet fix` and `valet install` commands:

![5](https://user-images.githubusercontent.com/1928452/38577907-a96899dc-3cd8-11e8-87fd-2e5f5fa3c5f7.png)

**Comment by Neodork** [comment]
Could you show me the output of `ls -la /usr/local/etc/php/{PHP_VERSION}/conf.d/`

**Comment by guarinogabriel** [comment]
@Neodork - Sure, here is the output:

![6](https://user-images.githubusercontent.com/1928452/38578292-e5346e7c-3cd9-11e8-950c-9435e0bd4cee.png)

**Comment by Neodork** [comment]
Euhm, just to let you know I am looking for the following directive `extension="apcu.so"`. My next guess would be your php.ini. Please show me `cat /usr/local/etc/php/{YOUR_VERSION}/php.ini`

**Comment by Neodork** [comment]
@guarinogabriel Please remove the top 3 instructions and save the file. Remove all extension= from the top 3 lines. Then show me `php -v`.

**Comment by guarinogabriel** [comment]
@Neodork - I removed those lines. Here is the output of that command:

![7](https://user-images.githubusercontent.com/1928452/38578999-06874d0e-3cdc-11e8-85d6-9362b504b41e.png)

**Comment by Neodork** [comment]
Good now run `valet fix` and `valet install`.

**Comment by guarinogabriel** [comment]
@Neodork - Here is the output of the `valet fix` command:

![8](https://user-images.githubusercontent.com/1928452/38579282-e6fa44e0-3cdc-11e8-93b1-18d0682a693a.png)

And here is the output of the `valet install` command:
![9](https://user-images.githubusercontent.com/1928452/38579306-f2249c08-3cdc-11e8-8ad8-049d8785a46c.png)

What do you recommend next?

**Comment by Neodork** [comment]
Show me `pecl install geoip` and `pecl list`.

**Comment by guarinogabriel** [comment]
Here is the output for both commands:

![10](https://user-images.githubusercontent.com/1928452/38579466-8250e3ea-3cdd-11e8-95ca-8e533e33ef01.png)

**Comment by Neodork** [comment]
Please do `brew install geoip` and `valet install` again.

**Comment by guarinogabriel** [comment]
Thanks so much @Neodork - Valet has been successfully installed.

![11](https://user-images.githubusercontent.com/1928452/38580432-551959e0-3ce0-11e8-81a3-7756c286fe43.png)

I will close the issue now, thanks again.
