### ISSUE TITLE
valet install fails on pecl apc install

### ISSUE THREAD

**Issue by capitaladot** [weprovide/valet-plus#142]
```valet install
Password:
[php] Checking for errors within the php installation...
[nginx] Stopping
[php@7.1] Stopping
[php@7.2] Stopping
[mysql] Stopping
[redis] Stopping
[devtools] Installing
[devtools] wp-cli already installed
[devtools] pv already installed
[binaries] Installing binaries
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions

In Pecl.php line 499:

  Could not find installation path for: apc
  Command: pecl install apc, failed! Error:


   p


install [--with-mariadb]
```

**Comment by josephfusco** [comment]
I get something slightly different when running `valet install`

```
Password:
[php] Checking for errors within the php installation...
[nginx] Stopping
[php@7.1] Stopping
[php@7.2] Stopping
[mysql] Stopping
[redis] Stopping
[devtools] Installing
[devtools] wp-cli already installed
[devtools] pv already installed
[binaries] Installing binaries
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions

In Pecl.php line 499:

  Could not find installation path for: geoip
  Command: pecl install geoip, failed! Error:


   a


install [--with-mariadb]
```

**Comment by capitaladot** [comment]
Mine seemed to get into a weird state trying to use php5.6. I ultimately gave up and am using 7.1.

**Comment by samgranger** [comment]
@capitaladot could you try restarting your machine? I have noticed that this helps a lot when your CLI is running a different version of PHP compared to the version Valet uses to serve your sites on.

I have merged a few PR's from @Neodork that should solve quite a few issues and have created a fresh new release - could you try upgrading to the newest version and run `valet fix`?

**Comment by samgranger** [comment]
@capitaladot see: https://github.com/weprovide/valet-plus/pull/140

We have merged this into our latest release so this should give us a better idea on what's happening - hope that we can get your issue resolved swiftly!

**Comment by samgranger** [comment]
Closing this issue, please open a new ticket if you're still encountering issues.
