### ISSUE TITLE
Fatal error: Call to undefined function apcu_fetch()

### ISSUE THREAD

**Issue by djdesign** [weprovide/valet-plus#143]
Having same issue as #133 , followed the suggestions but no luck. Any Suggestions?

Fatal error: Call to undefined function apcu_fetch() in /User/r2d2/.composer/vendor/weprovide/valet-plus/server.php on line 37

### env details

<details>
	<summary>php -v</summary>
PHP 7.1.16 (cli) (built: Apr 12 2018 03:28:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16, Copyright (c) 1999-2018, by Zend Technologies
</details>

<details>
<summary>**z-performance.ini**</summary

; Add America/New_York string for replacing with machine timezone
date.timezone = "America/New_York"

; Max execution time per request
max_execution_time = 300

; Max memory per instance
memory_limit = 128M

;The maximum size of an uploaded file.
upload_max_filesize = 128M

;Sets max size of post data allowed. This setting also affects file upload. To upload large files, this value must be larger than upload_max_filesize
post_max_size = 128M

session.auto_start = off
session.gc_probability = 0
suhosin.session.cryptua = off
memory_limit=2G

; Disable garbage collector
zend.enable_gc = off

; Use mailhog for sending emails
sendmail_path = /usr/local/bin/MailHog sendmail test@test  

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 2048
opcache.interned_strings_buffer = 20
opcache.file_cache=1
opcache.max_accelerated_files = 80000
opcache.max_wasted_percentage = 5
opcache.use_cwd = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
opcache.file_update_protection = 2
opcache.revalidate_path = 0
opcache.save_comments = 1
opcache.load_comments = 1
opcache.fast_shutdown = 1
opcache.enable_file_override = 0
opcache.optimization_level = 0xffffffff
opcache.inherited_hack = 1
opcache.blacklist_filename = ""
opcache.max_file_size = 0
opcache.consistency_checks = 0
opcache.force_restart_timeout = 180
opcache.error_log = ""
opcache.log_verbosity_level = 1
opcache.preferred_memory_model = ""
opcache.protect_memory = 0
apc.cache_by_default = false

[apcu]
; apcu and php-fpm cause valet to hang, so we turn off apcu for now.
; See https://github.com/weprovide/valet-plus/issues/49
apc.enabled=0
apc.shm_size=512M
apc.ttl=7200
apc.mmap_file_mask=/tmp/apc.XXXXXX
apc.enable_cli=1

[xdebug]
xdebug.remote_enable=1
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_autostart=1
xdebug.idekey=PHPSTORM

</details>

.<details>
	<summary>pcel list</summary>
```shell
Installed packages, channel pecl.php.net:
=========================================
Package Version State
apcu    5.1.11  stable
apcu_bc 1.0.4   stable
geoip   1.1.1   beta
```
</details>

**Comment by samgranger** [comment]
Hi @djdesign - sounds like your valet's frontend is still running on a different PHP version than your cli - could you try rebooting your machine as this seems to solve quite a few issues after updating. Let me know if this helps or if you require extra assistance.

**Comment by djdesign** [comment]
@samgranger I have restarted, but doesn’t help.

**Comment by FredericMartinez** [comment]
Same problem here, same config.

**Comment by Neodork** [comment]
Currently working on some improvements for this. @djdesign Are the apcu.so lines added to your php.ini file?

**Comment by djdesign** [comment]
@Neodork Yes I see It listed at the top.

extension="apc.so"
extension="apcu.so"
extension="geoip.so"

**Comment by Neodork** [comment]
@djdesign Those are invalid. Remove those and switch back. `valet use 7.1` and `valet use 5.6`

**Comment by MaxSouza** [comment]
@djdesign Did you try run valet install after valet use?

![image](https://user-images.githubusercontent.com/5350377/38738676-1fd785a6-3f09-11e8-9d1c-f022cdb80947.png)

After run valet use, i need run valet install for working on new version php.

![image](https://user-images.githubusercontent.com/5350377/38738828-868c680c-3f09-11e8-9475-76932eca994a.png)

**Comment by MaxSouza** [comment]
I don't know if that's the correct procedure

**Comment by djdesign** [comment]
This is the results I get.
<img width="1502" alt="screen_shot_2018-04-13_at_10_08_00_am" src="https://user-images.githubusercontent.com/6698286/38739373-bf716ea8-3f02-11e8-8108-fcd7f5af0d1c.png">

**Comment by Neodork** [comment]
@djdesign Could you show me `brew list | grep php`

**Comment by djdesign** [comment]
@Neodork ```shell 
~/s/v/testing  brew list | grep php
php-cs-fixer
php@7.1
phpunit
```

**Comment by Neodork** [comment]
Oke so no old installations present, that's good. How about `ls -la /usr/local/etc/php/7.0/cond.d/` are there any ext-apcu.ini files present?

**Comment by djdesign** [comment]
```bash
~/s/v/testing$  ls -la /usr/local/etc/php/7.0/cond.d/
ls: /usr/local/etc/php/7.0/cond.d/: No such file or directory
```

**Comment by FredericMartinez** [comment]
I solved this problem by uninstalling PHP and Valet Plus.
When you enter `php -v`, you shoud have `command not found`.

Then, reinstall PHP with brew and valet plus.

**Comment by Neodork** [comment]
I've had contact with @djdesign through google hangouts. The problem was mostly related to having PHP-FPM serving an other version of PHP as the CLI. As mentioned in this thread a few times before. He did have some issues with the DB but I don't think those were related to this issue.

**Comment by samgranger** [comment]
Thanks for helping @djdesign out @Neodork - closing this issue for now.

**Comment by FredericMartinez** [comment]
Thanks @lazyguru, `brew services restart php@7.1` works!
