### ISSUE TITLE
different php versions

### ISSUE THREAD

**Issue by stefandb** [weprovide/valet-plus#145]
Hi everyone,

I have a problem with switching the php version.
valet use works only on the php version of the CLI. the web version is always 7.0.27 not 7.1 after "valet use 7.1".

I reinstalled the php versions and update valet to the latest version. 
what do I have to do to get the right version?

**Comment by Neodork** [comment]
@stefandb Restarting your PC so old processes can die off tends to work. It is very likely you have an old php-fpm instance running your webserver.

**Comment by allrude** [comment]
@stefandb Yes restarting solved my problem, but I had to do it two times

**Comment by stefandb** [comment]
Thanks this fix the problem.
