### ISSUE TITLE
1.0.13 : Switch PHP versions throws PECL error

### ISSUE THREAD

**Issue by kanduvisla** [weprovide/valet-plus#148]
When I switch from PHP versions, I get the following error:

```
  Could not find installation path for: apc

  Package "apcu_bc" Version "1.0.4" does not have REST dependency information available
  install failed
```

Full trace:

```
» valet use 7.0                                                                 giel@Mac0025
[PECL] Removing extensions
Unlinking /usr/local/Cellar/php@7.1/7.1.16_1... 25 symlinks removed
ln: /usr/local/opt/jpeg/lib/libjpeg.8.dylib: File exists
Linking /usr/local/Cellar/php@7.0/7.0.29_1... 25 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/php@7.0/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/php@7.0/sbin:$PATH"' >> ~/.zshrc
[php@7.0] Stopping
[php@7.1] Stopping
[php@7.2] Stopping
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions

In Pecl.php line 498:

  Could not find installation path for: apc

  Package "apcu_bc" Version "1.0.4" does not have REST dependency information available
  install failed


use [<phpVersion>]
```

The only thing I did recently was that I had to manually install the Imagick-PECL extension. I did this using the default PECL-way.

Now my valet+ setup is broken again :-(
I had to do a `valet restart`, but logically, PHP is now throwing errors when I use methods like `apcu_fetch()` and such.

**minor update:**

I'm not sure if this is a Valet+ or a PECL issue because when I run `pecl install apcu_bc` I get the same error. But then again: I lack of knowledge how PECL is handled / installed by Valet+.

**Comment by kanduvisla** [comment]
I think I found the core of my issue. Because the default `pecl install apcu_bc`-command threw the same error I started looking in that direction. The pecl server wasn't down, so I thought that maybe it was an caching issue. I finally ended up deleting `/tmp/phar` and like a miracle everything started working perfectly again.

So I'll leave it up to the Valet+ community to determine if this is a bug (should Valet+ flush the `/tmp/phar`-directory when switching / installing?).

**Comment by Neodork** [comment]
@kanduvisla Thanks for your report. I am unsure on the `"Package "X" Version "Y" does not have REST dependency information available"` error. Lets leave this bug report open for a few days to see if anyone else encounters the same problem.

**Comment by kanduvisla** [comment]
@Neodork, otherwise the deleting of the `/tmp/phar`-folder might be an addition to the `valet fix`-command, because it was the fix in my scenario.

**Comment by kanduvisla** [comment]
@samgranger : I understand that you're closing this issue after 3 weeks, but this issue still persist in my setup today. I get it at least a couple times every week.

Am I really the only one who experiences this? What did you think about my suggestion to include it in the `valet fix` command?

**Comment by Neodork** [comment]
@kanduvisla I've noticed instability within PECL manager namely relating to the pear configuration. Could you share your `cat /usr/local/etc/php/7.0/pear.conf` file so I can compare?

**Comment by ivastly** [comment]
simple re-run just fixed it for me, looks like the root cause is a short downtime of PECL itself.
