### ISSUE TITLE
XDEBUG - Can't debug an external call

### ISSUE THREAD

**Issue by igor-imaginemage** [weprovide/valet-plus#150]
Hi guys, thanks for this amazing tool!

I am not getting to use XDEBUG to debug a custom extension, when I try to add a break point from a call from frontend the debug is not running. I noticed that I can debug the core modules but I am trying in a custom module and it's not working.

Am I missing some step?

If I add to break point the first line of my class it runs a lot of times this file:

<img width="982" alt="screen shot 2018-04-19 at 11 07 16 am" src="https://user-images.githubusercontent.com/25936073/39000505-3680c962-43c2-11e8-902a-52e40517201d.png">

If I run a cli command on terminal it works fine, I am not getting to debug only extern calls from my browser.

Thanks!

**Comment by Neodork** [comment]
@igor-imaginemage Are you sure you have the xdebug cookie set? For example with [xdebug helper](https://chrome.google.com/webstore/detail/xdebug-helper/eadndfjplgieldjbigjakmdgkmoaaaoc).

**Comment by igor-imaginemage** [comment]
Thanks for your feedback @Neodork, I tested on Firefox and looks good. Probably it was something wrong with my Chrome. Thank you.
