### ISSUE TITLE
php.ini errors?

### ISSUE THREAD

**Issue by NicolaLeonardi** [weprovide/valet-plus#158]
Hi all,

today I updated my php installation from php 7.1.16 to php 7.1.17 and updated also valet-plus.
I found that the php.ini's first 3 line were pointing to the old php version.

`zend_extension="/usr/local/Cellar/php@7.1/7.1.16/pecl/20160303/xdebug.so"
extension="/usr/local/Cellar/php@7.1/7.1.16/pecl/20160303/geoip.so"
extension="/usr/local/Cellar/php@7.1/7.1.16/pecl/20160303/apcu.so"`

This caused a lot of warnings like this

`Warning: PHP Startup: Unable to load dynamic library ...`

For now i solved to manually edit the php.ini file updating the folder path, and I just wanted to let you know.

**Comment by Neodork** [comment]
@NicolaLeonardi We've some improvements for these problems ready. The next release should set `extension_dir` within your php.ini file. The extension dir will make sure full paths are not required anymore.

**Comment by NicolaLeonardi** [comment]
Thank you guys, always the best! Wish there's a donate button

**Comment by wrongspot** [comment]
@Neodork pecl installs the modules into wrong directory. normaly its enough, to name the module in your php.ini like this

`extension="apcu.so"`

without any path. The extension dir from php is normaly clear. your can grap it like this

`php -i | grep extension_dir
extension_dir => /usr/local/Cellar/php@7.1/7.1.16/lib/php/20160303` 

so, if your modul is called "apcu.so" than it will be searched in that directory. in a standard brew php installation, the command

`pecl install apcu`

will create that modul in a slighty different folder. its placed in

`/usr/local/Cellar/php@7.1/7.1.16/pecl/20160303/apcu.so`

with an symlink like

`ln -s /usr/local/Cellar/php@7.1/7.1.16/pecl/20160303/apcu.so  /usr/local/Cellar/php@7.1/7.1.16/lib/php/20160303/apcu.so` 

works everything fine.

So from my perspectiv of view, pecl needs the right extension directory configured, where to put the extension in, right?

**Comment by Neodork** [comment]
@wrongspot The new release should set your extension_dir directive within the php.ini which should configure the correct directory. The extension_dir location is pulled from the pear configuration which upon switching is changes automatically (with the latest brew). So once we roll out a new release it should be solved.

**Comment by samgranger** [comment]
The new release has been published with @Neodork's pull request, hopefully this solves your issue.

**Comment by NicolaLeonardi** [comment]
I have to wait for a minor release of php@7.1 to see the effect. But sure I will inform you.

**Comment by Neodork** [comment]
@NicolaLeonardi The new release has been release under version number 1.0.17 please check if this resolves your problems.

**Comment by samgranger** [comment]
Closing due to lack of response. New version should solve the issue @NicolaLeonardi

**Comment by NicolaLeonardi** [comment]
@samgranger Sorry for the late reply, my Mac had to be repaired due to a failure of the disk. With version >= 1.0.17 the problem is solved.
