### ISSUE TITLE
default timezone configurable with command

### ISSUE THREAD

**Issue by Xpocalypse** [weprovide/valet-plus#16]
Has to be added to the php.ini, cause Symfony requires it.

**Comment by timneutkens** [comment]
Actually we can do something like this:

```php
$systemZoneName = readlink('/etc/localtime');
$systemZoneName = str_replace('/usr/share/zoneinfo/', '', $systemZoneName);
```

**Comment by timneutkens** [comment]
To fix this you can do a `str_replace` on the contents of `z-performance.ini` here: https://github.com/weprovide/valet-plus/blob/master/cli/Valet/PhpFpm.php#L70

So `$contents = str_replace('TIMEZONE', $systemZoneName, $contents)` and then add `date.timezone = "TIMEZONE"` to `z-performance.ini` here: https://github.com/weprovide/valet-plus/blob/master/cli/stubs/z-performance.ini
