### ISSUE TITLE
Unable to determine linked PHP

### ISSUE THREAD

**Issue by jellesiderius** [weprovide/valet-plus#166]
Hi,

Im using the newest version (1.0.15) of valet-plus and followed the install guide. I am currently getting this error when running 'valet install' : Unable to determine linked PHP.

What can i do to get this working?

![screen shot 2018-05-15 at 12 17 17](https://user-images.githubusercontent.com/8039493/40051171-1996c734-583a-11e8-9c99-cf3ceab5ae42.png)

**Comment by jellesiderius** [comment]
Fixed this myself... php.ini was corrupt 👎

**Comment by rafaelstz** [comment]
You can use this command below to fix it:

    brew link php@7.1 --force --overwrite

**Comment by Mon-Tea** [comment]
@jellesiderius what exactly in php.ini was corrupt .. could you please tell us?
