### ISSUE TITLE
Can't enable ioncube without getting errors - failed loading extension and apcu errors

### ISSUE THREAD

**Issue by iugo-robert** [weprovide/valet-plus#176]
Before:
$ php -v
PHP 7.2.5 (cli) (built: Apr 26 2018 12:07:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5, Copyright (c) 1999-2018, by Zend Technologies

After running command `valet ioncube on`:

$php -v
PHP Warning:  Failed loading Zend extension 'ioncube_loader_dar_7.2.so' (tried: /usr/local/lib/php/pecl/20170718/ioncube_loader_dar_7.2.so (dlopen(/usr/local/lib/php/pecl/20170718/ioncube_loader_dar_7.2.so, 9): image not found), /usr/local/lib/php/pecl/20170718/ioncube_loader_dar_7.2.so.so (dlopen(/usr/local/lib/php/pecl/20170718/ioncube_loader_dar_7.2.so.so, 9): image not found)) in Unknown on line 0

Warning: Failed loading Zend extension 'ioncube_loader_dar_7.2.so' (tried: /usr/local/lib/php/pecl/20170718/ioncube_loader_dar_7.2.so (dlopen(/usr/local/lib/php/pecl/20170718/ioncube_loader_dar_7.2.so, 9): image not found), /usr/local/lib/php/pecl/20170718/ioncube_loader_dar_7.2.so.so (dlopen(/usr/local/lib/php/pecl/20170718/ioncube_loader_dar_7.2.so.so, 9): image not found)) in Unknown on line 0
PHP 7.2.5 (cli) (built: Apr 26 2018 12:07:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5, Copyright (c) 1999-2018, by Zend Technologies

And also when I load any website:

Fatal error: Uncaught Error: Call to undefined function apcu_fetch() in ~/.composer/vendor/weprovide/valet-plus/server.php:37 Stack trace: #0 {main} thrown in ~/.composer/vendor/weprovide/valet-plus/server.php on line 37

**Comment by iugo-robert** [comment]
Last few lines from running `valet ioncube on`

[PECL] ioncube_loader_dar_7.2.so was found, moving to extension directory: /usr/local/lib/php/pecl/20170718
[PECL] Adding ioncube_loader_dar_7.2.so to php.ini...
ioncube_loader_dar successfully installed
[php@7.2] Restarting

I've found that the ioncube_loader_dar_7.2.so file does not exist.

**Comment by Neodork** [comment]
@iugo-robert I've looked into this and confirmed it to be a permissions issue with the downloaded file. Next release should have a fix. A manual solution would be to move the ioncube_loader_7.2.so file to the extension directory `pecl config-show ext_dir`.

**Comment by Neodork** [comment]
@iugo-robert Please try to install ioncube with valet-plus 1.0.17.

**Comment by samgranger** [comment]
Closing ticket due to lack of response from @iugo-robert
