### ISSUE TITLE
Parked paths not working

### ISSUE THREAD

**Issue by papakay** [weprovide/valet-plus#181]
I parked /Library/WebServer/Documents and ``valet paths`` gives the following response

```
Response:
 
[
    "/Library/WebServer/Documents"
]
```

When i enter mysites.test in the browser it shows the index file in /Library/Webserver/Documents instead of showing the content of the /Library/Webserver/Documents/mysites folder inside 

Please how i fix this.

OS: Mac OSX High Sierra
version: Latest Valet plus

**Comment by papakay** [comment]
After trying ``valet open`` from inside the folder, it opened the browser but throw an error.

```
Fatal error: Uncaught Error: Call to undefined function apcu_fetch() in /Users/PAPAKAY/.composer/vendor/weprovide/valet-plus/server.php:37 Stack trace: #0 {main} thrown in /Users/PAPAKAY/.composer/vendor/weprovide/valet-plus/server.php on line 37
```

**Comment by MaxSouza** [comment]
Did you see this issue #133?

**Comment by papakay** [comment]
I'm sorry i didn't see it before posting this. However I tried all the solutions mentioned but none worked for me.

I was forced to go for Laravel Valet instead since there was no much time on my side.

Thanks immensely.
