### ISSUE TITLE
Mailhog not working on custom domain

### ISSUE THREAD

**Issue by guarinogabriel** [weprovide/valet-plus#186]
Hi everyone,

I am using the latest version of Valet Plus, and I am currently experiencing an issue with Mailhog.

Here is a screenshot of the Mailhog panel:
![mailhog](https://user-images.githubusercontent.com/1928452/41133486-9273d7bc-6a9d-11e8-95c8-57e944a6ce2c.png)

I am using a custom domain (.localhost instead of .local), and I already tried to resolve the issue by running:

1. `composer global require weprovide/valet-plus`
2. `valet install`

Is anyone else experiencing this issue?
Please let me know your thoughts.
Thanks!

**Comment by Neodork** [comment]
Could you try another domain instead of localhost? It might conflict with reserver words here and there, I am not sure though. Are there any Javascript errors thrown?

**Comment by guarinogabriel** [comment]
@amarroni – If you can't access the domain, that seems to be a different issue.

Regarding the issue I was experiencing with Valet Plus in June, I didn't try again with the latest version and it seems that nobody else had experienced this problem.
