### ISSUE TITLE
Can't match PHP version.

### ISSUE THREAD

**Issue by dgtllion** [weprovide/valet-plus#187]
Can someone help me with that error? I have php installed via brew like it is told in the installation guide but i am facing those errors when i run this command:

user@macbook~$ **valet fix**
Password:
Removing all old php56- packages from homebrew/php tap
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Removing all old php70- packages from homebrew/php tap
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Removing all old php71- packages from homebrew/php tap
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Removing all old php72- packages from homebrew/php tap
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Removing all old n98-magerun packages from homebrew/php tap
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Removing drush package from homebrew/php tap
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
[php5.6] Disabling modules: apcu, intl, mcrypt
[php7.0] Disabling modules: apcu, intl, mcrypt
[php7.1] Disabling modules: apcu, intl, mcrypt
[php7.2] Disabling modules: apcu, intl, mcrypt
Trying to remove php56...
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Trying to remove php70...
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Trying to remove php71...
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Trying to remove php72...
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Installing and linking new PHP homebrew/core version.
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
Please check your linked php version, you might need to restart your terminal!
**Linked PHP should be php 7.1:
PHP 7.1.18 (cli) (built: May 25 2018 19:18:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.18, Copyright (c) 1999-2018, by Zend Technologies**

**Comment by Neodork** [comment]
Those brew errors are false positives. The fix is already proposed within a pending PR. Continue with the guide.

You can ignore those for now, are there any other problems you're facing?

**Comment by dgtllion** [comment]
i've found my issue i haven't added `--force` to my `brew link php71 --force`
