### ISSUE TITLE
Update error message: Error creating database

### ISSUE THREAD

**Issue by SanderJP** [weprovide/valet-plus#19]
```
Sander-mc:m2_22rc sander$ valet db create
Error creating database
```
I got this error thinking it was something wrong with the directory name, until I read the documentation and figured out the database name is based on the git repo name, and there was none. Maybe update the error message to read: 'Error creating database, no git repo found.' ?
Or even have a fallback to the directory name if there is no git yet.

**Comment by timneutkens** [comment]
Yeah lets do that, but it should fall back to the current directory if it can't find git.

**Comment by timneutkens** [comment]
Fixed in https://github.com/weprovide/valet-plus/commit/e57f24e980a7fc7b1394348349efc1452931ccfb
