### ISSUE TITLE
Can't use PHP5.6

### ISSUE THREAD

**Issue by GuySurname** [weprovide/valet-plus#193]
Just reinstalled Valet+ on a new machine after being off the tool for a while. 

I can't switch to 5.6, it stops and attempts to link to it and then fails with `Unable to determine linked PHP`

```
~ ❯ valet use 5.6
[php@7.1] Unlinking
Unlinking /usr/local/Cellar/php@7.1/7.1.18... 251 symlinks removed

[libjpeg] Relinking
[php@5.6] Linking
Warning: Already linked: /usr/local/Cellar/php@5.6/5.6.36
To relink: brew unlink php@5.6 && brew link php@5.6

[php@5.6] Stopping
[php@7.1] Stopping
[php@7.2] Stopping
PHP Warning:  readlink(): No such file or directory in /Users/***/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 314

Warning: readlink(): No such file or directory in /Users/***/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 314

In Brew.php line 274:

  Unable to determine linked PHP.


use [<phpVersion>]

~ ❯
```

From here, any attempts to relink via Valet or go back to 7.1 throw the same error. I have to relink manually using

```
~ ❯ brew link php@7.1 --force --overwrite
```

But still can't switch back to 5.6. Haven't tried other versions, as I'm mostly interested in 7.1 / 5.6

**Comment by Neodork** [comment]
Try `valet fix` and look for the PECL config output. If is said it's not found you might want to upgrade your current installed PHP versions `brew update && brew upgrade`.

**Comment by GuySurname** [comment]
@Neodork Thanks mate, it actually just started working after I stopped working on it and reset my machine for other reasons.

Glad to have Valet+ back
