### ISSUE TITLE
Issues with mcrypt getting moved into php binaries?

### ISSUE THREAD

**Issue by jacobgraf** [weprovide/valet-plus#194]
I installed Valet+ and was up and running with PHP 7.1. I needed to work on a legacy project so switched over to PHP 5.6 using `valet use 5.6`. Now, I'm stuck. I am getting the following error and from my research it looks like it's caused by `php56-mcrypt` being removed and now mcrypt is built into the brew php binaries. Is there a work-around?

`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-mcrypt/mcrypt.so' - dlopen(/usr/local/opt/php56-mcrypt/mcrypt.so, 9): image not found in Unknown on line`

**Comment by Neodork** [comment]
@jacobgraf You probably have lingering ext-mcrypt.ini files within your `/usr/local/etc/php/7.1/conf.d` You need to remove those and any reference to it from `/usr/local/etc/php/7.1/php.ini`. See https://github.com/weprovide/valet-plus/issues/127#issuecomment-378914908 for further details.

**Comment by samgranger** [comment]
Closing ticket due to no further response. Please follow @N
instructions if you still have this issue.
