### ISSUE TITLE
Valet Plus installs mysql 8, incompatible with older version of Laravel

### ISSUE THREAD

**Issue by agjmills** [weprovide/valet-plus#197]
As MySQL 8 is only supported by Laravel >= 5.5 (https://github.com/laravel/framework/pull/24038) and the HomeBrew 'mysql' package has now been upgraded to MySQL 8, I would recommend pinning the version of MySQL to 5.7

**Comment by Neodork** [comment]
To add to this problem:

When upgrading and MySQL v8 enables itself it will overwrite the `ib_logfile0` and `ib_logfile1` within the `/usr/local/var/mysql` folder. Which makes MySQL 5.6 unable to start due to incompatible log files.

**Comment by agjmills** [comment]
I've created a PR for it (I think I've done it correctly but I'm happy to change it if it's wrong!) https://github.com/weprovide/valet-plus/pull/198

**Comment by Neodork** [comment]
@agjmills LGTM have you tested it by removing all MySQL versions and running `valet install`? If you've I will give a go for this to be merged.

**Comment by agjmills** [comment]
@Neodork I tried as you'd said and realised I'd missed a few bits and pieces. 

I've rectified those and it works as expected now

**Comment by samgranger** [comment]
Closing ticket since issue has been resolved.
