### ISSUE TITLE
Allow Magento 2 setup from local.dev/setup

### ISSUE THREAD

**Issue by SanderJP** [weprovide/valet-plus#20]
Right now Magento 2 can only be installed through the command line with `bin/magento setup:install ...` or `n98-magerun2 install`. Is it possible to allow through `local.dev/setup` as well? 
I have not tested this but I imagine similar problems with other packages like Wordpress?

This would make it a lot more accessible to people with less experience with the command line.
It might be useful to add some short installation instruction for Magento(2) using `n98-magerun(2) install` or even add a valet magerun2 install command or something like that ;)

**Comment by timneutkens** [comment]
> I have not tested this but I imagine similar problems with other packages like Wordpress?
It's Magento2 only. Wordpress installer works just fine.

1. I fixed the Magento2 installed 😄 :
![screen shot 2017-07-08 at 22 25 31](https://user-images.githubusercontent.com/6324199/27989013-0aa595d8-6430-11e7-9571-f79a63dd1cca.png)

2. I added a page for when there's no `env.php` or `config.php`, cause Magento throws some non-descriptive errors when they're not there 👍 
![screen shot 2017-07-08 at 22 51 11](https://user-images.githubusercontent.com/6324199/27989010-fe9bf606-642f-11e7-83de-6d6a39449f11.png)
