### ISSUE TITLE
use dev.example.com as development url

### ISSUE THREAD

**Issue by MikeYV** [weprovide/valet-plus#203]
Hi, is it possible to use the url "dev.example.com" as development url without blocking all .com domains ?

**Comment by MikeYV** [comment]
I have found a solution.

Change domain to com ( valet domain com )
edit ~/.valet/dnsmasq.conf
 - Change: **.com** to **dev.example.com**

Restart valet

**Comment by samgranger** [comment]
Glad you managed to find a solution!
