### ISSUE TITLE
`open` ignore default browser settings

### ISSUE THREAD

**Issue by Igloczek** [weprovide/valet-plus#205]
For unknown reason `valet open` always use Safari, no matter which browser I set as default in system settings.

I have this problem for at least few months, so it's not related to latest updates.

Valet+ 1.0.18
macOS High Sierra 10.13.5

**Comment by samgranger** [comment]
I'm assuming the command might need to be ran under the current user. Will investigate this issue.

**Comment by mischabraam** [comment]
Can confirm that `valet open` is run under the `root` user. Which has safari as default browser.

**Comment by mischabraam** [comment]
Fixed in 73b7ecd8f5147392feb74198fd2311e4bd6c17ad, will be in next release

**Comment by mischabraam** [comment]
Available in `1.0.21`
