### ISSUE TITLE
Drupal 7 not working

### ISSUE THREAD

**Issue by SanderJP** [weprovide/valet-plus#21]
Not sure if it's my local setup but I can't seem to get a Drupal 7 site working, any idea?

![image](https://user-images.githubusercontent.com/2470914/28010645-d92323a0-655f-11e7-8c3a-dc0c83083717.png)

Also `drush cc all` is giving me:
```
No Drupal site found, only 'drush' cache was cleared.  
```
Even though I have a settings.php with (I think) the right db settings:
```
$databases['default']['default'] = array(
  'driver' => 'mysql',
  'database' => 'project',
  'username' => 'root',
  'password' => 'root',
  'host' => 'localhost',
  'prefix' => '',
  'collation' => 'utf8_general_ci',
);
```

**Comment by timneutkens** [comment]
https://www.perfexcrm.com/knowledgebase/console-error-content_decoding_failed/ according to this it might be related to `zlib.output_compression`.

**Comment by timneutkens** [comment]
Could you try adding `ini_set('zlib.output_compression', 1);` to your index.php, if it works I'll try to add it to the default `php.ini` 👍

**Comment by SanderJP** [comment]
My bad, Drupal 7 doesn't support php 7 yet so that was giving errors :)
