### ISSUE TITLE
Valet Drivers do not support proxying

### ISSUE THREAD

**Issue by tkrause** [weprovide/valet-plus#213]
Valet in it's current state doesn't support proxying a request to another port while preserving the headers. For any applications that need HTTPS and the correct host header this is just not possible in Valet and require manual configuration.

This is a huge deal breaker for SPAs that use hot loading like Nuxt.js as well as Swoole. 

We've submitted a PR that seeks to solve this issue by allowing Nginx to proxy the requests instead of the Valet driver. 

#212

**Comment by samgranger** [comment]
Closing this ticket as we have added your PR to Valet+'s new 1.0.19 release! Thank you for your contribution.
