### ISSUE TITLE
Valet Nginx FPM stuck on 5.6 despite "use 7.0", "use 7.1", "use 7.2"

### ISSUE THREAD

**Issue by capitaladot** [weprovide/valet-plus#214]
```valet fix```
No change

```valet uninstall && valet install```
No change.

Confirmed it is the Valet nginx instance, as ```valet stop``` stops serving pages

**Comment by capitaladot** [comment]
```valet fix```
No change

```valet uninstall && valet install```
No change.

Confirmed it is the Valet nginx instance, as ```valet stop``` stops serving pages

**Comment by samgranger** [comment]
I know others have encountered this issue - restarting a machine completely usually solves this for me (only required once) but I think someone pinpointed it to `~/.valet/valet.sock` at one point.

Are you still encountering this? If so, I'd like to investigate this issue further.

**Comment by samgranger** [comment]
Closing this as I think it's related to #207 and #177

**Comment by samgranger** [comment]
Quick update, the new 1.0.19 version does an unlink before linking on switching PHP versions - hopefully, this will solve the issue.
