### ISSUE TITLE
Version of symfony/process breaks 5.6

### ISSUE THREAD

**Issue by capitaladot** [weprovide/valet-plus#215]
```$ valet secure
Password:
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in ~.composer/vendor/symfony/process/Process.php on line 140

Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in ~/.composer/vendor/symfony/process/Process.php on line 140
```

Should be pegged to a version that doesn't require >= 7

**Comment by capitaladot** [comment]
v3.4.12 seems to work

**Comment by Neodork** [comment]
I can confirm symfony/process v4 not being compatible with PHP 5.6 and thus breaking valet-plus.

**Comment by cagartner** [comment]
Has a correction for this? Or I need to rollback the valet to 1.0.17?

**Comment by samgranger** [comment]
Closing this ticket as we have reverted the `symfony/process` v4 commit in Valet+'s new 1.0.19 release. Please upgrade! :)
