### ISSUE TITLE
Ability to disable redis, mailhog, rabbitmq and varnish

### ISSUE THREAD

**Issue by regularlabs** [weprovide/valet-plus#217]
Would love to see options to (temporarily) disable redis, mailhog, rabbitmq and varnish.
Starting and running these only use up time and memory when not always needed.

**Comment by samgranger** [comment]
I agree that this would be a nice addition. For now, you can disable Redis for example by changing <true /> to <false /> in `~/Library/LaunchAgents/homebrew.mxcl.redis.plist` underneath `RunAtLoad`.

**Comment by regularlabs** [comment]
Thanks, but that doesn't work.
It just overwrites the file with it set to `<true/>` again after doing a `valet start`.
(Yes, I first did a `valet stop`, then changed those plist files).

Also, there are only plist files for redis and mailhog. Not for rabbitmq and varnish.

Something like this would be awesome:
`
valet start --no-redis --no-mailhog --no-rabbitmq --no-varnish
`

**Comment by mischabraam** [comment]
`valet varnish off`
`valet rabbitmq off`
Are these not sufficient (for varnish and rabbitmq)?

**Comment by regularlabs** [comment]
I see support for this has just been added:
`valet mailhog stop`
Can the same be added for these?
```
valet redis stop
valet rabbitmq stop
valet varnish stop
```

**Comment by regularlabs** [comment]
I see support for this has just been added by @mischabraam:
`valet mailhog stop`
https://github.com/weprovide/valet-plus/commit/93c4cf6ddd6bcbeb50228acc27cb788a321af85d

Can the same be added for these?
```
valet redis stop
valet rabbitmq stop
valet varnish stop
```

**Comment by mischabraam** [comment]
@regularlabs, yes, the intention is to do that indeed. Will do that pretty soon.

**Comment by regularlabs** [comment]
Ok, very nice :)

**Comment by mischabraam** [comment]
`valet mailhog off|disable|on|enable` is now available in version 1.0.20. Can you please let me know how this works out for you?

**Comment by regularlabs** [comment]
After updating valet I get this error on all `valet` commands:
`Could not open input file: /cli/valet.php`

**Comment by regularlabs** [comment]
I don't have a weprovide.com email address or an invite.

**Comment by mischabraam** [comment]
Yeah I know, my mistake, changed it. Can you try https://join.slack.com/t/valet-plus/signup

**Comment by regularlabs** [comment]
`This team's administrator has not enabled email signups.`

**Comment by mischabraam** [comment]
True, just changed that to invite only. I would need your email (any) to send you an invite

**Comment by mischabraam** [comment]
Ah found it. You can join https://join.slack.com/t/valet-plus/shared_invite/enQtNDE2MjU2NzgyNjQwLTc4MmI0ZTlhM2FiODRjNmQxN2RlZDVlN2E2YjUwMDBjNGViYjVkNWQ4ODJjYzI3M2U4ZGM5M2Q3ZGQ3ZDQ2YjY

**Comment by regularlabs** [comment]
Ok, issue with my valet setup has been fixed by you guys (thanks!)

I can confirm that `valet mailhog on` and `valet mailhog off` work.
Mailhog gets added/removed from the (re)start list when doing a `valet start` too.
So all good.

**Comment by regularlabs** [comment]
```
➜  ~ valet mailhog on
[mailhog] Restarting

➜  ~ valet start
[dnsmasq] Restarting
[nginx] Restarting
[mysql@5.7] Restarting
[redis] Restarting
[mailhog] Restarting
[rabbitmq] Restarting
[varnish] Restarting
Valet services have been started.

➜  ~ valet mailhog off
[mailhog] Stopping

➜  ~ valet start
[dnsmasq] Restarting
[nginx] Restarting
[mysql@5.7] Restarting
[redis] Restarting
[rabbitmq] Restarting
[varnish] Restarting
Valet services have been started.
```

**Comment by mischabraam** [comment]
`
valet redis on|off
valet varnish on|off
valet rabbitmq on|off
`

Added in 4a00ec1fab7d0803d22eb1744febf08cb97c5a99, will be in next release

**Comment by regularlabs** [comment]
Very cool :)

**Comment by mischabraam** [comment]
Available in `1.0.21`

**Comment by regularlabs** [comment]
All seems good.
tested:
```
valet mailhog on/off
valet redis on/off
valet rabbitmq on/off
valet varnish on/off
```

**Comment by regularlabs** [comment]
Much better:
```
➜  ~ valet start
[dnsmasq] Restarting
[nginx] Restarting
[mysql@5.7] Restarting
Valet services have been started.
```
:)
