### ISSUE TITLE
wildly different server speed

### ISSUE THREAD

**Issue by philbraun** [weprovide/valet-plus#218]
Created 3 instances of the same WordPress site under valet+, all using the exact same process: copy all theme and plugin files, then migrating the database and media files using Migrate DB Pro from the original running under Local by Flywheel (Docker/VirtualBox).

First instance of the site is blazing fast, as expected from Valet+. The second and third sites though, both also an exact copy, are about three times slower – when site one opens a backend page in ~560ms, site two takes 2.62s and site three 2.65s. Same site/same page opens in 1.43s under virtualboxed Linux and Docker.

Is that some sort of normal behaviour for Valet+ – only one site running at full speed?

**Comment by samgranger** [comment]
I wouldn't call it normal - trying to figure out how we could debug your issue.

**Comment by philbraun** [comment]
Tried again today after fixing valet+ MySQL (set up without root password on all new installs, fix) - now Valet+ blazes away like lightning, almost 3 times faster than Local by Flywheel or MAMP, and up to 6 times faster than Docker.
