### ISSUE TITLE
Magento2 in production mode gives 404 Not Found for js-translation.json requests.

### ISSUE THREAD

**Issue by Vinai** [weprovide/valet-plus#219]
The `cli/drivers/Magento2ValetDriver.php` always delegates to `pub/static.php` even if the file exists (regardless of the deploy mode).
In production mode this causes a 404 Not Found response since no asset generation is triggered.

Currently the code looks like this:

```php
if (strpos($uri, '/js-translation.json') === false && file_exists($staticFilePath = $sitePath . '/pub' . $uri)) {
    return $staticFilePath;
}

if(strpos($uri, '/js-translation.json') !== false) {
    header('Cache-Control: no-store, must-revalidate');
}

if (strpos($uri, '/static/') === 0) {
    $_GET['resource'] = $resource;
    include($sitePath . DIRECTORY_SEPARATOR . 'pub' . DIRECTORY_SEPARATOR . 'static.php');
    exit;
}
```
So for `js-translation.json` files it always falls through to the inclusion of `pub/static.php`.

A solution that works for me is to move the branch that calls `header('Cache-Control: no-store, must-revalidate');` above the check if the file exists, and remove the condition if it's a `js-translation.json` from the branch that returns `$staticFilePath`:

```php
if (strpos($uri, '/js-translation.json') !== false) {
    header('Cache-Control: no-store, must-revalidate');
}

if (file_exists($staticFilePath = $sitePath . '/pub' . $uri)) {
    return $staticFilePath;
}

if (strpos($uri, '/static/') === 0) {
    $_GET['resource'] = $resource;
    include($sitePath . DIRECTORY_SEPARATOR . 'pub' . DIRECTORY_SEPARATOR . 'static.php');
    exit;
}
```

**Comment by samgranger** [comment]
Could you submit this as a PR?

**Comment by Vinai** [comment]
Sure. Two things stopped me from doing so in the first place:

1. There are a bunch of open PRs so I'm not sure that the project is taking PRs
2. I might have missed another reason for not serving `js-translation.json` directly besides adding the no-cache header.

This works for me with 2.2.4 and 2.2.5 and I tested in developer and production mode, but I might be missing something.
Do you maybe have any insight?

**Comment by samgranger** [comment]
We are taking PR's - I am not aware of reasons for not serving js-translation.json directly - I'll try and get this feature added in the upcoming release.

**Comment by samgranger** [comment]
Closing this ticket as we have added your PR to Valet+'s new 1.0.19 release! Thank you for your contribution.
