### ISSUE TITLE
Magento 1 cannot load core javascript file

### ISSUE THREAD

**Issue by SanderJP** [weprovide/valet-plus#23]
I've installed a Magento 1 webshop and everything works except when I go to the admin forget password form (http://project.dev/index.php/admin/index/forgotpassword/). It's trying to dynamically load javascript files through the following URL:
`http://project.dev/js/index.php/x.js?f=prototype/prototype.js,prototype/validation.js,mage/adminhtml/events.js,mage/adminhtml/form.js,scriptaculous/effects.js` but this gives a 404.
index.php has logic to deal with the /x.js but I think Valet+ is trying to read index.php as a directory or something.
Any idea's ?

**Comment by timneutkens** [comment]
Easiest fix is to disable js merging from the looks of it.

**Comment by SanderJP** [comment]
Merging is off, it's the way the index.php is picked up by Valet I think, `x.js` is not actually a file.
But I've managed to get in and I don't see this error anywhere else, so for now it doesn't matter too much.

**Comment by timneutkens** [comment]
Cool, i'm going to close this as we haven't experienced issues because of it.

**Comment by anitr** [comment]
How did you solve this problem?

**Comment by SanderAtom** [comment]
I did not solve the problem, but you should be able to reset the admin password through something like [magerun2](https://github.com/netz98/n98-magerun2#change-customer-password)

**Comment by anitr** [comment]
Yes, or by changing template to button type="submit". But I wanted to get rid of console errors :(

**Comment by Flipmediaco** [comment]
Our hosting was serving static files via Ngnix and PHP via Apache. The routing rule was incorrectly seeing the request path as ending with ".js" so routing the request to Ngnix resulting in a 404. If this is your case then a rule forcing requests  to "/js/index.php" to be proceed by Apache will resolve the issue.
