### ISSUE TITLE
Cannot list DB's - mysqli::__construct(): (HY000/2002) no such file or directory

### ISSUE THREAD

**Issue by KilianPM** [weprovide/valet-plus#233]
Upgraded to 1.0.19.

```
Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /Users/****/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 254
Failed to connect to database
PHP Warning:  mysqli_real_escape_string(): Couldn't fetch mysqli in /Users/***/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 275
```
Have run `brew doctor`, `valet fix` and the like.

**Comment by samgranger** [comment]
Could you check this ticket out to see if the steps mentioned solve your issue? https://github.com/weprovide/valet-plus/issues/208

If so, I will have to look into merging the steps into `valet fix`

**Comment by KilianPM** [comment]
After following JPry's steps, I'm getting `ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)` (password I'm using is `root`)

**Comment by KilianPM** [comment]
Dug further into issues and found: #56 

This has fixed it

**Comment by KilianPM** [comment]
After a reboot today, I'm running into the initial issue again

```
PHP Warning:  mysqli::__construct(): (HY000/2002): No such file or directory in /Users/****/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 254
```

**Comment by samgranger** [comment]
Could you share the output of `brew services ls`? Can you check which version of mysql is running?

**Comment by KilianPM** [comment]
`mysql --version`:
```
mysql  Ver 15.1 Distrib 10.3.8-MariaDB, for osx10.13 (x86_64) using readline 5.1
```

`brew services ls`:
```
Name    Status  User   Plist
dnsmasq started root   /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mailhog started *** /Users/***/Library/LaunchAgents/homebrew.mxcl.mailhog.plist
mariadb started *** /Users/***/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
nginx   started root   /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php@5.6 stopped
php@7.0 stopped
php@7.1 started root   /Library/LaunchDaemons/homebrew.mxcl.php@7.1.plist
redis   started *** /Users/***/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

**Comment by rafaelstz** [comment]
I solved it using this command:

```bash
mysqladmin -u root --password='root' password root
```

**Comment by samgranger** [comment]
Closing this issue.

**Comment by atty31** [comment]
I am facing the same or similar issue. See error message after i execute valet db list: 
PHP Warning:  mysqli::__construct(): (HY000/2002): No such file or directory in /Users/atillanaghi/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 284

Warning: mysqli::__construct(): (HY000/2002): No such file or directory in /Users/atillanaghi/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 284
Failed to connect to database
PHP Warning:  mysqli_real_escape_string(): Couldn't fetch mysqli in /Users/atillanaghi/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 305

Warning: mysqli_real_escape_string(): Couldn't fetch mysqli in /Users/atillanaghi/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php on line 305
