### ISSUE TITLE
ping magento2.test after install, reboot returns 100% packet lost

### ISSUE THREAD

**Issue by cuongtran-6618** [weprovide/valet-plus#238]
Hi,

I have a trouble during install valet in MAC. Can you guy please help me out? 
I used to have MAMP and docker but I have uninstalled that and reboot already. I followed the install instruction but after install valet plus, using 
`sudo valet install` and reboot system

I ping the test site and it just return 100% packet lost.
Here is my pecl list:

Installed packages, channel pecl.php.net:
Package Version State

`apcu  5.1.12  stable |
apcu_bc 1.0.4   stable |
geoip   1.1.1   beta`

Here is my php version: 

`PHP 7.1.20 (cli) (built: Jul 20 2018 10:27:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.20, Copyright (c) 1999-2018, by Zend Technologies`

**Comment by samgranger** [comment]
Could you share the output of `brew services ls`? If you join our Slack channel we can help you further - probably a bit more practical :)

**Comment by tiikeri86** [comment]
Thank @samgranger for response. here is the out put of brew services ls. Could you please point out what is slack channel?

dnsmasq           	started root     
elasticsearch@2.4 	started cutranqu 
mailhog           	started cutranqu 
mysql             		stopped
mysql@5.7         	started cutranqu 
nginx             		started root     
php@7.1           	started root     
redis             		started

Here is what is in terminal when I try to install valet plus

`sudo valet fix`

PHP 7.1.12 (cli) (built: Nov 27 2017 15:53:40) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans


`sudo valet install`
[php] Checking for errors within the php installation...
[nginx] Stopping
[php@7.1] Stopping
[php@7.2] Stopping
[mysql@5.7] Stopping
[redis] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[binaries] Installing binaries
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions
apcu_bc is already installed, skipping...
apcu_bc successfully enabled
geoip is already installed, skipping...
geoip successfully enabled
[PECL-CUSTOM] Installing extensions
[php@7.1] Restarting
[dnsmasq] Restarting
[mysql@5.7] Stopping
[mysql@5.7] Configuring
[mysql@5.7] Restarting
[redis] already installed
[redis] Restarting
[mailhog] already installed
[mailhog] Restarting
[nginx] Restarting
Setting password for root user failed.

Valet installed successfully!

ping foobar.test
PING foobar.test (127.0.0.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4

**Comment by SanderAtom** [comment]
I see you get the error `Setting password for root user failed.`, can you try this? https://github.com/weprovide/valet-plus/issues/246#issuecomment-421583402

**Comment by tiikeri86** [comment]
Hi,

I followed that but still no luck with that

**Comment by SanderAtom** [comment]
I see that you have 2 MySQL's installed:
```
mysql stopped
mysql@5.7 started cutranqu
```
Can you check your path variable with `echo $PATH` to see if the old MySQL is loaded through any of those path directories?
Also what does `which mysql` show?

You can join the gitter chatroom here: https://gitter.im/valet-plus/Lobby

**Comment by tiikeri86** [comment]
which mysql shows that /usr/local/bin/mysql and I have 2 path ( I using Mamp right now and wanna switch to valet)
export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH=/Applications/MAMP/bin/php/php7.1.12/bin:$PATH

I gotta run now, will check that when I come home

**Comment by SanderAtom** [comment]
Right and if you type `ls -l /usr/local/bin/mysql` you can see where it's symlinked to, it should be to the `Cellar` directory so you know it's the `brew` instance.

**Comment by tiikeri86** [comment]
Yes, it is the Cellar directory as you mentioned before so what I should do next?

**Comment by VincentMarmiesse** [comment]
Hi,
I have the same issue and none of the solution worked for me.
`ls -l /usr/local/bin/mysql` shows the right path:
```
/ur/local/bin/mysql -> ../Cellar/mysql@5.7/5.7.24/bin/mysql
```

but I still have the error message `Setting password for root user failed.`.

**Comment by brendanfalkowski** [comment]
For reference, I had to forcefully remove all traces of MySQL and reinstall with Valet Plus to get it working again. I documented the issue and processes here:

- https://manuals.gravitydept.com/develop/environment-setup/valet-plus
- https://manuals.gravitydept.com/develop/command-line/brew

**Comment by AntonEvers** [comment]
```
$ valet install --with-mariadb
[php] Checking for errors within the php installation...
[nginx] Stopping
[valet-php@5.6] Stopping
[valet-php@7.0] Stopping
[valet-php@7.1] Stopping
[valet-php@7.2] Stopping
[valet-php@7.3] Stopping
[mariadb] Stopping
[redis] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[binaries] Installing binaries
[BREW TAP] henkrehorst/php already installed
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions
	apcu_bc is already installed, skipping...
	apcu_bc is already enabled, skipping...
	geoip is already installed, skipping...
	geoip is already enabled, skipping...
[PECL-CUSTOM] Installing extensions
[valet-php@7.1] Restarting
[dnsmasq] Restarting
[mariadb] Stopping
[mariadb] Configuring
[mariadb] Restarting
[redis] already installed
[redis] Restarting
[mailhog] already installed
[mailhog] Restarting
[nginx] Restarting
Setting password for root user failed.

Valet installed successfully!
```

Then I logged into the database and reset the root password to an empty string.
```
$ mysql -uroot
$ ALTER USER 'root'@'localhost' IDENTIFIED BY '';
$ ALTER USER 'root'@'127.0.0.1' IDENTIFIED BY '';
$ ALTER USER 'root'@'::1' IDENTIFIED BY '';
```

```
$ valet install --with-mariadb
[php] Checking for errors within the php installation...
[nginx] Stopping
[valet-php@5.6] Stopping
[valet-php@7.0] Stopping
[valet-php@7.1] Stopping
[valet-php@7.2] Stopping
[valet-php@7.3] Stopping
[mariadb] Stopping
[redis] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[binaries] Installing binaries
[BREW TAP] henkrehorst/php already installed
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions
	apcu_bc is already installed, skipping...
	apcu_bc is already enabled, skipping...
	geoip is already installed, skipping...
	geoip is already enabled, skipping...
[PECL-CUSTOM] Installing extensions
[valet-php@7.1] Restarting
[dnsmasq] Restarting
[mariadb] Stopping
[mariadb] Configuring
[mariadb] Restarting
[redis] already installed
[redis] Restarting
[mailhog] already installed
[mailhog] Restarting
[nginx] Restarting

Valet installed successfully!
```

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
