### ISSUE TITLE
Did not get front controller from driver. Please return a front controller to be executed.

### ISSUE THREAD

**Issue by wowcut** [weprovide/valet-plus#239]
After a while of not using valet I was trying to get back to it on a mac and all I get it this error message:
```
Did not get front controller from driver. Please return a front controller to be executed.
```
what was the meaning of this error? dns seems to be ok, paths and links do exist on the system. 
It would be great if the error message could give some hints about why it happened.

**Comment by mischabraam** [comment]
Valet has an auto-detection to load a driver according to your website's folder and file structure. If none of the drivers can be detected this error occurs. Do you have an index.php? Is it in the root or web etc?
This is usually the problem, but it can occur on other scenario's as well.

**Comment by davemacaulay** [comment]
@wowcut which application where you trying to host? I find this can happen by accident if you have the application within an additional folder Valet doesn't expect or you're using an unsupported application.

**Comment by AdrianSanduleasa** [comment]
I'm having the same issue with Valet+ on Magento 2. 
I tried in project root: 
1. valet link && valet config, result is:
`Current working directory linked to magento2.test

Configuring Magento 2...

Setting base url...

Setting elastic search hostname...

Enabling URL rewrites...

Flushing cache...

Configured Magento 2`
2. valet open, result is "Did not get front controller from driver. Please return a front controller to be executed." in browser.

**Comment by samgranger** [comment]
Did you run `valet park` in the root folder containing all your projects? Closing this ticket but please re-open if still encountering issues.
