### ISSUE TITLE
Composer global update does not update Valet+

### ISSUE THREAD

**Issue by SanderJP** [weprovide/valet-plus#24]
Not sure if this is my configuration but when I ran `composer global update`, Valet+ was not updated.
In fact it was downgrading some dependencies as if it couldn't find Valet+. I saw the Valet+ require in `~/.composer/composer.json` with version `"^0.2.3"`.
Als running `composer global show` shows:
`weprovide/valet-plus 0.2.3   Blazing fast macOS PHP development environment`

I had to use `composer global require weprovide/valet-plus:0.4.0` to install the latest version.

**Comment by timneutkens** [comment]
Hmm I wonder if we should document `composer global update weprovide/valet-plus`

**Comment by SanderJP** [comment]
I can check on the next release if that is sufficient.

**Comment by timneutkens** [comment]
Just tested. It works. Updated the docs.
