### ISSUE TITLE
'valet secure' secures wrong name if another link is present

### ISSUE THREAD

**Issue by SanderAtom** [weprovide/valet-plus#241]
Not sure if this is my environment specific or out of the box, but I'm in folder `nameA` with an extra link through `valet link nameB` and when I exec `valet secure` it's securing `nameB` and not the current directory `nameA`.

**Comment by SanderAtom** [comment]
(this might be my environment, I suspect an update to openssl is causing this)

**Comment by mischabraam** [comment]
`valet secure -h`
Shows you can follow this command with a domain to secure. You can use this to bypass your problem. Also when making a link you can directly secure it, see `valet link -h`.

I'm not sure what the basic functionality should be. Will be back on this.

**Comment by SanderAtom** [comment]
This was due to an update to the `openssl` library some time before, but for some reason that was not a problem until later. Closing as it's not a problem anymore.
