### ISSUE TITLE
symfony/process error and Laravel/valet to Valet + Upgrade

### ISSUE THREAD

**Issue by dustbuster** [weprovide/valet-plus#245]
Hello!
So I have been a long term fan of laravel valet, and my question is as follows. 

Every time i try to install valet plus, i run into this error: 

➜ composer global require weprovide/valet-plus
Changed current directory to /Users/dustin/.composer
Using version ^1.0 for weprovide/valet-plus 
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - weprovide/valet-plus 1.0.1 requires symfony/process ~2.7|~3.0 -> satisfiable by symfony/process[2.7.x-dev, 2.8.x-dev, 3.0.x-dev, 3.1.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.35, v2.7.36, v2.7.37, v2.7.38, v2.7.39, v2.7.4, v2.7.40, v2.7.41, v2.7.42, v2.7.43, v2.7.44, v2.7.45, v2.7.46, v2.7.47, v2.7.48, v2.7.49, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.0-BETA1, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.0-BETA1, v3.1.0-RC1, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9] but these conflict with your requirements or minimum-stability.

I try to upgrade to valet + every couple days and solve the issues, but i am rather new to composer, and if my problem isn't you app, my apologies, i am just trying to use your software and i could use a little help. 

Here's my global composer.json
```
"require": {
        "laravel/installer": "^2.0",
        "consolidation/cgr": "^2.0",
        "symfony/process": "^4.1",
        "laravel/valet": "^2.0"
 }
```

Also, say we do get this installed, do I have to completely delete the old valet?
The commands are the same, and without having the old valet purged, I don't see how this will work. 
Maybe a valet to valet + upgrade procedure would be helpful! 
Thanks!

**Comment by SanderAtom** [comment]
Does this help? https://github.com/weprovide/valet-plus/issues/28

**Comment by dustbuster** [comment]
Thanks Bud. It might. For now I have been using php -s and running localhost. 
I guess since i am using that, and it's working i may just take apart my valet installation and start over with plus. I think part of my problem is composer. It's so not user friendly.

**Comment by SanderAtom** [comment]
Yeah you have to completely remove Valet to install Valet+. The command Valet+ `valet fix` has been added which handles some problems in regards to Homebrew chances, but you might run into some config files/paths left over which could cause different problems. You can join https://gitter.im/valet-plus/Lobby for more direct help.

**Comment by rafaelstz** [comment]
I fixed it using these commands:

```bash
brew reinstall composer
composer clearcache
cd ~/.composer
composer require weprovide/valet-plus --no-update
composer update -vvvv
valet
```

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
