### ISSUE TITLE
Shopware5ValetDriver.php is not loaded

### ISSUE THREAD

**Issue by SanderAtom** [weprovide/valet-plus#248]
The `Shopware5ValetDriver` driver is missing from the list of drivers to include in `cli/drivers/ValetDriver.php`.

**Comment by Adioz01** [comment]
I have the same error here too ✌️

**Comment by iainhubbard** [comment]
This looks to be fixed in commit https://github.com/weprovide/valet-plus/commit/a8e69235596c076dcf316eb9dd3335c358218387

If you cant wait for the release you can add `$drivers[] = 'Shopware5ValetDriver';` to `vendor/weprovide/valet-plus/cli/drivers/ValetDriver.php`

**Comment by kayyyy** [comment]
I had the same error today.
In my case i just copied the code to a new custom driver called `ShopwareValetDriver`.

**Comment by mischabraam** [comment]
Version 1.0.22 released with dynamically loaded drivers
