### ISSUE TITLE
FR: 'valet reimport [file]' or create db when using import on non-existing db

### ISSUE THREAD

**Issue by SanderJP** [weprovide/valet-plus#25]
When you use 'valet db import [file]' but the database doesn't exist yet, you get the error `ERROR 1049 (42000): Unknown database 'project'`. It would be nice if the database is created if it doesn't exist.
Also I use 'valet db drop && valet db create && db import [file]' as a one-liner for re-installing a database, if that could be 'valet db reimport [file]', that would be awesome!

**Comment by timneutkens** [comment]
Great idea! Adding now.

**Comment by timneutkens** [comment]
Added in `0.4.2`

**Comment by timneutkens** [comment]
https://github.com/weprovide/valet-plus/releases

**Comment by SanderJP** [comment]
:+1:
