### ISSUE TITLE
How to uninstall and completly remove Valet+ ?

### ISSUE THREAD

**Issue by ladetryne** [weprovide/valet-plus#253]
Like the title suggest I am looking for a way to completly remove Valet+ so that I can reinstall. Reason is I have done something that completly broke it and I dont have the know how to fix this issue. please help me with to find a solution to completly uninstall and remove so I can install it from scratch again :)

**Comment by BenSpace48** [comment]
Have you tried `composer global remove weprovide/valet-plus`?

**Comment by samgranger** [comment]
Reinstalling homebrew might help, are you running on Mojave?

**Comment by iugo-robert** [comment]
This is a handy gist for uninstalling Valet+

https://gist.githubusercontent.com/dannygsmith/5b74ba708d7bf8621c1cb6b959ece99f/raw/f1b0e88ba4e0a753b112bd2187c22bf8eaa9a234/valet-plus-destroy

Be careful if you intend to keep your mysql databases though.

**Comment by samgranger** [comment]
Closing this issue as answered by @iugo-robert

**Comment by rafaelstz** [comment]
To optimize the execution of the @iugo-robert script you can run it directly via the raw file provided via link with this command:

```
bash <(curl -s https://gist.githubusercontent.com/dannygsmith/5b74ba708d7bf8621c1cb6b959ece99f/raw/f1b0e88ba4e0a753b112bd2187c22bf8eaa9a234/valet-plus-destroy)
```
