### ISSUE TITLE
Changing the Version of PHP Hoses Valet on Mojave

### ISSUE THREAD

**Issue by realto619** [weprovide/valet-plus#257]
I've reinstalled Mojave 3 times now on a new partition and then installed valet plus on it each time successfully. However, when I change the version of PHP to 5.6, it totally hoses the install. After that, running valet returns the following error: 

`/usr/local/bin/valet: line 60: 41430 Segmentation fault: 11  php "$DIR/cli/valet.php" "$@"`

Has anyone else had this issue or know how to resolve it and restore valet? 

Thanks in advance,
Paul

**Comment by mischabraam** [comment]
https://github.com/Homebrew/homebrew-core/issues/32434
https://github.com/Homebrew/homebrew-core/issues/32497

**Comment by samgranger** [comment]
Closing this issue, should be resolved now.
