### ISSUE TITLE
The default 404 template is not showing/working

### ISSUE THREAD

**Issue by Luuk2016** [weprovide/valet-plus#259]
If I go to a Valet url that doesn't exist I get the following text:
"Did not get front controller from driver. Please return a front controller to be executed."

I was wondering how to see the 404 template that is provided with ValetPlus.
I really would like to have an overview of all my parked sites.

Thanks.

**Comment by SanderAtom** [comment]
I've fixed a bug that prevented the overview from being shown, PR is here #267.

**Comment by Serializator** [comment]
PR is merged, this issue can be closed.
