### ISSUE TITLE
Problem installing: [UnexpectedValueException] RecursiveDirectoryIterator::__construct(/usr/local/var/mysql): failed to open dir: No such file or directory

### ISSUE THREAD

**Issue by karudonaldson** [weprovide/valet-plus#262]
OS X Mojave
PHP 7.1.23
Master branch

valet install --with-mariadb                                                                                                                                   
[php] Checking for errors within the php installation...
[nginx] Stopping
[php@7.1] Stopping
[mysql@5.7] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[binaries] Installing binaries
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions
	apcu_bc is already installed, skipping...
	apcu_bc is already enabled, skipping...
	geoip is already installed, skipping...
	geoip is already enabled, skipping...
[PECL-CUSTOM] Installing extensions
[php@7.1] Restarting
[dnsmasq] Restarting
[mysql@5.7] Stopping
[mysql@5.7] Configuring

 [UnexpectedValueException]
 RecursiveDirectoryIterator::__construct(/usr/local/var/mysql): failed to open dir: No such file or directory

install [--with-mariadb]

**Comment by rafaelstz** [comment]
I solved it running:

```
brew link mysql@5.7 --force
valet fix && valet install
```
