### ISSUE TITLE
Command "fix" is not defined.

### ISSUE THREAD

**Issue by emateu** [weprovide/valet-plus#263]
Hi guys, following the readme https://github.com/weprovide/valet-plus#installation

Steo 6, after running `valet fix` I'm getting:
```
Command "fix" is not defined.
```

<img width="1153" alt="screen shot 2018-11-06 at 15 18 51" src="https://user-images.githubusercontent.com/629964/48084754-511eee80-e1d7-11e8-9046-2258815f3175.png">

**Comment by samgranger** [comment]
Indeed, somehow laravel/valet got mixed in with our releases in packagist. Our apologies!
