### ISSUE TITLE
Cannot extend custom drivers because of dynamic loading

### ISSUE THREAD

**Issue by TommyKolkman** [weprovide/valet-plus#264]
We've got a custom driver setup for Magento 2 in our project root as LocalValetDriver.php. 

This class extends Magento2ValetDriver, but since [this](https://github.com/weprovide/valet-plus/pull/237/commits/345d080afebdcca92bb9c2e747d95b6d27e02416) PR was merged, we are unable to extend, the driver is not on the require list anymore.

As a temp fix we now patch cli/drivers/require.php, but surely there's a better option?

**Comment by cagartner** [comment]
Need to verify this, we need to rollback the PR manually to make work the LocalValetDriver.php

**Comment by jellesiderius** [comment]
Can confirm, having the same issue!

**Comment by JPry** [comment]
I'm also having this problem. This was caused by #237.

**Comment by samgranger** [comment]
This has been fixed in the latest version of Valet+, see https://github.com/weprovide/valet-plus/commit/35cdc69047e17a92007edeed6ff5c15727e2e065
