### ISSUE TITLE
JSON:API call returns Bad request because 'q' is a violation of spec.

### ISSUE THREAD

**Issue by SanderAtom** [weprovide/valet-plus#268]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Using JSON:API in Drupal returns a `Bad request 400` with this message:
`The following query parameters violate the JSON API spec: 'q'.`

**What was supposed to happen?**
A valid JSON:API response.

**What actually happened?**
A Bad request response.

**How to reproduce this?**
Install drupal/jsonapi in a Drupal 8 installation and visit `site.test/jsonapi`.

**What is the solution?**
Remove the following lines all together:
```
if (!isset($_GET['q']) && !empty($uri) && $uri !== '/' && strpos($uri, '/jsonapi/') === false) {
    $_GET['q'] = $uri;
}
```
I cannot find any reason to set the uri in `q` since this should be handled by apache/nginx and Drupal.

Note: I've been running with these lines commented out for months, both Drupal 7 and 8 sites, without any problems.

Original message:
------------------
Hi,

I'm using JSON:API to make a rest call to retrieve information from Drupal, but it returns a `Bad request 400` with this message:
`The following query parameters violate the JSON API spec: 'q'.`

I have no problems with other calls like an access token from oAauth, seems to be specific to the JSON:API.

Did anyone see this before, or know how to fix this?

**Comment by samgranger** [comment]
We have added a fix: https://github.com/weprovide/valet-plus/blob/master/cli/drivers/DrupalValetDriver.php#L56

This will be included in the next release.

**Comment by ptoly** [comment]
This fix didn't work for me when running Drupal 8. The JsonAPI spec calls for camel casing and, technically, the 'q' here isn't camel cased, so it coughed up a hairball (400). Changing the parameter to a capital Q fixed it.

**Comment by SanderAtom** [comment]
I'm re-opening this issue to add a PR to remove those lines all together. I've been running with these lines removed for months and have not experienced any downsides. JSON:API, auto-complete and multi-site in Drupal work just fine without them and it seems to have been added from the start and might not be relevent anymore.
I'll update the issue description.

**Comment by Neodork** [comment]
Closing, this was merged and released.
