### ISSUE TITLE
Valet db export

### ISSUE THREAD

**Issue by SanderJP** [weprovide/valet-plus#27]
1. You can use `valet db export` inside the right directory and it'll export the database of that directory to `[name].sql`. If you want to change the name of the file, you have to use `valet db export [db] [filename]` which makes you retype the current directory. If the directory and filename parameters are reversed you can use `valet db export [filename]`, which uses the current directory if omitted.

2. I keep typing `valet db export dir filename.sql` so I end up with `filename.sql.sql`, I expect to have to type in the full filename.

3. If you can add a date (or date-time) format to the default sql name, I probably don't have to use the full command as much to change the name, since I usually add the date of the export.

**Comment by timneutkens** [comment]
Hi Sander,
Thanks for the feedback ❤️ , Sam/me have implemented all your suggestions. 
See https://github.com/weprovide/valet-plus/releases
