### ISSUE TITLE
SQLSTATE[HY000]: General error: 1018 Can't read dir of '.'

### ISSUE THREAD

**Issue by guarinogabriel** [weprovide/valet-plus#274]
Hi everyone,

I am experiencing the following error when I try to access the Magento admin panel:
``
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[HY000]: General error: 1018 Can't read dir of '.' (errno: 24 - Too many open files), query was: SELECT `constraints`.`CONSTRAINT_NAME` AS `name`, `info`.`TABLE_NAME` AS `table_name`, `info`.`REFERENCED_TABLE_NAME` AS `reference_table_name`, `info`.`COLUMN_NAME` AS `field_name`, `info`.`REFERENCED_COLUMN_NAME` AS `reference_field_name`, `constraints`.`DELETE_RULE` AS `delete_strategy` FROM `information_schema`.`KEY_COLUMN_USAGE` AS `info`
 INNER JOIN `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `constraints` ON constraints.CONSTRAINT_NAME = info.CONSTRAINT_NAME AND constraints.CONSTRAINT_SCHEMA = info.CONSTRAINT_SCHEMA WHERE (info.REFERENCED_TABLE_NAME IS NOT NULL) AND (info.CONSTRAINT_SCHEMA = 'databasename')
Exception #1 (PDOException): SQLSTATE[HY000]: General error: 1018 Can't read dir of '.' (errno: 24 - Too many open files)
``

I reviewed the MySQL configuration in the `/usr/local/etc/my.cnf` file, however the "open_files_limit" parameter is set to 999999 as can be seen here: https://github.com/weprovide/valet-plus/blob/b660397f29805b67da694549da2c8c0576063794/cli/stubs/my.cnf

Has anyone experienced the same issue?

Thanks in advance!

**Comment by guarinogabriel** [comment]
I close this issue since I was able to resolve it.

The solution was to increase the "open files limit" setting for MacOS as documented here:
https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c

**Comment by rafaelstz** [comment]
I didn't need to run all the instructions of this link above, I just run:

```bash
ulimit -n 200000
ulimit -u 2048
valet fix
valet install
```

And all projects worked well even without restart my Mac.
