### ISSUE TITLE
PHP 7.0 not found

### ISSUE THREAD

**Issue by samgranger** [weprovide/valet-plus#277]
For those that are encountering issues with php@7.0, Homebrew has removed PHP 7.0 since it has reached EOL.

We are currently in the process of creating a new brew tap to solve this issue.

**Comment by dheesbeen** [comment]
@samgranger At the moment i'm using this tap https://github.com/eXolnet/homebrew-deprecated

**Comment by Neodork** [comment]
Hey there, we have started development on this issue please refer to: https://github.com/weprovide/valet-plus/issues/298

**Comment by samgranger** [comment]
This has been fixed in the new release.
