### ISSUE TITLE
`valet use 7.2` Uses PHP 7.3, Ends Using 7.1

### ISSUE THREAD

**Issue by leepeterson** [weprovide/valet-plus#280]
```
  valet use 7.2
Password:
[php@7.1] Unlinking
Unlinking /usr/local/Cellar/php@7.1/7.1.25... 207 symlinks removed
...
[php@7.2] Linking
Unlinking /usr/local/Cellar/php/7.3.0... 176 symlinks removed
Linking /usr/local/Cellar/php/7.3.0... 24 symlinks created
[php@7.1] Stopping
[php] Stopping
...
[php] Restarting
Valet is now using php
...
  php -v
PHP 7.1.25 (cli) (built: Dec  7 2018 08:24:41) ( NTS )
```

Also, why is root being used for things that don't require root?

**Comment by regularlabs** [comment]
Should be fixed with (already merged): #272 
And improved and hopefully merged later with: #283

**Comment by samgranger** [comment]
Hi regularlabs, we will create a new release tomorrow, will update this ticket when it's ready!

**Comment by regularlabs** [comment]
Ok, great. What about #283 ?
Will that make it in?

**Comment by theozzz** [comment]
Hi @samgranger 

When the release will be available?

Kind Regards,

Theo

**Comment by Neodork** [comment]
Hey there, we have started development on this issue please refer to: https://github.com/weprovide/valet-plus/issues/298

**Comment by samgranger** [comment]
This has been fixed in the new release.
