### ISSUE TITLE
Add support for phpbrew compiled php versions

### ISSUE THREAD

**Issue by Edicatax** [weprovide/valet-plus#285]
I want to use Valet+ with a self-compiled php version so I can make use of threads.  I am using phpbrew as outlined in [this article](https://medium.com/@rossbulat/true-php7-multi-threading-how-to-rebuild-php-and-use-pthreads-bed4243c0561) and I see no way of telling Valet+ to use that version.  Is there a chance this can be added in the future, or alternatively is there a way for me to manually switch php versions to the compiled one in Valet+?

**Comment by samgranger** [comment]
This can be achieved by creating your own homebrew tap.
