### ISSUE TITLE
Installation fails with mariadb already installed

### ISSUE THREAD

**Issue by wowcut** [weprovide/valet-plus#29]
The installation process fails when mariadb was already installed with brew:
```
Error: Cannot install mysql because conflicting formulae are installed.
  mariadb: because mysql, mariadb, and percona install the same binaries.
...
```
The flexibility of valet+ is what makes it a plus for me - that should include using it with mariadb.

**Comment by timneutkens** [comment]
@wowcut Mariadb support added in https://github.com/weprovide/valet-plus/releases/tag/0.5.5

`valet install --with-mariadb`
