### ISSUE TITLE
valet-plus version 1.0.24 missing on packagist.org

### ISSUE THREAD

**Issue by bjoern-flagbit** [weprovide/valet-plus#292]
Just want to let you know that version **1.0.24** can not installed when doing a update.

Because it is missing here:
https://packagist.org/packages/weprovide/valet-plus

**Comment by Neodork** [comment]
Potential cause: https://github.com/weprovide/valet-plus/blob/1.0.24/cli/valet.php still being set to 1.0.23.

**Comment by samgranger** [comment]
1.0.24 ended up being buggy, we are working on a new release!

**Comment by samgranger** [comment]
1.0.25 has been released.
