### ISSUE TITLE
PHP 5.6 removed from homebrew-core

### ISSUE THREAD

**Issue by Nathanw** [weprovide/valet-plus#294]
PHP 5.6 was removed from homebrew core in this commit: https://github.com/Homebrew/homebrew-core/commit/37b075c205d3398e298889c11914afb16c8f5c25 so when running `valet use 5.6` valet breaks due to not being able to install 5.6 also they seem to have removed `7.0` as they discussed in the PR for this here: https://github.com/Homebrew/homebrew-core/pull/35679.

**Comment by pgrenaud** [comment]
Not that we condone the use of deprecated software, but I've setup a tap at my organisation to be able to support older software that were not migrated yet. I've already added the php 5.6 and 7.0 formulae.

You can find the tap here: https://github.com/eXolnet/homebrew-deprecated

**Comment by Neodork** [comment]
Hey there, we have starting development on this issue please refer to: https://github.com/weprovide/valet-plus/issues/298

**Comment by samgranger** [comment]
This has been solved with the new release.
