### ISSUE TITLE
PHPStorm XDebug Breaking twice

### ISSUE THREAD

**Issue by hrtrulz** [weprovide/valet-plus#296]
I just setup Valet Plus and I created a simple test project in PHPStorm to test debugging of code. It is work but for some reason, it breaking twice on the same code. Why would it do that and how can I get it to only break once?

**Comment by Neodork** [comment]
@hrtrulz did this resolve your problem? https://github.com/weprovide/valet-plus/issues/157

**Comment by hrtrulz** [comment]
I changed the settings to be 2 max connections and seems to be working ok at the moment

**Comment by Neodork** [comment]
@samgranger Close please.

**Comment by hrtrulz** [comment]
I actually worked what causing it, it happens when I use the url with the file name like http://site.test/ and not http://site.test/index.php

Not sure why it does it tho.

**Comment by samgranger** [comment]
Closing for now, if this remains an issue please re-open and we will investigate further!

**Comment by paul-gene** [comment]
I too am experiencing this issue.
