### ISSUE TITLE
Unable to run valet use -php_version-

### ISSUE THREAD

**Issue by kupoback** [weprovide/valet-plus#308]
When running `valet use 7.2` as mentioned in the Read Me, I get the following error when it unlinks and relinks. The only way to resolve it, in which it defers back to php version 7.1, is to run `valet fix`

```
user$ valet use 7.2
[php@7.1] Unlinking
Unlinking /usr/local/Cellar/valet-php@7.1/7.1.25... 131 symlinks removed

[libjpeg] Relinking
[php@7.2] Linking
Warning: Already linked: /usr/local/Cellar/valet-php@7.2/7.2.13
To relink: brew unlink valet-php@7.2 && brew link --force valet-php@7.2

[valet-php@7.1] Stopping
[valet-php@7.2] Stopping
[valet-php@7.3] Stopping
[BREW TAP] henkrehorst/php already installed
PHP Warning:  readlink(): No such file or directory in /Users/user/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 314

Warning: readlink(): No such file or directory in /Users/user/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 314

In PhpFpm.php line 307:

  Unable to determine linked PHP.


use [<phpVersion>]
```

**Comment by samgranger** [comment]
What do you get when running `which php`, is it pointing to `/usr/local/bin/php`?

**Comment by kupoback** [comment]
It is. This is on a fresh install following the instructions posted on the Read Me.

**Comment by samgranger** [comment]
7.2 seems to link to `/usr/bin/php` instead of `/usr/local/bin/php` here, a fix would be running the following command after trying to switch to 7.2: `ln -s /usr/local/Cellar/valet-php@7.2/7.2.13/bin/php /usr/local/bin/php`. The odd thing is, after doing so & switching again to 7.1 and back to 7.2 I'm not getting this issue anymore. Will investigate a bit more. Are you running on Mojave, or?

**Comment by kupoback** [comment]
Hmmm, ran that, then `valet xdebug on` somehow got enabled, and as I had phpStorm open, it errored out as it couldn't serve. Might have to be another topic for support, but yes, running your command did fix it.

**Comment by samgranger** [comment]
Feel free to jump onto our Slack - we're always happy to help you out there!

**Comment by samgranger** [comment]
Closing this ticket since your issue has been resolved.
