### ISSUE TITLE
Cannot complete "valet install"

### ISSUE THREAD

**Issue by Floctopus** [weprovide/valet-plus#311]
After updating to the latest version i get the following error/output when running: "valet install"

```
[php] Checking for errors within the php installation...
[nginx] Stopping
[mysql@5.7] Stopping
[redis] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[binaries] Installing binaries
[valet-php@7.1] Installing
Error: No available formula with the name "valet-php@7.1"
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
Error: No similarly named formulae found.
==> Searching taps on GitHub...
==> Searching for similarly named formulae...
==> Searching taps...
Error: No formulae found in taps.


In Brew.php line 107:

  Brew was unable to install [valet-php@7.1].


install [--with-mariadb]
```

**Comment by Neodork** [comment]
Hey please do `brew tap henkrehorst/php`. I'll look into the installation this weekend to test if any problems arise when switching from a homebrew/core php version.

**Comment by theozzz** [comment]
Hi All,

Same issue for me, downgrading valet right now, waiting for Neodork feedback in order to update again.

Kind Regards,

Theo

**Comment by philbraun** [comment]
Same error here.
Did the `brew tap henkrehorst/php ` dance multiple times, but got
`dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.62.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Abort trap: 6
` every time.
`brew upgrade composer` and additional various`brew reinstall php` and `brew install valet-php@7.2` did not help, but `valet fix` and re-re-re-re-re-re-`install valet` apparently did.

**Comment by Floctopus** [comment]
I ended up solving it by using the following uninstall script: https://gist.github.com/dannygsmith/5b74ba708d7bf8621c1cb6b959ece99f/
**I ended up removing the Mysql section from the script**  to leave alone my mysql config and db's

After running the script i installed Valet Plus according to the installation instructions on the repo.
And poof... Like magic. it all worked again!

**Comment by Neodork** [comment]
Hey guys so I haven't been able to reproduce this over the course of the weekend. Could any of you provide me with `brew tap` output and provide `php -v` and the `php.ini path`?

**Comment by robrecord** [comment]
```
$ brew tap
buo/cask-upgrade
homebrew/apache
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/dupes
homebrew/nginx
homebrew/services
```

```
$ php -v
PHP 7.3.1 (cli) (built: Jan 10 2019 13:15:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.1, Copyright (c) 1999-2018, by Zend Technologies
```

```
Configuration File (php.ini) Path => /usr/local/etc/php/7.3
Loaded Configuration File => /usr/local/etc/php/7.3/php.ini
Scan this dir for additional .ini files => /usr/local/etc/php/7.3/conf.d
Additional .ini files parsed => /usr/local/etc/php/7.3/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.3/conf.d/xdebug.ini,
/usr/local/etc/php/7.3/conf.d/z-performance.ini
```

**Comment by fransyrcc** [comment]
I updated  valet plus and had the same problem. You might want to run `brew tap henkrehorst/php` before updating

**Comment by samgranger** [comment]
As mentioned, this issue is was to the switch to the new `henkrehorst/php` tap. Closing this issue.

**Comment by adamlindqvist** [comment]
Just adding how I solved it if anyone ends up here:

`brew upgrade`

and then

`brew cleanup`

**Comment by fresh-a** [comment]
> I updated valet plus and had the same problem. You might want to run `brew tap henkrehorst/php` before updating

This is useful!Thanks
