### ISSUE TITLE
Listing all sites available is a huge privacy violation

### ISSUE THREAD

**Issue by trepatudo** [weprovide/valet-plus#312]
Some people, like me, were using the original valet with nginx to host the pages directly to internet (open ports 80,443) which would facilitate certain processes instead of having to share a ngrok link.

With valet-plus, the concept of showing all pages creates an easy way for anyone on internet to know what I'm working on. 

This is actually valid for LAN too and even tho it's nice for localhost it's actually quite careless to show all projects you are working on to other people.

**Comment by samgranger** [comment]
I have merged your PR!
