### ISSUE TITLE
Error: invalid option: --with-http2 when installing on Mojave

### ISSUE THREAD

**Issue by lfolco** [weprovide/valet-plus#314]
I am running a clean install (having removed all traces of Valet+) and I'm running into the following error when running `valet install`:

```
[nginx] Installing
Usage: brew install [options] formula

Install formula.

formula is usually the name of the formula to install, but it can be specified
in several different ways.

Error: invalid option: --with-http2

In Brew.php line 107:

Brew was unable to install [nginx].
```

Has anyone else run into this issue?

**Comment by samnabi** [comment]
I'm getting this issue as well.

**Comment by agdelarosa** [comment]
I was able to install valet by editing this file:
~/.composer/vendor/weprovide/valet-plus/cli/Valet/Nginx.php

Edit line 43
$this->brew->installOrFail('nginx', ['--with-http2']);
to 
$this->brew->installOrFail('nginx', ['']);
