### ISSUE TITLE
php 7.3.1+ upgrade

### ISSUE THREAD

**Issue by code2prog** [weprovide/valet-plus#316]
Is there any way to update valet-php@7.3 to version 7.3.1?
Laravel queue has some issues on 7.3.0
Thanks

**Comment by Neodork** [comment]
Please create an issue at: https://github.com/henkrehorst/homebrew-php

**Comment by henkrehorst** [comment]
solved: https://github.com/henkrehorst/homebrew-php/issues/3

**Comment by Neodork** [comment]
@code2prog Please confirm.

**Comment by code2prog** [comment]
@Neodork it's ok now

**Comment by Neodork** [comment]
@samgranger Please close.

**Comment by samgranger** [comment]
Thanks @Neodork !
