### ISSUE TITLE
Magento 2 admin hangs

### ISSUE THREAD

**Issue by paul-gene** [weprovide/valet-plus#322]
I am trying to get a fresh M2 setup running, and I can access the homepage and the admin login fine.

As soon as I enter the correct credentials and click sign in, the request is pending for 20+ minutes.

I have redis setup in my env.php file, php 7.1 running and its M2 v2.3.0.

**Comment by samgranger** [comment]
Are you getting any errors in `~/.valet/Log`?

**Comment by DigitalStartupUK** [comment]
@paul-gene Did you ever resolve this? I just ran into the same issue. But may have fixed itself after about an hour of downtime?

**Comment by sy-salvo** [comment]
Hi everyone, 
same error here. 

- fresh valet plus install 
- magento 2.3.1 
- this is the error i find in nginx-error.log: 

2019/05/04 23:06:08 [error] 256#0: *356 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /admin_magento/admin/index/index/key/5bc9c783daac7bbf07275c77b0f9a96c64934afa84849537a92f88f3e259d8a9/ HTTP/1.1", upstream: "fastcgi://unix:/Users/salvatorecapritta/.valet/valet.sock:", host: "www.magento.test", referrer: "http://www.magento.test/admin_magento/admin/index/index/key/5bc9c783daac7bbf07275c77b0f9a96c64934afa84849537a92f88f3e259d8a9/"

ty

**Comment by rafaelstz** [comment]
Same error, frontend is perfect but when access admin page I'm receiving an error **504 Gateway Time-out**.

#### valet log nginx
```
2019/06/04 20:21:51 [error] 67692#0: *149 upstream timed out (60: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: m22.test, request: "POST /admin/admin/index/index/key/719432d237d2dfdc45d3f0b204c7f463e2dac509d50581144b1848f8204ec010/ HTTP/2.0", upstream: "fastcgi://unix:/Users/rafael/.valet/valet.sock", host: "m22.test", referrer: "https://m22.test/admin/admin/index/index/key/719432d237d2dfdc45d3f0b204c7f463e2dac509d50581144b1848f8204ec010/"
```
#### valet log nginx
```
[04-Jun-2019 20:26:00] WARNING: [pool www] child 69421 exited with code 124 after 314.262670 seconds from start
```

**Comment by sy-salvo** [comment]
Still facing this error, only on macbook, imac goes well (mojave on both)

**Comment by rafaelstz** [comment]
Hey @gsomoza, I saw your PR https://github.com/weprovide/valet-plus/pull/326 do you know how could we solve it?

**Comment by SanderAtom** [comment]
Can you try and add `fastcgi_read_timeout 3600;` to `/usr/local/etc/nginx/valet/valet.conf` with in the `location ~ \.php$ {` block and restart nginx with `valet restart nginx`?
Also which magento caches are enabled? If you disable all caching, everything will take way longer.

**Comment by gsomoza** [comment]
With my PR, the FastCGI timeout is increased to 3600 seconds, which is one hour. All reports here mention the error happens before the hour. 

So for those cases the only things that I can imagine would cause an earlier timeout:

1. The timeout could be happening further down the stack (not in Nginx). For example maybe the www pool (PHP FastCGI) is timing out, which seems to be the case for @rafaelstz's error output. Make sure the timeout settings for the PHP FastCGI process are high enough.
2. The `fastcgi_read_timeout` on my PR was not applied correctly to the environment.
     1. Maybe the version of Valet+ being run is not the one with my PR? Probably not the case with @sy-salvo
    2. The 3600 timeout is being overwritten on a different nginx file?
    3.  For some reason the nginx configuration file being used might be different than the one shipped with Valet?

**Comment by gsomoza** [comment]
By the way, to be more specific, in case of #1 please check PHP's `max_execution_time` and also the FastCGI pool's `request_terminate_timeout` setting (must be 0). Also make sure the FastCGI pool is not overriding PHP settings through `php_value[max_execution_time]` for example

**Comment by sy-salvo** [comment]
thanks @gsomoza 
i'll try asap and give u a feeback

**Comment by rafaelstz** [comment]
When I installed Valet again to try, it worked even without any customization, thank you anyway.

**Comment by sy-salvo** [comment]
Hi everyone, finally found time to check my macbook valet problems. 

Seems to be solved now. 

This is what i did: 
- upgraded my valet version
- uninstalled mysql@5.7 (which gave me problems) 
- re-installed mysql@5.7 (laso removed /usr/local/var/mysql/ content)
- reinstalled valet
- configured mysql root password with mysql_secure_installation

now working with 2.2.x and 2.3.x version :))) 

 hope it can be useful for someone

**Comment by Neodork** [comment]
Dear Contributor,

With the release of Valet+ `2.0.0` the Valet+ development team and contributors have implemented the [contribution guidelines](https://github.com/weprovide/valet-plus/blob/master/CONTRIBUTING.md#issue-templates). The contribution guidelines aim to improve the support and workflow of Valet+. For further information why this was implemented please check https://github.com/weprovide/valet-plus/issues/393.

We're closing this ticket because it does not follow the correct format. If you feel your ticket is still relevant we encourage you to re-open your ticket using the [correct format](https://github.com/weprovide/valet-plus/issues/new/choose).

Kind regards,
The Valet+ team
