### ISSUE TITLE
PhpMyAdmin

### ISSUE THREAD

**Issue by wontroba666** [weprovide/valet-plus#334]
hello, is there any possibility to install Phpmyadmin ? 

Sequel Pro has no search in the entire database (strange)

**Comment by ershagen** [comment]
You can just download PMA from here: https://www.phpmyadmin.net/
And then add it to your Sites folder. Then login with your username and password.

**Comment by wontroba666** [comment]
you rocks! thx

**Comment by samgranger** [comment]
@wontroba666 I assume you are using the nightly build? The filters have been moved (you can now also define multiple filters). See the filter icon at the bottom of the window in nightly.
