### ISSUE TITLE
Clean url prestashop

### ISSUE THREAD

**Issue by oliwerhelsen** [weprovide/valet-plus#339]
Hi Guys,

I need some help with clean URLs for Prestashop together with Valet plus. 
Is there any way to do something like *a2enmod rewrite* to activate it. 

Thanks in advance!

**Comment by oliwerhelsen** [comment]
Yeah, stupid me. I just read the docs and understand that I needed a valet driver to handle this.

**Comment by samgranger** [comment]
You might be able to find inspiration or just copy paste this driver: 

https://github.com/chrigarc/prestashop-driver-laravel-valet

If it works, let me know - if that's the case I can ask the author if we can merge it into Valet+
