### ISSUE TITLE
icu4c version 64

### ISSUE THREAD

**Issue by dheesbeen** [weprovide/valet-plus#343]
Last friday i did a brew update and it installed icu4c version 64. 
After that the valet php versions stopped working. The brew 'native' version worked after a reinstall. 
Reinstalling valet php versions didn't work. Is this something that needs to be fixed in valet plus or in the henkrehorst/php taps?

**Comment by alexvandervegt** [comment]
You can downgrade icu4c following this:

http://hanxue-it.blogspot.com/2018/08/macos-homebrew-installing-older-version-of-software.html
