### ISSUE TITLE
valet fix ends with error

### ISSUE THREAD

**Issue by snHolst** [weprovide/valet-plus#344]
Removing all old php56- packages from homebrew/php tap

Removing all old php70- packages from homebrew/php tap

Removing all old php71- packages from homebrew/php tap

Removing all old php72- packages from homebrew/php tap

Removing all old n98-magerun packages from homebrew/php tap

Removing drush package from homebrew/php tap

[php5.6] Disabling modules: apcu, intl, mcrypt
[php7.0] Disabling modules: apcu, intl, mcrypt
[php7.1] Disabling modules: apcu, intl, mcrypt
[php7.2] Disabling modules: apcu, intl, mcrypt
Installing and linking new PHP homebrew/core version.
**Error: No such keg: /usr/local/Cellar/valet-php@7.1**

I have not found a solution to the problem yet.
MacOS Mojave: 10.14.4 (18E227)

**Comment by kevinvarley** [comment]
@snHolst to fix this do:

`brew tap henkrehorst/php
brew reinstall valet-php@7.1`

Then you should be able to re-run:

`valet fix`

Without error
