### ISSUE TITLE
"Non-static method Valet\Mailhog::updateDomain() should not be called statically in "weprovide/valet-plus/cli/Valet/Nginx.php"

### ISSUE THREAD

**Issue by viniciusfabri** [weprovide/valet-plus#348]
Hi,
I think an issue has been introduced in this commit: https://github.com/weprovide/valet-plus/commit/abeeeb3f79dc6e29621114b2e6bc797f9829e09d

On cli/Valet/Nginx.php two new methods are being called statically, while they're not static. This is breaking valet install for me.

Checking the package out to tag 1.0.27 seems to have solved the issue for me. Not sure why master was set up by default

**Comment by viniciusfabri** [comment]
Log of valet install:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/11316647/57414667-74027d80-71cf-11e9-9d93-1fcad34772cc.png">

**Comment by SanderAtom** [comment]
If I run `composer require weprovide/valet-plus` it will install version `1.0.27`, so not sure why it installed `master` for you. But yea that does seem like a bug that needs to be fixed.

**Comment by mischabraam** [comment]
This is fixed in since version `1.0.28`, see commit 806bd97
