### ISSUE TITLE
extension="apcu.so" occurs multiple times causing error PHP Warning:  Module 'apcu' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by WinstonN** [weprovide/valet-plus#349]
Hi

I'm looking at using Valet+ for Magento2 local development - we're currently using docker

On installation, things started throwing errors, in particular
```
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
```
and
```
PHP Parse error:  syntax error, unexpected 'apcu' (T_STRING), expecting ',' or ')' in Command line code on line 2
```
Searching through the issues did not yield a fix, and so, looking at my system, in this file:
```
/usr/local/etc/valet-php/7.1/php.ini
```
I see this in the beginning of that file
```
extension_dir = "/usr/local/lib/php/pecl/20160303"
zend_extension="xdebug.so"
extension="apcu.so"
extension="geoip.so"
extension="apcu.so"
extension="apcu.so"
extension="apc.so"
extension="apc.so"
``` 
My question is, why is that duplication there, and what is the "valet way" for removing that?

**UPDATE**:
Manually removing those duplicate entries (the order seems tom change between 7.1 and 7.2) gets rid of the errors

**UPDATE**:
After enabling xdebug I see the duplication is back - could be the culprit?
```valet xdebug on --remote_autostart=1```

/usr/local/etc/valet-php/7.1/php.ini
```
zend_extension="xdebug.so"
extension_dir = "/usr/local/lib/php/pecl/20160303"
zend_extension="xdebug.so"
extension="apcu.so"
extension="apcu.so"
extension="geoip.so"
```

**Comment by WinstonN** [comment]
I saw this today on my colleague laptop
I had to set
```
export LDFLAGS="-L/usr/local/opt/valet-php@7.1/lib"
export CPPFLAGS="-I/usr/local/opt/valet-php@7.1/include"
```
Closing this ticket because it can be fixed

**Comment by ericclaeren** [comment]
I am running into the same issue, have added the export flags to my ~/.bash_profile file, but after running 'valet install' the issue returns and the double extensions are set.

**Comment by brendanfalkowski** [comment]
I experienced the same issue after uninstalling and installing Valet+. Error message:

```
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected 'apcu' (T_STRING), expecting ',' or ')' in Command line code on line 2
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0
PHP Parse error:  syntax error, unexpected 'apcu' (T_STRING), expecting ',' or ')' in Command line code on line 2
PHP Warning:  Module 'apcu' already loaded in Unknown on line 0

Warning: Module 'apcu' already loaded in Unknown on line 0
Could not open input file:
Warning: Module 'apcu' already loaded in Unknown on line 0

Parse error: syntax error, unexpected 'apcu' (T_STRING), expecting ',' or ')' in Command line code on line 2/cli/valet.php
```

## Failed — adding flags to my shell profile

Tried adding this to my shell profile, but it didn't affect the error:

```
export PATH="/usr/local/opt/valet-php@7.1/bin:$PATH"
export PATH="/usr/local/opt/valet-php@7.1/sbin:$PATH"
export LDFLAGS="-L/usr/local/opt/valet-php@7.1/lib"
export CPPFLAGS="-I/usr/local/opt/valet-php@7.1/include"
```

## Succeeded — editing `php.ini`

I'm guessing the duplicates are leftover from the previous Valet+ install, and the install doesn't de-duplicate them. When I checked the `php.ini` file for each PHP version that Valet installed this is what I found initially:

### File: /usr/local/etc/valet-php/7.1/php.ini

Initially there was a duplicate entry for `apcu.so`:

```
extension="apcu.so"
extension="apc.so"
extension="apcu.so"
extension_dir = "/usr/local/lib/php/pecl/20160303"
```

Which I changed to:

```
extension="apcu.so"
extension="apc.so"
extension_dir = "/usr/local/lib/php/pecl/20160303"
```

Then ran `valet install` which succeeded:

![Screen Shot 2019-09-05 at 11 35 18 AM](https://user-images.githubusercontent.com/214924/64369466-42f55680-cfd1-11e9-994d-5afdd3397b6c.png)

But failed to setup the MySQL root password properly, so I ran:

```
brew link --force mysql@5.7
valet install
```

Which then fully worked.

And afterward that `php.ini` file had been rewritten with:

```
extension="apcu.so"
extension="geoip.so"
extension="yaml.so"
extension="apc.so"
extension_dir = "/usr/local/lib/php/pecl/20160303"
```

### File: /usr/local/etc/valet-php/7.2/php.ini

The 7.2 `php.ini` didn't have any extensions listed before/after trying to fix and running `valet install`. After switching I had to make similar changes to its `php.ini` file.

**Comment by brian-labelle** [comment]
I ran into the same issue with 7.1. I followed the fix provided by @brendanfalkowski to remove the duplicate apacu.so extension, and the installation succeeded.

**Comment by lfolco** [comment]
Could we reopen this? It seems to occur on a fresh install (removing the php.ini files and reinstalling everything).

**Comment by jfelisco** [comment]
Issue on duplicate `apcu.so` and `apc.so` will occur again when changing `php version`. I need to remove duplicates every time I change `php version`. Ticket should be reopen.

**Comment by maiorano84** [comment]
This is also occurring on a colleague's laptop on a fresh install.

The install command duplicates the apcu.so extension and then later results in a failure that prevents the install process from completing, making this package completely unusable.

Ended up going with a standard Laravel Valet install and enabled XDebug myself.

**Comment by stilfx** [comment]
Brand new imac, fresh Mavericks install, same issue. Moving back to Laravel Valet for now.

**Comment by guerinteedmike** [comment]
I am having same issue - brand new iMac, Mojave 10.14.16 install as well. Keep running into issues including this one. 

Does this have a resolution?

**Comment by alpfilho** [comment]
R.I.P valet-plus
3 days trying to make this work
Moving back to Laravel Valet for now too.

**Comment by squishz** [comment]
What worked for me was removing all the lines at the top of:
`usr/local/etc/valet-php/7.1/php.ini`

I went from:
```
extension="apcu.so"
extension="apc.so"
extension="apcu.so"
extension_dir = "/usr/local/lib/php/pecl/20160303"
[PHP]

;;;;;;;;;;;;;;;;;;;
; About php.ini   ;
```

and changed that to only have

```
[PHP]

;;;;;;;;;;;;;;;;;;;
; About php.ini   ;
```

I then run
`valet fix`
`valet install`

Which made it install without a problem for me.

**Comment by mattLaakvand** [comment]
Well done. Clever boy.

**Comment by Evertt** [comment]
@squishz that works, but it's only a temporary work-around. There's definitely a bug somewhere that causes these duplications to happen. I keep getting them back.

**Comment by JeSTeRFLA** [comment]
OK heres the deal i found with mine

root@AntiSec:/etc/php/7.3# find . -name "*apc*"
./embed/conf.d/20-apcu.ini
./embed/conf.d/25-apcu_bc.ini
**./fpm/conf.d/20-apcu.ini**            <------- fpm apcu loaded 1st time
./fpm/conf.d/25-apcu_bc.ini
**./fpm/conf.d/30-apcu.ini**            <------- fpm apcu loaded 2nd time
**./cli/conf.d/20-apcu.ini**            <------- cli apcu loaded 1st time
./cli/conf.d/25-apcu_bc.ini
**./cli/conf.d/30-apcu.ini**            <------- cli apcu loaded 2st time
./cgi/conf.d/20-apcu.ini
./cgi/conf.d/25-apcu_bc.ini
./mods-available/apcu_bc.ini
./mods-available/apcu.ini
**./apache2/conf.d/20-apcu.ini**        <------- apache apcu loaded 1st time
./apache2/conf.d/25-apcu_bc.ini
**./apache2/conf.d/30-apcu.ini**        <------- apache apcu loaded 2st time
./phpdbg/conf.d/20-apcu.ini
./phpdbg/conf.d/25-apcu_bc.ini

SO, i removed the 30-apcu.ini's and message went away and has not came back.
and my apcu still works find, actually it works better and faster after i removed the duplicates.
