### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by CrixuAMG** [weprovide/valet-plus#35]
`Parse error: syntax error, unexpected '' - dlopen(/usr/local/opt/php7' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' in Command line code on line 3/cli/valet.php
` 
Got this error on calling `valet install`.
I have installed php71, on a 2016 macbook pro, latest updates.

**Comment by SanderJP** [comment]
Did you follow the Installation instructions? https://github.com/weprovide/valet-plus#installation

**Comment by timneutkens** [comment]
So, I've seen this before when a colleague installed php71 it didn't actually link php71 to /usr/local/bin/php. Instead it kept using the default php version (5.5 / 5.6) could you check `php -v`? Thanks!

**Comment by CrixuAMG** [comment]
Output of `php -v`:

```PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies```

I followed the instructions to the letter :)

**Comment by CrixuAMG** [comment]
Just solved it by reinstalling PHP and some of the extensions. For me it turned out to be PHP71-Imagick causing the issue. Thanks for helping!

**Comment by timneutkens** [comment]
Great!
