### ISSUE TITLE
Question around 404 / paths / SSL

### ISSUE THREAD

**Issue by WinstonN** [weprovide/valet-plus#351]
Hi

I'd like to try Valet+ with Magento2 because I have heard some great reviews about it, currently I am using docker - on a mac <scream_face>

I installed valet+ and it looks to be working 
My site project folder looks like this

```
project directory
...
├── CHANGELOG.md
├── LocalValetDriver.php // I added this to try and get my multi sites to work - however, this does not work 
├── README.md
├── src // this is the magento root directory
    ├── LocalValetDriver.php // I added this to get my multi site to work - it only works if I navigate to https://src.test (need to change to url in links below)
    ├── app
    ├── bin
    ├── composer.json
    ├── composer.lock
    ├── index.php
    ├── lib
    ├── phpserver
    ├── pub
    ├── setup
    ├── var
    └── vendor
...
```
My project is a multi site (4 different domains, each configured in Nginx mapps) which means, I don't use subfolders, all the domains just go to the same codebase

I have done 
```
valet park ..
valet link ..
```

My config.json looks like this
```
{
    "domain": "test",
    "paths": [
        "/Users/UserName/.valet/Sites",
        "/Users/UserName/Projects/project_name/magento2"
    ],
    "redistool": {
        "enabled": true
    },
    "mailhog": {
        "enabled": true
    }
}
```
Valet links, gives me the following info
```
+-----------------------+-----+------------------------------+------------------------------------------------------+
| Site                  | SSL | URL                          | Path                                                 |
+-----------------------+-----+------------------------------+------------------------------------------------------+
| www.domain1.test      |     | http://www.domain1.test      | /Users/UserName/Projects/project_name/magento2/src   |
| www.domain2.test      |     | http://www.domain2.test      | /Users/UserName/Projects/project_name/magento2/src   |
| www.domain3.test      |     | http://www.domain3.test      | /Users/UserName/Projects/project_name/magento2/src   |
| www.domain4.test      |     | http://www.domain4.test      | /Users/UserName/Projects/project_name/magento2/src   |
+-----------------------+-----+------------------------------+------------------------------------------------------+
```
I have also secured those sites, however, that does not show an X under SSL (I am not sure why, because the certs are generated and added to the nginx config)

When I visit https://www.domain1.test I just get the default 404 page, showing all my sub folders
When I visit the src.test folder (my code is in a sub folder of the project directory called src)
I get redirected back to https://www.domain1.test showing me the 404
I created a LocalValetDriver.php but it's not working 100% in the sense that I can only see it firing when I visit the src.test url

I am basically unable to view my site - do you know why this is so?

Looking forward to trying out Valet+ and thank you for putting together such a great project

**Comment by samgranger** [comment]
Please try creating a .env.valet file with the following contents in the root of the main project, this should solve your issue:

```
<?php

return [
    'domain1' => [
        'MAGE_RUN_CODE' => 'store_view_code_1',
        'MAGE_RUN_TYPE' => 'store',
    ],
    'domain2' => [
        'MAGE_RUN_CODE' => 'store_view_code_2',
        'MAGE_RUN_TYPE' => 'store',
    ],
];
```

Also feel free to join our Slack channel for any further assistance!
