### ISSUE TITLE
Problem with connecting to db

### ISSUE THREAD

**Issue by beany-vu** [weprovide/valet-plus#36]
I tried to setup the valet web server and it's okay because and I can try like "example.dev". However, I can't connect to the db or do anything relating the db.
This is the screenshot of my error: [link](http://prntscr.com/g75req)
Any ideas about this problem?
Thanks in adance.

**Comment by DigicreateJens** [comment]
I encountered this error earlier today when testing for my own issue (#37).
After testing if the error I mentioned still occurs when reinstalling with the `--with-mariadb` flag, the `valet db ls` command started working for some reason.

**Comment by timneutkens** [comment]
Lets track this in #37 since it's the same issue.
