### ISSUE TITLE
MySQL breaks when exporting

### ISSUE THREAD

**Issue by DigicreateJens** [weprovide/valet-plus#37]
I'm trying to export a Magento2 DB via SequelPro, but the export always stops around table number 32-35 because the MySQL server just stops working. After running a `valet restart` the server is back online, but restarting the export breaks it again.

This is rather a pressing issue, because I use MySQL exports frequently via SequelPro

**Comment by DigicreateJens** [comment]
Tried reinstalling with `--with-mariadb` option, no difference. Not even sure if it actually installs MariaDB, as SequelPro shows my database as 'MySQL 5.7.17'

**Comment by timneutkens** [comment]
@DigicreateJens it actually doesn't install mariadb yet. Weird question, but could you try a system restart. It'll load some config changes which we can't manually load on first install 👍

**Comment by DigicreateJens** [comment]
Yep, restart seems to fix the issue. Issue #36 was fixed before the reboot though. 👍

**Comment by timneutkens** [comment]
@DigicreateJens okay so we have to think of something to load https://github.com/weprovide/valet-plus/blob/master/cli/stubs/limit.maxfiles.plist without restarting 👍

**Comment by timneutkens** [comment]
Fixed in 1.0.1
