### ISSUE TITLE
libyaml must be a dependency

### ISSUE THREAD

**Issue by elaman** [weprovide/valet-plus#370]
macOS latest Mojave, PHP 7.1 installation is failing if I don't manually install **libyaml**. Here is the output:

> ➜  ~ valet install --with-mariadb
> [php] Checking for errors within the php installation...
> [nginx] Stopping
> [valet-php@7.1] Stopping
> [mysql@5.7] Stopping
> [devtools] Installing tools
> [devtools] wp-cli already installed
> [devtools] pv already installed
> [devtools] geoip already installed
> [binaries] Installing binaries
> [BREW TAP] henkrehorst/php already installed
> [PECL] Updating PECL channel: pecl.php.net
> [PECL] Installing extensions
> 	apcu_bc is already installed, skipping...
> 	apcu_bc successfully enabled
> 	geoip is already installed, skipping...
> 	geoip successfully enabled
> 
> In Pecl.php line 147:
>                                                                                
>   Could not find installation path for: yaml                                   
>                                                                                
>   downloading yaml-2.0.4.tgz ...                                               
>   Starting to download yaml-2.0.4.tgz (39,071 bytes)                           
>   ..........done: 39,071 bytes                                                 
>   8 source files, building                                                     
>   running: phpize                                                              
>   Configuring for:                                                             
>   PHP Api Version:         20160303                                            
>   Zend Module Api No:      20160303                                            
>   Zend Extension Api No:   320160303                                           
>   Please provide the prefix of libyaml installation [autodetect] : building i  
>   n /private/tmp/pear/temp/pear-build-dodoYja2Mc/yaml-2.0.4                  
>   running: /private/tmp/pear/temp/yaml/configure --with-php-config=/usr/local  
>   /opt/valet-php@7.1/bin/php-config --with-yaml                                
>   checking for grep that handles long lines and -e... /usr/bin/grep            
>   checking for egrep... /usr/bin/grep -E                                       
>   checking for a sed that does not truncate output... /usr/bin/sed             
>   checking for cc... cc                                                        
>   checking whether the C compiler works... yes                                 
>   checking for C compiler default output file name... a.out                    
>   checking for suffix of executables...                                        
>   checking whether we are cross compiling... no                                
>   checking for suffix of object files... o                                     
>   checking whether we are using the GNU C compiler... yes                      
>   checking whether cc accepts -g... yes                                        
>   checking for cc option to accept ISO C89... none needed                      
>   checking how to run the C preprocessor... cc -E                              
>   checking for icc... no                                                       
>   checking for suncc... no                                                     
>   checking whether cc understands -c and -o together... yes                    
>   checking for system library directory... lib                                 
>   checking if compiler supports -R... no                                       
>   checking if compiler supports -Wl,-rpath,... yes                             
>   checking build system type... x86_64-apple-darwin18.6.0                      
>   checking host system type... x86_64-apple-darwin18.6.0                       
>   checking target system type... x86_64-apple-darwin18.6.0                     
>   checking for PHP prefix... /usr/local/Cellar/valet-php@7.1/7.1.26            
>   checking for PHP includes... -I/usr/local/Cellar/valet-php@7.1/7.1.26/inclu  
>   de/php -I/usr/local/Cellar/valet-php@7.1/7.1.26/include/php/main -I/usr/loc  
>   al/Cellar/valet-php@7.1/7.1.26/include/php/TSRM -I/usr/local/Cellar/valet-p  
>   hp@7.1/7.1.26/include/php/Zend -I/usr/local/Cellar/valet-php@7.1/7.1.26/inc  
>   lude/php/ext -I/usr/local/Cellar/valet-php@7.1/7.1.26/include/php/ext/date/  
>   lib                                                                          
>   checking for PHP extension directory... /usr/local/Cellar/valet-php@7.1/7.1  
>   .26/pecl/20160303                                                            
>   checking for PHP installed headers prefix... /usr/local/Cellar/valet-php@7.  
>   1/7.1.26/include/php                                                         
>   checking if debug is enabled... no                                           
>   checking if zts is enabled... no                                             
>   checking for re2c... no                                                      
>   configure: WARNING: You will need re2c 0.13.4 or later if you want to regen  
>   erate PHP parsers.                                                           
>   checking for gawk... no                                                      
>   checking for nawk... no                                                      
>   checking for awk... awk                                                      
>   checking if awk is broken... no                                              
>   checking whether to enable LibYAML suppot... yes, shared                     
>   checking for yaml headers... not found                                       
>   configure: error: Please install libyaml                                     
>   ERROR: `/private/tmp/pear/temp/yaml/configure --with-php-config=/usr/local/  
>   opt/valet-php@7.1/bin/php-config --with-yaml' failed                         
>                                                                                
> 
> install [--with-mariadb]

**Comment by mischabraam** [comment]
True, this must be a dependency built in Valet+. Workaround is to install it yourself.
`brew install libyaml`

**Comment by Neodork** [comment]
@mischabraam Brew tap has added the libyaml to all PHP versions:

https://github.com/henkrehorst/homebrew-php/commit/442ec4d03942cd25255fe60edb6dfa11db4e6c73

Please confirm if this solves the problem.

**Comment by mischabraam** [comment]
@Neodork I see you added the libyaml only at 7.1 +, not 7.0 and lower correct?

**Comment by elaman** [comment]
@Neodork yes, the issue is gone now. Thank you!

@mischabraam it would seem, that 5.6 and 7.0 already had libyaml as a dependency.

**Comment by mischabraam** [comment]
Resolved in PR #390
