### ISSUE TITLE
Invalid datetime zone?

### ISSUE THREAD

**Issue by CrixuAMG** [weprovide/valet-plus#38]
When I cloned my project in `~/sites/project-name`, I saw many warnings related to the timezone.
Europe/Amsterdam is perfect, as I am from the Netherlands, but it appears to be set incorrectly?
I've tried setting it in my own script, (not even using DateTime btw, only using Nesbot's Carbon package) but that still shows the errors.
After scrolling down a bit, I can also see an exception is thrown. These errors and exception are even showing up if I do the following on the first line of my script: `phpinfo();die;`.
Here is a (full) screenshot of my phpinfo: [link](http://imgur.com/a/70QrO)

**Comment by CrixuAMG** [comment]
I've placed `ini_set('date.timezone', 'Europe/Amsterdam');` in my bootstrapper, but why would this be required of any project? Please setup a default timezone in the ini so that exceptions aren't thrown whenever trying to use a DateTime class instance :)

**Comment by timneutkens** [comment]
Interesting! I'll have a look 🙌🏻

**Comment by timneutkens** [comment]
> I've placed ini_set('date.timezone', 'Europe/Amsterdam'); in my bootstrapper, but why would this be required of any project? Please setup a default timezone in the ini so that exceptions aren't thrown whenever trying to use a DateTime class instance :)

This was already done, please check `/usr/local/etc/php/7.0/conf.d/z-performance.ini` line 2 should have the timezone. Note that you'll have to change `7.0` with your installed PHP version 🙌

**Comment by CrixuAMG** [comment]
Maybe make a command `valet php [number]`, where [number] would be 70, 71 etc, so people can easily upgrade their php version? ;)

**Comment by timneutkens** [comment]
We already have `valet use [5.6,7.0,7.1]` https://github.com/weprovide/valet-plus#switching-php-version

**Comment by joshredwards** [comment]
Aware of this being closed, however I'd like to point out that when you call one of those commands as you've mentioned @timneutkens.. You essentially do a blanket shut-down of php. I suggest not doing that and terminating the specific service - It'll improve speed.
