### ISSUE TITLE
n98-magerun - homebrew/php was deprecated

### ISSUE THREAD

**Issue by rodrigoobiassi** [weprovide/valet-plus#382]
Issues:

[n98-magerun] Installing
Error: homebrew/php was deprecated. This tap is now empty as all its formulae were migrated.

Brew was unable to install [n98-magerun]

Unable to determine linked PHP.

Image:
<img width="583" alt="Screen Shot 2019-07-09 at 23 23 08" src="https://user-images.githubusercontent.com/14968349/60935552-9cc2f400-a2a0-11e9-9ed5-54f8c320a9c8.png">

I've researched many similar issues, but no one has come up with a solution yet. Can someone help me?

**Comment by rafaelstz** [comment]
Try to run these commands below:

```
valet fix && \
brew link --force valet-php@7.1
```

**Comment by rodrigoobiassi** [comment]
Message: "Command "fix" is not defined"

<img width="303" alt="Screen Shot 2019-07-11 at 21 30 51" src="https://user-images.githubusercontent.com/14968349/61093960-3b775e00-a423-11e9-9ef0-12d0d6c46961.png">

**Comment by rodrigoobiassi** [comment]
I managed to fix it like this:

**cd ~/.composer/
rm -rf cache/ vendor/ composer.lock
brew install valet-php@7.1
brew link --force valet-php@7.1
brew install mysql@5.7
brew link mysql@5.7 --force
valet fix && valet install**

There were some problems, I checked all the php.ini file of each version:
/usr/local/etc/valet-php/5.6/php.ini
/usr/local/etc/valet-php/7.0/php.ini
/usr/local/etc/valet-php/7.1/php.ini
/usr/local/etc/valet-php/7.2/php.ini
/usr/local/etc/valet-php/7.3/php.ini

I removed all the extensions that were on the first lines, adds by valet

Then, I ran again:
**valet install**

It worked for me! I hope it helps someone!

**Comment by Neodork** [comment]
Great that you have your issue resolved! 

Seemed like you were running an old valet-plus installation or valet installation which was within your composer.lock file. If you're encountering issues with the .ini generation you could create a new ticket for it.
