### ISSUE TITLE
Add ability to enable/disable SOAP module

### ISSUE THREAD

**Issue by diazwatson** [weprovide/valet-plus#384]
I was wondering how difficult would it be to add ability to enable or disable PHP-SOAP.

Does anyone know how could we do that thing?

**Comment by Neodork** [comment]
Hey there! What PHP soap module? The extension?

From what I can gather the PHP-SOAP extension needs to be build with PHP:
https://www.php.net/manual/en/soap.installation.php

Meaning that it will bit a lot more difficult than just adding a PECL module.

**Comment by diazwatson** [comment]
Yeap, what if we update the formulae in https://github.com/henkrehorst/homebrew-php?

**Comment by Neodork** [comment]
@diazwatson That would be the way to go. Could you open a ticket in the brewtap repo?

**Comment by diazwatson** [comment]
Sure, I'll do it now

**Comment by diazwatson** [comment]
https://github.com/henkrehorst/homebrew-php/issues/11

**Comment by Neodork** [comment]
We will continue the discussion in the brew tap ticket.
