### ISSUE TITLE
Error installing ElasticSearch

### ISSUE THREAD

**Issue by diazwatson** [weprovide/valet-plus#389]
## Description
Error installing ElasticSearch using `valet elasticsearch on`

## Preconditions
- valet use php 7.1

## Expected
ElasticSearch is installed and enabled

## Actual

```bash
$ valet elasticsearch on
[elasticsearch@2.4] Installing
elasticsearch@2.4: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: An unsatisfied requirement failed this build.


In Brew.php line 107:

  Brew was unable to install [elasticsearch@2.4].


elasticsearch [<mode>]
```

**Comment by mischabraam** [comment]
True, ElasticSearch needs Java. Currently not installed through Valet+ as dependency yet. Like the error says you can install it manually with 
`brew cask install homebrew/cask-versions/adoptopenjdk8`

**Comment by diazwatson** [comment]
but I do have Java installed:

```
java --version
java 12.0.2 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
```

**Comment by diazwatson** [comment]
The command @mischabraam mentioned fixed my issue
