### ISSUE TITLE
Cannot connect to any site

### ISSUE THREAD

**Issue by FlorianMoser** [weprovide/valet-plus#391]
Just installed Valet Plus and got all green ouput. But now I can't reach any site (ERR_CONNECTION_REFUSED).

I verified in ~/.valet/config.json that the correct path ist parked. I also tried `valet domain test`, but nothing changed. Pinging *.test works and there is also no connection when opening 127.0.0.1, so I suppose it's no DNS problem.

Any help would be very appreciated.

**Comment by Serializator** [comment]
What output do you get when you run `sudo nginx -t`?

**Comment by FlorianMoser** [comment]
Thanks a lot, @Serializator, you made my day!

`sudo nginx -t`revealed a missing .conf file for Elasticsearch. Creating an empty file fixed the problem.

**Comment by Serializator** [comment]
Glad that I could help!

What you might want to do is use the stub from Valet+ that should've been copied to `/usr/local/etc/nginx/valet/elasticsearch.conf` on install. You can find the stub under `~/.composer/vendor/weprovide/valet-plus/cli/stubs/elasticsearch.conf`, do not forget to replace `VALET_DOMAIN` with `.test` (or the domain you've configured if you did). This way you won't run into troubles later if you need Elasticsearch for example.

I'll create a follow-up ticket referencing this one for further bugfixing! 😉

**Comment by FlorianMoser** [comment]
Thanks, will do.

To be honest it took me 5h to get Valet Plus working. Countless wiping and re-installing. I had to fix so many issues manually (missing PHP files, wrong PHP versions, missing PHP extensions, acpu problems, MySQL not working). Glad you're opening a ticket for the Elassticsearch issue.

But I'm very happy now, how Valet Plus is running :-)

**Comment by joomkit** [comment]
This is till an issue July 2020 fresh install

**Comment by joshuadegier** [comment]
It appears to be still an issue on Oct 2020 fresh install, I ran into it after trying a full re-install of Valet+.

**Comment by XaRz** [comment]
Issue still appears in a valet+ fresh install through homebrew. Not a quick fix?

**Comment by joomkit** [comment]
XaRz has elastic search fix not worked?

**Comment by kaiserkiwi** [comment]
Just tried to switch vom Valet to Valet+. Sadly the issue still seems to exist. It's good to know, that the problem seems to be fixable, but how should I explain to my team the switch, when the original is just two lines of terminal work and this is such a hassle to install? I'm a bit disappointed that the problem was reported one and a half year ago and it still exists…

**Comment by SanderAtom** [comment]
@kaiserkiwi I understand your point of view but remember this is an open-source framework maintained by a few people that have full time jobs beside this, and mostly by the community members around the project spending their free time. Also did you [uninstall Valet](https://github.com/weprovide/valet-plus/wiki/Installation#laravel-valet-to-valet) before installing Valet+?

For anyone still experiencing this can you provide more information about the situation, like:
- Which macOS version are you running?
- Was any other local development framework (Valet or other) installed before installing Valet+?
- Was Valet+ installed before trying to re-install? If so, what steps were taken to clear all Valet+ related config?
- Any other errors or notifications during install besides the missing `elasticsearch.conf`?
