### ISSUE TITLE
Bug: switching versions leads to multiple php versions running and apcu_fetch() errors

### ISSUE THREAD

**Issue by joomkit** [weprovide/valet-plus#405]
- [ ] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Switch php versions leads to brew starting two valet php services

**What was supposed to happen?**
Only one version was supposed to run

**What actually happened?**
fetch_apcu errors on all sites 

**How to reproduce this?**
A step by step guide on how to reproduce this issue.
Switch php versions. Check brew services list against CLI php -i

**What is the solution?**
Dunno

**Sources**

**Comment by Neodork** [comment]
Do you have any lingering PHP-FPM instances running? Are you sure the PHP-FPM the server is using is the valet-php one? 

`ps aux | grep php-fpm`

**Comment by Neodork** [comment]
Hey we've resolved this behaviour in valet-plus `2.x`. I would like to get your feedback after checking out the development branch (`2.x-dev`). Please let me know if it resolves your issue.

**Comment by r-martins** [comment]
It seems you need to re-export the variables to the current php version and re-run `valet install`.
```
export PATH="/usr/local/opt/valet-php@5.6/bin:$PATH"
export PATH="/usr/local/opt/valet-php@5.6/sbin:$PATH"
```
where 5.6 is my current php version...

I was just wondering how to get the current valet php version, so we can modify this export PATH to use the correct value. So we would just need to start a new terminal session in order to make valet work properly in those cases.

**Comment by Neodork** [comment]
Yeah never add those exports in your PATH. We're removing the suggestion from the output. Thanks for the feedback.
