### ISSUE TITLE
valet uninstall should uninstall valet-php versions

### ISSUE THREAD

**Issue by Leland** [weprovide/valet-plus#406]
- [x] I've checked the issue queue and could not find anything similar to my feature.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`

**Why implement this feature?**  
Because valet-php is not used out of valet plus

**What will be required for this feature?**  
When running `valet uninstall`, each of the Homebrew-installed `valet-php` versions would be uninstalled.

**Comment by Neodork** [comment]
Agreed this has been one of the things on my list. Tagging as `2.x` Minor ticket.

**Comment by mischabraam** [comment]
Covered in 3.x-dev
