### ISSUE TITLE
Bug: ElasticSearch data path collision

### ISSUE THREAD

**Issue by mischabraam** [weprovide/valet-plus#407]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `master` branch :D
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
The problem is the installation sequence of ElasticSearch and the sharing of the datapath between the versions of ElasticSearch. The way ES indexes the data differs between versions, which means that (for instance) ES6.8 can't read data from ES2.4 or ES5.6.
The datapath is configured in `elasticsearch.yml`. Valet+ alters this config file and uses the version of the used ES version as suffix for the datapath. So, if you switch to ES2.4 the datapath will be `..../elasticsearch@2.4`.

The actual problem occurs for people that already have 2.4 or 5.6 installed using an older version of Valet+ in combination of switching to ES6.8. ES6.8 is currently the main version offered by Brew. So, `brew install elasticsearch` will install ES6.8. This is also used by Valet+ when switching to ES6.8. For this version there is no suffix `@6.8`, result is a datapath also without suffix.

So, if you have ES2.4 installed in older version of Valet+ the datapath is `.../elasticsearch` (default before switch feature). When switching to ES6.8 by using `valet use es 6.8`, the new datapath is also `.../elasticsearch`. This collides with the already indexed data in 2.4, 6.8 can't read it.

**What was supposed to happen?**
Installation of ES6.8 should be indeed without suffix (currently correct). However, switching to ES6.8 should use the `@6.8` suffix for the datapath config to prevent collisions with older installations.

**What actually happened?**
A description of what actually happened.

**How to reproduce this?**
- Remove all versions of ElasticSearch with `brew remove elasticsearch elasticsearch@2.4 elasticsearch@5.6`
- Remove all indexed data and config with `rm -rf /usr/local/var/elasticsearch*` and `rm -rf /usr/local/etc/elasticsearch`
- Manually install ES2.4 with `brew install elasticsearch@2.4`
- Switch to ES6.8 with `valet use es 6.8`

**What is the solution?**
Always use version as `@<version>` as suffix in the datapath.

**Comment by mischabraam** [comment]
As a temp work around. You can follow steps below.

- Remove all versions of ElasticSearch with brew remove elasticsearch elasticsearch@2.4 elasticsearch@5.6
- Remove all indexed data and config with rm -rf /usr/local/var/elasticsearch* and rm -rf /usr/local/etc/elasticsearch
- Install ES6.8 with `valet use es 6.8` first
- Install desired other version with `valet use es 2.4`

**Comment by Neodork** [comment]
@mischabraam Closing as PR is merged!

**Comment by amarroni** [comment]
Hi guys how are you?,
Problem still happening on valet+ 2.0. I try to follow @mischabraam but elasticsearch still pointing to 2.4.
How can I solve this issue?
Thanks.
