### ISSUE TITLE
FastCGI buffer directives for nginx

### ISSUE THREAD

**Issue by Neodork** [weprovide/valet-plus#410]
- [X] I've checked the issue queue and could not find anything similar to my feature.
- [X] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`

**Why implement this feature?**  
Some applications require certain factcgi buffer sizes. If not set the applications in question could throw a 502 Bad Gateway error. I would like to open a discussion with the community to decide what the best course of action would be here.

**What will be required for this feature?**  
Decide what buffer size would be best to apply. E.G: In which cases do we get 502 Bad gateways. And/or allow users to set buffer sizes through a command.
 
**Directives:**
`fastcgi_buffer_size`
`fastcgi_buffers`

**In files:**
`cli/stubs/nginx.conf`
`cli/stubs/secure.nginx.conf`

**Sources**
http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_buffers
http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_buffer_size

**Comment by SanderAtom** [comment]
What could be the downside(s) of setting these values a lot higher?

**Comment by Neodork** [comment]
Good question I am not unsure what the downsides could be if set too high. We should research that and update the ticket.

**Comment by SanderAtom** [comment]
I just ran into this issue again after updating valet+ and did some testing. I only need to add these values to the top of `/usr/local/etc/nginx/valet/valet.conf`:
```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
server {
  ...
```
This fixes the 502 Bad Gateway response with the `upstream sent too big header while reading response header from upstream` error in `~/.valet/Log/nginx-error.log`.
The values are from examples like [here](https://timonweb.com/devops/fixing-upstream-sent-too-big-header-while-reading-response-header-from-upstream-error-in-laravel-valet-nginx/) and [here](https://janostlund.com/2019-06-20/502-bad-gateway-laravel-valet).
I've seen examples like [here](https://github.com/laravel/valet/issues/290#issuecomment-398686133) where these values are very high but with just 16/16k and 32k it fixes the problem for Drupal. Also according to [this answer](https://stackoverflow.com/a/57548517/1902185) it's not recommended to set these values too high:
```
Either way, don't set those buffers too high and use calculations specific to your app. Arbitrarily high values won't do good to your RAM, because those buffers are used per connection.
```
There could still be processes or systems (like maybe Magento 2?) that need more buffer/size, but this might be a good average bump to at least prevent a lot of 502 errors.

**Comment by maurisource** [comment]
@SanderAtom Do you know if there is a way to add these configurations don't get overwritten on next update?

**Comment by SanderAtom** [comment]
You can test if you can add your own file to `~/.valet/Nginx/` with those settings. That file is loaded before Valet+'s config but it's not overwritten after so should work.
But I think we can change the last few lines in `/usr/local/etc/nginx/nginx.conf` to read: `include valet/*;`. This way you could add your own `valet/z-local.conf` or similar to load after `valet/valet.conf` for any overwrites.

**Comment by mischabraam** [comment]
Looks like this config change is already affective since version [2.2.0](https://github.com/weprovide/valet-plus/releases/tag/2.2.0)
