### ISSUE TITLE
Xdebugger does not work on magento 2.3.2 projects

### ISSUE THREAD

**Issue by umarch06** [weprovide/valet-plus#415]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I'm on latest version of valet+ i.e 1.0.29, the xdebugger is not working on magento 2.3.2, I've used both php 7.2 and 7.1 versions.

**What was supposed to happen?**
The xdebugger shipped from valet+ would have worked with magento 2.3.2 smoothly.

**What actually happened?**
I have multiple instances of magento 2.2.x, 2.3.1 and 2.3.2. I have tried debugging magento 2.2.x on php 7.1 and all is good, I have tried debugging magento 2.3.1 on php 7.2 and everything is good, even magento 2.2.x projects work smoothly on both php 7.1 and 7.2, but when i use magento 2.3.2 projects on either php 7.1 and 7.2, xdebugger doesn't work. So I'm guessing something is probably wrong with latest valet+ xdebugger with magento 2.3.2 debugging.

**How to reproduce this?**
just install a fresh instance of magento 2 from https://magento.com/tech-resources/download. after deploying project, put breakpoint in pub/index.php or index.php on root, the breakpoint will not be hit.

**What is the solution?**
I don't know the solution, probably need to do something in Valet Magento driver.

**Sources**
The bug is not related to php extension as disabling the debugger will let you server website so i don't think that's the issue, please consider checking it.

**Comment by Neodork** [comment]
@samgranger @mischabraam You guys experiencing this? I don't run Magento so I cannot check it.

**Comment by MaxSouza** [comment]
Have the same issue.

**Comment by umarch06** [comment]
I ended up reinstalling MAC OS High Sierra for using valet-plus xdebug. I guess they haven't made valet-plus 2.3.2 compatible with Mojave yet.

**Comment by Tjitse-E** [comment]
@umarch06 i've also checked this, and Magento 2.3.2 + PHP 7.2 (i'm using `valet-php@7.2`) works with Xdebug in my case. Using Mojave 10.14.6.

**Comment by MaxSouza** [comment]
Hi,

In my case, there was a problem with port, so I changed for 9002 and it's  works

**Comment by mischabraam** [comment]
I don't have this problem. Can use xdebug fine with Magento 2.3.2 or any other version or framework. Don't think this is related to Valet+.
What can happen is a false server path mapping. In Magento by default, there is a vendor file named `server.php` which conflicts with the `server.php` file from Valet+.
If you set up your project to **not** use path mappings, the conflict is resolved and you can debug.

**Comment by Neodork** [comment]
Closing due to no answer.
