### ISSUE TITLE
Bug: Unable to get past Call to undefined function apcu_fetch()

### ISSUE THREAD

**Issue by ianrobertdouglas** [weprovide/valet-plus#416]
- [ X ] I've checked the issue queue. No solutions from similar issues worked.
- [ X ] I'm on the latest version of valet-plus (`valet --version`): `<1.0.29>`
- [ X ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Ping works, browser fails

**What was supposed to happen?**
 I should see my site

**What actually happened?**
 I see this: 
`Fatal error: Uncaught Error: Call to undefined function apcu_fetch() in /Users/Decline/.composer/vendor/weprovide/valet-plus/server.php:51 Stack trace: #0 {main} thrown in /Users/Decline/.composer/vendor/weprovide/valet-plus/server.php on line 51`

**How to reproduce this?**
No idea. I followed the install instructions to the letter.

**What is the solution?**
No clue.

_______________________________________________________
**Explanation**

I've been trying to get Valet Plus up and running for about 10hrs. 

I followed the install instructions precisely.

I have read through at least 30 previous issues, in search of answers for whatever I was facing. I seem stuck in a cycle of errors, though a number have been resolved. 

What I cannot resolve is that my site - which I can ping just fine - spits out the following:

`Fatal error: Uncaught Error: Call to undefined function apcu_fetch() in /Users/Decline/.composer/vendor/weprovide/valet-plus/server.php:51 Stack trace: #0 {main} thrown in /Users/Decline/.composer/vendor/weprovide/valet-plus/server.php on line 51`

Valet+ 1.0.29
OSX 10.14.6

**Brew services list:**
```
dnsmasq       started root    /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
mailhog       started root    /Library/LaunchDaemons/homebrew.mxcl.mailhog.plist
mysql         started root    /Library/LaunchDaemons/homebrew.mxcl.mysql.plist
mysql@5.7     started Decline /Users/Decline/Library/LaunchAgents/homebrew.mxcl.mysql@5.7.plist
nginx         started root    /Library/LaunchDaemons/homebrew.mxcl.nginx.plist
php@7.1       started root    /Library/LaunchDaemons/homebrew.mxcl.php@7.1.plist
redis         started Decline /Users/Decline/Library/LaunchAgents/homebrew.mxcl.redis.plist
tor           started root    /Library/LaunchDaemons/homebrew.mxcl.tor.plist
valet-php@7.1 started root    /Library/LaunchDaemons/homebrew.mxcl.valet-php@7.1.plist
valet-php@7.2 started Decline /Users/Decline/Library/LaunchAgents/homebrew.mxcl.valet-php@7.2.plist
```

I have tried `valet fix` and `valet install` scores of times.

I have checked the php.ini file and I don't have duplicates of `extension="apcu.so"`

I checked my .zshrc file and removed some lines that were appended at the bottom. Made no difference: the current error was already present and didn't go away.

I've restarted my machine multiple times.

I've checked the php version. From what I have read around, 7.1 seems the one that works for most, and install was defaulting to it, so I downgraded my pre-existing 7.2 to match that.

```
php -v
PHP 7.1.32 (cli) (built: Sep  9 2019 14:07:03) ( NTS )
```

```
which php
/usr/local/bin/php
```

I'm at a loss at what to do now.

In case it's relevant, I get the following in red when I run `valet install`:

```
[nginx] Restarting
Setting password for root user failed.
```

I was planning on trying to deal with that once I can reach a site.

I checked the valet paths. My server directory is there, so that's all fine.

______________

As an afterthought, I see that the 2.x dev branch seems to address issues with apcu. If anyone has a clue how to move my current setup to version 2.x, I'd love to know how.

**Comment by ianrobertdouglas** [comment]
I don't know if it was this resolved the issue, but I removed the Homebrew versions of php, with:
```
brew remove php@7.1
brew remove php@7.2
```
My sites now resolve.
Still interested if anyone knows how to move to the 2.x dev branch, via command line if possible.

**Comment by ianrobertdouglas** [comment]
I passed two days trying to resolve any number of errors: I seemed to go in a loop from the error in my original post to still others, and sometimes back again.

Honestly, I’m not entirely sure how I resolved it, and the following is not everything I tried, because I tried a thousand things, but in case it helps anyone, I did more or less the following in the end: 

1) I read through this guide: https://manuals.gravitydept.com/develop/environment-setup/valet-plus It included instructions on what to do if you face the `Setting password for root user failed` error. In short, wipe mysql from your machine entirely. Like, everywhere. Remove valet plus entirely and start over. “If Homebrew somehow installs/updates to MySQL 8 — that breaks Valet+, which requires MySQL 5.7. You’ll waste hours trying to reinstall Valet+ or MySQL but nothing will work. You have to scorch any trace of MySQL ever existing on your computer, restart, then destroy and reinstall Valet+ so it can install the MySQL version it requires. ” I followed this gist to help with that process: https://gist.github.com/vitorbritto/0555879fe4414d18569d and this one to help remove valet plus: https://gist.github.com/dannygsmith/5b74ba708d7bf8621c1cb6b959ece99f/ 

2) The total removal and start over thing didn’t entirely go smoothly, but I think the difference this time is that I added nothing manually to my PATH. 

3) Somehow I arrived to a different error `ERR_CONNECTION_REFUSED` in my web browser. This thread helped resolve that by copying and amending a elasticsearch.conf file that should have been copied on install: https://github.com/weprovide/valet-plus/issues/391 

4) Meanwhile, mysql wasn’t any longer throwing the error `'Can't connect to local MySQL server through socket '/tmp/mysql.sock' but rather ERROR 1045 (28000): Access denied for user 'Decline'@'localhost' (using password: NO).` Progress. I ran `sudo mysqladmin -u root --password='' password root` and then `valet install` again, still got the error `Setting password for root user failed.` But when I checked again with the command `mysql` it worked. Same with `valet db ls`. 

I’ll explore next if I can create and import databases, and I really hope it all holds up.

**Comment by ianrobertdouglas** [comment]
I should add that I moved over to 2.x-dev with this command:
`composer global require weprovide/valet-plus "2.x-dev"`

**Comment by Neodork** [comment]
@ianrobertdouglas PM me on the slack channel and we'll go over your issues one by one.

**Comment by ianrobertdouglas** [comment]
Thank you!
