### ISSUE TITLE
Feature: Allow secure websites to use own certificate

### ISSUE THREAD

**Issue by dverkade** [weprovide/valet-plus#419]
- [X] I've checked the issue queue and could not find anything similar to my feature.
- [X] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`

**Why implement this feature?**  
Magento PWA Studio does not allow self signed certificates for development. Currently when you secure a site with Valet Plus it creates a self signed certificate. 

**What will be required for this feature?**  

- Create the ability to add a general certificate in the certificates directory. For instance a certificate for a specific domain or a wildcard certificate. 
- When a wildcard certificate is present configure nginx to use the wildcard certificate when securing a site instead of creating a self signed certificate.

**Comment by Neodork** [comment]
This would be possible if we track certificates per link / park and simply serve that instead. The work required to do this is quite some though.

Tagged as `2.x minor` ticket

**Comment by sheshagiricorra** [comment]
Do we have any updates on this?
