### ISSUE TITLE
Add Imagemagick to valet-php

### ISSUE THREAD

**Issue by Leland** [weprovide/valet-plus#420]
- [x] I've checked the issue queue and could not find anything similar to my feature.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 1.0.29`

**Why implement this feature?**  
Imagemagick isn't a part of valet-php, but is used by various parts of Magento - eg catalog:image:resize

**Comment by Neodork** [comment]
@Leland I was under the impression that extension was deprecated. Or am I wrong?

**Comment by samsycamore** [comment]
@Neodork 
When I try to install imagemagick via pecl as valet-php@7.2 I get this

`No releases available for package "pecl.php.net/imagemagick"
install failed`

Do you have any insight?

**Comment by mischabraam** [comment]
Ran into the same issue of a project depending on imagick with Magento 2.3.3, tried to install imagick using installation suggestions from https://ma.ttias.be/install-phps-imagick-extension-on-mac-with-brew/ but failed doing so (in fact it totally screwed up my installation).

**Comment by royduin** [comment]
- `brew install imagemagick`
- `pecl install imagick`
Worked for me.

**Comment by samsycamore** [comment]
@royduin Do you know which version of PHP your valet sites are using? Is it valet-php?

**Comment by royduin** [comment]
```
$ which php
/usr/local/opt/valet-php@7.4/bin/php
$ which pecl
/usr/local/opt/valet-php@7.4/bin/pecl
```

**Comment by mischabraam** [comment]
Added to 3.x-dev
