### ISSUE TITLE
Install: Package container-interop/container-interop is abandoned

### ISSUE THREAD

**Issue by GeoJunkie** [weprovide/valet-plus#424]
On a clean installation, during the `composer global require weprovide/valet-plus`, I get the following warning:

`Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.`

I checked the usage and found this is related to the `mnapoli/silly` package:

```
➜  ~ composer global  why container-interop/container-interop
Changed current directory to /Users/***/.composer
mnapoli/silly   1.5.1  requires  container-interop/container-interop (~1.0)
php-di/invoker  1.3.3  requires  container-interop/container-interop (~1.1)
```

`mnapoli/silly` moved to `psr/container` in [Version 1.6.0](https://github.com/mnapoli/silly/releases/tag/1.6.0). Should Valet+ move to the newest version?

**Comment by Neodork** [comment]
@GeoJunkie Good catch. We'll have to upgrade `mnapoli/silly` but check if the package has made non-BC changes. Since that's the core valet+ is running on. We could also have a check with `laravel/valet` to see what they did.

**Comment by majstomphorst** [comment]
Today i tried to install and configure `valet plus` but i hit bug after bug. 
and this was the first one. Can this block the utility form completely working?

i've tried everything to get is working but no luck. `valet fix` gives a lot of errors. 

I hope that you guy can fix this

**Comment by Mezzle** [comment]
@majstomphorst This is a warning, not an error. 

I'd open your own issue, and paste the full output somewhere for someone to read to be able to find out what your issue is, or do the same in the slack.

**Comment by GeoJunkie** [comment]
@Neodork I actually posted this over on `laravel/valet` because with my limited understanding of `composer.json` I didn't catch the differences between the two files.

valet plus: `"mnapoli/silly": "~1.5.0",`
laravel/valet: `"mnapoli/silly": "~1.0",`

As they pointed out in my [misguided issue there](https://github.com/laravel/valet/issues/860), their parameter "means it'll use anything 1.x.x ... which right now means it's using the latest version."

So if the `valet-plus` `composer.json` was updated to replace `~1.5.0` with `~1.0` that SHOULD fix everything, right?

**Comment by BrunoAHVincent** [comment]
I got this error also, is it safe to simply  ignore it, or what should I do about this?
