### ISSUE TITLE
Feature Request: Add PHP 7.4 support

### ISSUE THREAD

**Issue by Neodork** [weprovide/valet-plus#427]
- [X] I've checked the issue queue and could not find anything similar to my feature.
- [X] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`

**Why implement this feature?**  
PHP versions are moving up and we'll need to add 7.4 support. The support is already added in the brew tap.

**What will be required for this feature?**  
Add the constants and ensure it's building in the CI/CD.

**Sources**
https://www.php.net/supported-versions.php

**Comment by Neodork** [comment]
This is now released in the `2.x` branch.

**Comment by royduin** [comment]
When can we expect a public release with PHP 7.4 support?
