### ISSUE TITLE
Bug: Wordpress Multisite Subdirectory Driver Not Working

### ISSUE THREAD

**Issue by RMcLeod79** [weprovide/valet-plus#429]
- [✅] I've checked the issue queue and could not find anything similar to my bug.
- [✅] I'm on the latest version of valet-plus (`valet --version`): `1.0.29`
- [✅] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When browsing a site within a Wordpress Multisite install no assets are loaded

**What was supposed to happen?**
When browsing a site that uses subdirectories as opposed to subdomains, the subdirectory should be stripped from the URL for all assets.

**What actually happened?**
The subdirectory isn't stripped

**How to reproduce this?**
Have a WordPress Multisite install, setup a new site that uses subdirectories. Browse the new site.

**What is the solution?**
I will be creating a Pull Request with the fix.

**Comment by Neodork** [comment]
@jeremyfelt @RMcLeod79 Could you guys reupload the PR targeting the correct branch using the correct format?
