### ISSUE TITLE
Bug: break change with Symfony\Component\Translation\TranslatorInterface On Laravel Project

### ISSUE THREAD

**Issue by zymawy** [weprovide/valet-plus#431]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
there is a break change with   Symfony\Component\Translation\TranslatorInterface::setLocal

**What was supposed to happen?**
Everything Should Work Normal 

**What actually happened?**
A description of what actually happened.

**How to reproduce this?**
using "symfony/translation": "4.3.8" of Symfony Did solve it but you need to include it in every project 
or branch.

**What is the solution?**
A description of the proposed solution.

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by Omar1415** [comment]
this is need atticntion

**Comment by Neodork** [comment]
@zymawy @Omar1415 There is not enough information in this ticket for us to act upon. Could you explain how that breaking change effects valet-plus and how we can reproduce this in steps?
