### ISSUE TITLE
Unable to determine linked PHP

### ISSUE THREAD

**Issue by m9iqbal** [weprovide/valet-plus#433]
I've seen this issue reported earlier in #114 and #149 but the proposed solutions haven't worked for me.

I'm on the latest stable version (i.e Valet+ 1.0.29) and have tried relinking php@7.2 but I still keep getting `Unable to determine linked PHP` every time I run `valet use 7.2`

Full output is below:

```$ valet use 7.2
[php@7.1] Unlinking
Unlinking /usr/local/Cellar/valet-php@7.1/7.1.33_2... 344 symlinks removed

[libjpeg] Relinking
[php@7.2] Linking
Warning: Already linked: /usr/local/Cellar/valet-php@7.2/7.2.24_2
To relink: brew unlink valet-php@7.2 && brew link --force valet-php@7.2

[valet-php@7.1] Stopping
[valet-php@7.2] Stopping
[BREW TAP] henkrehorst/php already installed
PHP Warning:  readlink(): No such file or directory in /Users/mudassar/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 314

Warning: readlink(): No such file or directory in /Users/mudassar/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 314

In PhpFpm.php line 307:
                                   
  Unable to determine linked PHP.  
                                   

use [<service>] [<targetVersion>]```

**Comment by Neodork** [comment]
@m9iqbal Could you show us your PATH variable?

**Comment by diazwatson** [comment]
Check what php binary you are using, it should be the one in:
```
usr/local/bin/php
```
**not** the one in:
```
usr/bin/php
```

to fix that, add
```
export PATH="/usr/local/bin/php:$PATH"
```
to your `.bash_profile`, `.zshrc`, etc. File

**Comment by m9iqbal** [comment]
@Neodork Please find below my PATH variable's value

`/Users/mudassar/.magento-cloud/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/mudassar/.composer/vendor/bin`

@diazwatson I'm already using the PHP binary inside /usr/local/bin/php.

`$ which php`
`/usr/local/bin/php`

**Comment by diazwatson** [comment]
@m9iqbal and what is the output of 
```
ls -al /usr/local/bin/php
```
?

**Comment by m9iqbal** [comment]
Currently, it's pointing to PHP 7.1, which works fine. The problem arises when I try to use PHP 7.2

Full output is below:

```lrwxr-xr-x  1 mudassar  admin  40 Dec 23 16:01 /usr/local/bin/php -> ../Cellar/valet-php@7.1/7.1.33_2/bin/php```

**Comment by diazwatson** [comment]
Try switching to 7.2 and paste in here the errors you get

**Comment by m9iqbal** [comment]
@diazwatson I've shared the errors in bug description above. Please let me know if you need further details.

**Comment by diazwatson** [comment]
Installing in a brand new mac I am now have the same issue than you 🤣 
Have tried everything but nothing seems to work 🤦‍♂

**Comment by capitaladot** [comment]
Same issue on Mojave. Blew away installation due to borked MySQL and now dead in the water and can't seem to re-install. Guess I'll try a version below 1.0.29?

**Comment by Rosebudlia** [comment]
I've been having this problem as well.

From tinkering around with the code a bit, I found that in the following snippet:

`   public function linkedPhp()
    {
        if (!$this->files->isLink('/usr/local/bin/php')) {
            throw new DomainException("Unable to determine linked PHP.");
        }

        $resolvedPath = $this->files->readLink('/usr/local/bin/php');

        $versions = self::SUPPORTED_PHP_FORMULAE;

        foreach ($versions as $version => $brewname) {
            if (strpos($resolvedPath, '/' . $brewname . '/') !== false) {
                return $version;
            }
        }

        throw new DomainException("Unable to determine linked PHP.");
    }`

$brewname is always being set to valet-php@{some_php_version}, which then is not found because the linked PHP version in the path string is just a number (i.e. without valet-php at the beginning). Not sure whether this is a general problem or a my-individual-laptop-problem. But in any case, either I need to link a valet-php version of PHP in Homebrew (which I'm not sure is doable, and strikes me as a little odd because we might be using php for other stuff) or this check needs to change so that regular PHP versions are also successfully found in the path string. When I change the function thus, it works:

`    /**
     * Determine which version of PHP is linked with Homebrew.
     *
     * @return string
     * @internal param bool $asFormula
     */
    public function linkedPhp()
    {
        if (!$this->files->isLink('/usr/local/bin/php')) {
            throw new DomainException("Unable to determine linked PHP file.");
        }

        $resolvedPath = $this->files->readLink('/usr/local/bin/php');

        $versions = self::SUPPORTED_PHP_FORMULAE;

        foreach ($versions as $version => $brewname) {
            if (strpos($resolvedPath, '/' . $version) !== false) {
                return $version;
            } 
        }

        throw new DomainException("Unable to determine linked PHP.  " . $resolvedPath);
    }`

Does this help at all?

**Comment by Neodork** [comment]
Hey All,

We've identified several issues regarding the stacktrace and behaviour mentioned in the OP.

We're planning to improve the switch flow. Please see https://github.com/weprovide/valet-plus/issues/451 for more information.

I'll be closing this ticket now since there are several different issues being reported. The above ticket should triggered on all error states thus making it easier to identify any bug related to switching in valet+ `2.x`.

**Comment by VladyslavSikailo** [comment]
Install PHP 7.3 manually by this command: `brew install valet-php@7.3`

Create a symlink for /usr/local/bin/php by this command:
`ln -s /usr/local/opt/valet-php@7.3/bin/php /usr/local/bin/php`
if you have an error: "ln: /usr/local/bin/php: File exists", run `rm /usr/local/bin/php`

Run `valet use 7.3`

Hope that it helps!

**Comment by r-martins** [comment]
> Install PHP 7.3 manually by this command: `brew install valet-php@7.3`
> 
> Create a symlink for /usr/local/bin/php by this command: `ln -s /usr/local/opt/valet-php@7.3/bin/php /usr/local/bin/php` if you have an error: "ln: /usr/local/bin/php: File exists", run `rm /usr/local/bin/php`
> 
> Run `valet use 7.3`
> 
> Hope that it helps!


**I got this:**
$ brew install valet-php@7.3
==> Downloading https://dl.bintray.com/henkrehorst/valet-php/valet-php%407.3-7.3.27_2.sierra.bottle.tar.gz
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 403 Forbidden
Error: valet-php@7.3: Failed to download resource "valet-php@7.3"
Download failed: https://dl.bintray.com/henkrehorst/valet-php/valet-php%407.3-7.3.27_2.sierra.bottle.tar.gz

**Solution:**
I deleted manually ( `sudo rm -rf /usr/local/Cellar/valet-php@7.3/`) and did `valet fix --reinstall`.
