### ISSUE TITLE
FR: use gzip for sql files

### ISSUE THREAD

**Issue by SanderJP** [weprovide/valet-plus#44]
He, I could have a look to make this myself but I'm not sure about other platform compatibility and what gzip progs to use etc, but it would be great if the db export/dump can directly pipe the sql into a .gz file. Also reading a .gz file on import/reimport would be awesome! Space is valuable ;)

**Comment by timneutkens** [comment]
Feel free to add it 👌

**Comment by srikat** [comment]
can be done with a bash script.

```
#!/usr/bin/env /bin/bash

# change current directory to the site
cd ~/Sites/$1

wp db export $1.sql

gzip $1.sql
```

To run:

`wp-export example`

**Comment by SanderJP** [comment]
PR is up: https://github.com/weprovide/valet-plus/pull/62
