### ISSUE TITLE
Bug: Mailhog won't catch mails send from CLI

### ISSUE THREAD

**Issue by pascalheidmann** [weprovide/valet-plus#442]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When running PHP scripts via cli that are sending out mails those won't be catched by mailhog but potentially send out.

**What was supposed to happen?**
No mails send.

**What actually happened?**
Mails got send out.

**How to reproduce this?**
Run a script from cli that will send a mail.

**What is the solution?**
Valet should provide an `php.ini` for cli that won't fallback to regular sendmail but instead use `mhsendmail` or similar solution. See https://github.com/mailhog/mhsendmail

**Comment by Neodork** [comment]
@pascalheidmann Can you supply a simple script we can use to test this? I use the CLI for quite some things and have never had it bypass my default mail port. If you can supply a small script to reproduce I'll have a look at this.

**Comment by pascalheidmann** [comment]
@Neodork just create a script `mailtest.php`:
```
<?php
mail("your@email.com", "test", "test");
```
and run it via `php mailtest.php` and you should get a mail.

**Comment by SanderAtom** [comment]
@pascalheidmann can you make sure you run valet's php in CLI?
`which php` should show `/usr/local/bin/php` and `ls -l /usr/local/bin/php` should show something like `/usr/local/bin/php -> ../Cellar/valet-php@7.3/7.3.2/bin/php`
I've just tested both visiting the webpage and executing `php test.php` and both ways the emails are picked up by Mailhog.

**Comment by pascalheidmann** [comment]
Ok, looks like something was not configured correctly or old code, and the wrong php ini got loaded... 🤷‍♂️
Guess this issue can be closed then

**Comment by SanderAtom** [comment]
Ok glad it's solved, thanks for the feedback.
