### ISSUE TITLE
Bug: Valet secure <sitename> switches php version

### ISSUE THREAD

**Issue by dipsaus9** [weprovide/valet-plus#445]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `1.0.29`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Enabling ssl for your site switches php cause it is turning off all the settings and restarting your system. After restarting your pc this problem is solved again.

**What was supposed to happen?**
After enabling ssl the php version should stay the same.

**What actually happened?**
I uses `valet use 7.2` then `valet secure website`. After this my php version turned back to 7.1

**How to reproduce this?**
I uses `valet use 7.2` then `valet secure website`. After this my php version turned back to 7.1

**What is the solution?**
Restarting the right php version.

**Sources**
Terminal says php version was 7.2 while my phpinfo() said 7.1

**Comment by Neodork** [comment]
This generally happens when you PATH variable is already pointing towards another PHP version.

Can you check or leave your entire PATH variable here?

**Comment by dipsaus9** [comment]
```
export PATH="/usr/local/opt/valet-php@7.2/bin:$PATH"
export PATH="/usr/local/opt/valet-php@7.2/sbin:$PATH"
```

**Comment by dipsaus9** [comment]
I've made a mistake. The `export PATH` was defined but was closed earlier. This means it works when switching but it resets after every change. Sorry.

**Comment by dipsaus9** [comment]
Reopening issue as the problem did not resolve after restart of my computer. 

I restarted my computer and created some new projects with valet. But after valet secure valet was using php 7.1 again, even though my terminal gave me the 7.2 version. 

```
export PATH="/usr/local/git/bin:/sw/bin:/usr/local/bin:/usr/local:/usr/local/sbin:/usr/local/mysql/bin:$PATH"
export PATH="/usr/local/opt/valet-php@7.2/bin:$PATH"
export PATH="/usr/local/opt/valet-php@7.2/sbin:$PATH"
export PATH="$PATH:$HOME/.composer/vendor/bin"
```
This is my PATH export in my bash_profile.

**Comment by Neodork** [comment]
@dipsaus9 Please join slack so we can go over this.

**Comment by mischabraam** [comment]
Is this still an issue? I can't reproduce it.
