### ISSUE TITLE
Bug:   Brew was unable to install [mysql-utilities].  

### ISSUE THREAD

**Issue by nerotic** [weprovide/valet-plus#446]
- [X] I've checked the issue queue and could not find anything similar to my bug.
- [X] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [X] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Installation does not complete for Valet+2dev

**What was supposed to happen?**
Installation should have completed successfully without this dependency.

**What actually happened?**
```
[mysql-utilities] Installing
Error: No available formula with the name "mysql-utilities" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
Error: No similarly named formulae found.
==> Searching taps on GitHub...
==> Searching for similarly named formulae...
==> Searching taps...
Error: No formulae found in taps.


In Brew.php line 107:
                                                 
  Brew was unable to install [mysql-utilities].  
```
                                                 

install [--with-mariadb]

**How to reproduce this?**
Run install

**What is the solution?**
Apparently provided in https://github.com/weprovide/valet-plus/issues/436 but not working.

**Comment by Neodork** [comment]
Hi!

We've fixed this issue and merged the fix in the `2.x` branch. It will be ready for the 2.0.0 release.

See https://github.com/weprovide/valet-plus/pull/437 for more information.

**Comment by rafaelstz** [comment]
To fix it without updating to 2.x, I opened the file `~/.composer/vendor/weprovide/valet-plus/cli/Valet/Mysql.php` and I removed/commented this snippet below.


```php
if (!$this->brew->installed('mysql-utilities')) {	
    $this->brew->installOrFail('mysql-utilities');
}
```

So, run `valet install` again.
