### ISSUE TITLE
apc.shm_size too high?

### ISSUE THREAD

**Issue by noplanman** [weprovide/valet-plus#45]
Hi, it seems that the `apc.shm_size` is too high for my setup. Having it set to `2048M` I get the following error when using PHP (e.g. `php -v`)

`PHP Fatal error:  PHP Startup: apc_mmap: ftruncate failed: in Unknown on line 0`

When I set it lower, to say `512M`, PHP works perfectly with APCU.

Would there be a way to set this dynamically somehow from a config? Now I need to manually change the `cli/stubs/z-performance.ini` for PHP version switches to work properly. Or I need to set the value in `/usr/local/etc/php/x.y/conf.d/z-performance.ini` manually each time.

**Comment by timneutkens** [comment]
@noplanman I guess we can move it down a bit 👌
