### ISSUE TITLE
Bug:   Brew was unable to install [mysql-utilities]. 

### ISSUE THREAD

**Issue by nerotic** [weprovide/valet-plus#452]
- [X] I've checked the issue queue and could not find anything similar to my bug.
- [X] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [X] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
After reading https://github.com/weprovide/valet-plus/issues/446 I proceed to reinstall the dev branch but still had an error related to mysql-utilities.

**What was supposed to happen?**
Valet install should complete without errors

**What actually happened?**
```
Error: No available formula with the name "mysql-utilities" 
Found a cask named "mysql-utilities" instead. Try
  brew cask install mysql-utilities

In Brew.php line 107:
                                                 
  Brew was unable to install [mysql-utilities]. 
```
                                                

**How to reproduce this?**
```
composer require weprovide/valet-plus:2.x-dev
valet fix
valet install
```

**Comment by Neodork** [comment]
Are you sure you have 2.x-dev installed? I see no such errors in the CI/CD.

**Comment by nerotic** [comment]
I am.. i was stepping through it with Sandra yesterday in slack but I also
had some shrapnel left over from one x and that was causing problems so I
completely uninstall everything and I'm just waiting for the release to
retry 👍

**Comment by Neodork** [comment]
@nerotic Ah oke, we'll have `2.0.0` ready around sunday this week. I'll close for now. You can open a new ticket if you're still experiencing this with the new release. Thanks for your input.
