### ISSUE TITLE
Valet unlink always returns success message and has unclear description how to use it

### ISSUE THREAD

**Issue by SanderAtom** [weprovide/valet-plus#453]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
`valet unlink` always returns the success message even if the link could not be found and unlinked. The documentation doesn't mention to not include `.test` in the command.
`valet links` shows `name.test` but you have to use `valet unlink name`.

**What was supposed to happen?**
Throw an error.

**What actually happened?**
Success message without actually unlinking.

**How to reproduce this?**
Run `valet unlink bla.test` (if bla does not exists).

**What is the solution?**
Throw an error if the link was not found and the unlinking was unsuccesful. Improve the command description.

**Comment by Neodork** [comment]
Merged into `2.x` for next release.
