### ISSUE TITLE
Feature request: Allow innodb_file_per_table setting to be toggled in MySQL

### ISSUE THREAD

**Issue by darthsteven** [weprovide/valet-plus#456]
- [x] I've checked the issue queue and could not find anything similar to my feature.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.0.0`

**Why implement this feature?**  
As previously described in #386 and #417 if you import a database into the MySQL configured by Valet+ then the `ibdata1` file grows in size **and will never shrink**. You can drop the database all you want, but the `ibdata1` will be forever at least that size.
The only way to make the file smaller is to delete it (and _all_ of your MySQL data along with it).

As mentioned in #386:

> Given that this is developer tool [Valet+], I suggest that the killer feature here is that I can do a one-off import of a large DB, drop it and I'll actually be able to reclaim that disk space :)

**What will be required for this feature?**  

Changing the Valet+ MySQL configuration to include:

> innodb_file_per_table=ON

Note that this is now the MySQL default from 5.6 onwards anyway.

**Sources**

* #386
* #417 
* https://dev.mysql.com/doc/refman/5.6/en/innodb-file-per-table-tablespaces.html
* https://stackoverflow.com/questions/3456159/how-to-shrink-purge-ibdata1-file-in-mysql

**Comment by darthsteven** [comment]
@Neodork you mentioned in #417 that you have some performance benchmark showing that `innodb_file_per_table=OFF` is 'faster' in some regard? Could you share it here please.

**Comment by Neodork** [comment]
@darthsteven I'll see if I can report them here. Did some reading so I'll have to track back a bit. I'll get back to you. Thanks for recreating the issue. I really appreciate the effort!

**Comment by darthsteven** [comment]
@Neodork how's the reading going :)

**Comment by WinstonN** [comment]
I have tested setting `table_open_cache=1000` and `innodb_file_per_table=ON` and so far no crashes `Server version: 5.7.29 Homebrew`

**Comment by Neodork** [comment]
@darthsteven I think it's save to say we can move towards this. Do you know if switching this is safe for all users or should be create an update path?

**Comment by darthsteven** [comment]
So are you leaning toward making valet have `innodb_file_per_table=on` always rather than configurable?

If we're going to change it for everyone with no configurability then we can change it now and most people won't notice any difference really, until they create tables or drop DBs. MySQL will transparently move them over to being in their own files, but won't ever shrink the `ibdata1` file as discussed. Not sure if we want to provide an upgrade path (script to dump and re-import all databases), or just something in the upgrade notes about how to shrink that file.

**Comment by darthsteven** [comment]
Any thoughts or movement on this one?

**Comment by royduin** [comment]
+1 to remove the setting as the default from MySQL 5.6 and up is `innodb_file_per_table=on`.

**Comment by darthsteven** [comment]
I'm closing this one out as there clearly isn't the appetite to make this change to align with the MySQL default.
Also, I don't use valet-plus any more, so won't be pushing this along etc.
