### ISSUE TITLE
Improvement: Limit size of log files

### ISSUE THREAD

**Issue by mischabraam** [weprovide/valet-plus#462]
- [x] I've checked the issue queue and could not find anything similar to my feature.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`

**Why implement this improvement?**  
This improvement suggestion involves the exiting logging feature of Valet+. Currently log files are captured and made readable with `valet log ...`. These log files are locate at `~/.valet/Log` and grow in size without limits. My hard drive just went out of free space when I noticed I had around 6 Gb of log files at this location.

On webservers I would implement something like logrotation. However, since this a development environment I don't see a reason to keep these log files indefinitely. I would suggest to build something to automatically purge the log files. Probably something more sophisticated then just remove, but at least prevent hard drives to grow out of space because of development log files. 

**What will be required for this feature?**  
.. not sure

**Sources**
.. no sources

**Comment by Neodork** [comment]
**What will be required for this feature?**
Log rotation/limitation for the different log types, per log writing service.

e.g:  php, php-fpm, nginx, mysql, mailhog, redis

**Comment by mischabraam** [comment]
https://serverfault.com/a/352980
https://stackoverflow.com/questions/32991484/how-to-set-limit-for-nginx-log-files-on-mac-os

**Comment by mischabraam** [comment]
Added to 3.x-dev
