### ISSUE TITLE
Bug: Fresh install doesn't work. Conflicts with laravel vapor dependency of illuminate/container v6.0 

### ISSUE THREAD

**Issue by keganlester** [weprovide/valet-plus#463]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I have laravel vapor and it requires illuminate/container v6 and valet plus requires ^v.5.1

**What was supposed to happen?**
The package was supposed to install
**What actually happened?**
I got dependency errors telling me they are conflicting.

**How to reproduce this?**
composer global require laravel/vapor-cli
then
composer global require weprovide/valet-plus

**What is the solution?**
Update depedencies to handle illuminate/container ^v6.0

**Comment by Neodork** [comment]
@keganlester As you can see in packagist: https://packagist.org/packages/illuminate/container#v6.0.0

The illuminate container v6.0.0 is not compatible with lower than PHP 7.2. Thus making us impossible to add this in 2.x. We could aim for 3.x when we're dropping such support.

**Comment by Neodork** [comment]
@keganlester As you can see in packagist: https://packagist.org/packages/illuminate/container#v6.0.0

The illuminate container v6.0.0 is not compatible with lower than PHP 7.2. Thus making us impossible to add this in 2.x. We could aim for 3.x when we're dropping such support.
