### ISSUE TITLE
Bug: valet fix returns process signal "9"

### ISSUE THREAD

**Issue by dingo-d** [weprovide/valet-plus#465]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I get the following errors when running both `valet fix` and `valet install`

```bash
Removing all old php56- packages from homebrew/php tap

Removing all old php70- packages from homebrew/php tap

Removing all old php71- packages from homebrew/php tap

Removing all old php72- packages from homebrew/php tap

Removing all old n98-magerun packages from homebrew/php tap

Removing drush package from homebrew/php tap

[php5.6] Disabling modules: apcu, intl, mcrypt
[php7.0] Disabling modules: apcu, intl, mcrypt
[php7.1] Disabling modules: apcu, intl, mcrypt
[php7.2] Disabling modules: apcu, intl, mcrypt
Installing and linking new PHP homebrew/core version.
Uninstalling /usr/local/Cellar/valet-php@7.2/7.2.24_2... (515 files, 75.0MB)


In Process.php line 429:

  The process has been signaled with signal "9".


fix [--reinstall]
```

The install throws

```bash
[php] Checking for errors within the php installation...
[nginx] Stopping
[valet-php@7.1] Stopping
[mysql@5.7] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[devtools] zlib already installed
[binaries] Installing binaries
[BREW TAP] henkrehorst/php already installed

In PhpFpm.php line 308:

  Unable to determine linked PHP.


install [--with-mariadb]
```

**What was supposed to happen?**

Install should work.

**What actually happened?**

It errored out

**How to reproduce this?**

Have a new mac, try to follow installation steps.

**Comment by dingo-d** [comment]
I've restarted the mac and I avoided doing `valet fix` since that caused the `valet-php@7.2` to be removed for some reason so I just went ahead, force linked it and installed valet so it passed.

**Comment by nerotic** [comment]
@dingo-d Can you please provide instructions on how to force link?  I'm having the same issue.

**Comment by dingo-d** [comment]
So I had a new mac, so nothing was installed. I just followed the [installation instructions](https://github.com/weprovide/valet-plus/wiki/Installation) and got to part 4

```bash
brew link valet-php@7.2 --force
```

but don't do step 8, because that can unlink the PHP. By default, the latest Catalina has PHP 7.3 iirc, but  the valet+ will install PHP 7.2. So before step 8, the `php -v` should say 7.2.

Then the installation with `valet install` should pass.

**Comment by ChristopherDosin** [comment]
I am having the same issue today. New macOS 10.15.4 installation, nothing installed.

```
valet fix
Password:
Removing all old php56- packages from homebrew/php tap

Removing all old php70- packages from homebrew/php tap

Removing all old php71- packages from homebrew/php tap

Removing all old php72- packages from homebrew/php tap

Removing all old n98-magerun packages from homebrew/php tap

Removing drush package from homebrew/php tap

[php5.6] Disabling modules: apcu, intl, mcrypt
[php7.0] Disabling modules: apcu, intl, mcrypt
[php7.1] Disabling modules: apcu, intl, mcrypt
[php7.2] Disabling modules: apcu, intl, mcrypt
Installing and linking new PHP homebrew/core version.
Uninstalling /usr/local/Cellar/valet-php@7.2/7.2.29... (514 files, 74.8MB)


In Process.php line 429:
                                                  
  The process has been signaled with signal "9".  
                                                  

fix [--reinstall]
```

**Comment by elburro1887** [comment]
Had the same issue when upgrading to php 7.4, needed to do:

`brew link valet-php@7.4 --force`

and if that errors then use:

`brew link valet-php@7.4 --overwrite`

then:

`valet install`

worked again
