### ISSUE TITLE
safari can't connect to server

### ISSUE THREAD

**Issue by elsuper-josev** [weprovide/valet-plus#466]
Hi,

New at Git and with Valet+. Trying to test as a Laravel environment.

 I've checked the issue queue and could not find anything similar to my bug.
 I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Created a new laravel site: algo.test

Got this error in Safari, but in Spanish, literal translation: 
`Safari can't connect to server`
Firefox: 
`Can't connect.`

Created another site uno.test, with a simple index.php file. Same error returned

Ping to anything.test returns 127.0.0.1

Tried in a different port for Nginx 8088, no way.

I setup Valet+ following your docs.

After check and made many tests, removed Homebrew completely and installed again from scratch.

**What was supposed to happen?**
Looks like there is some kind of problem with some brew services like dnsmasq, nginx and valet-php@7.2 are listed as started but displayed in yellow. Other services like mysql or redis are green.

![Captura de pantalla 2020-02-24 a las 3 37 28](https://user-images.githubusercontent.com/5492585/75126257-61ebc000-56b9-11ea-832c-f53326b6b56d.png)

Checking Nginx error log found errors like this
`2020/02/24 02:47:44 [emerg] 65212#0: open() "/usr/local/etc/nginx/valet/mailhog.conf" failed (2: No such file or directory) in /usr/local/etc/nginx/nginx.conf:43`

I replaced all relative routes in Nginx.conf
`include valet/mailhog.conf`

by absolute paths
`/usr/local/etc/nginx/valet/mailhog.conf`

ps aux | grep nginx  doesn't return anything running.

What should I check?

Thanks
Jose

**Comment by elsuper-josev** [comment]
Hello,

I got sites on the browser!

Thanks to Serializator answer in this issue (sudo nginx -t):
https://github.com/weprovide/valet-plus/issues/391

...elasticsearch.conf wast not being included by Nginx. 

Now works but brew services list shows the same services still in yellow. Nginx log shows successful start.

Any idea about what have to check what still wrong with Nginx dnsmasq and valet-php?

Thanks for the help.

**Comment by elsuper-josev** [comment]
Don't know if it's relevant. All services in yellow are root owned, green ones by my user. I remember you because those Valet issues I removed everything and installed Homebrew from scratch.

![Captura de pantalla 2020-02-24 a las 11 06 21](https://user-images.githubusercontent.com/5492585/75143824-0e4b9780-56f6-11ea-9f06-c8ec5cae735d.png)

**Comment by SanderAtom** [comment]
Hi @elsuper-josev annoying you ran into that bug, we are aware of it. In fact there is a fix (#464) for it, but it's not released in 2.x yet. I'll check if this can be made into a minor release.

**Comment by Neodork** [comment]
This is merged now, closing.
