### ISSUE TITLE
Setting password for root user

### ISSUE THREAD

**Issue by LucasMali** [weprovide/valet-plus#468]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `❯ `Valet+ 2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
❯ valet install
[php] Checking for errors within the php installation...
[nginx] Stopping
[valet-php@7.2] Stopping
[mysql@5.7] Stopping
[redis] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[devtools] zlib already installed
[binaries] Installing binaries
[BREW TAP] henkrehorst/php already installed
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions
	apcu successfully installed
	apcu successfully enabled
	geoip is already installed, skipping...
	geoip is already enabled, skipping...
	yaml is already installed, skipping...
	yaml is already enabled, skipping...
[PECL-CUSTOM] Installing extensions
[valet-php@7.2] Restarting
[dnsmasq] Restarting
[mysql@5.7] Stopping
[mysql@5.7] Configuring
[mysql@5.7] Restarting
[redis] already installed
[redis] Restarting
[mailhog] already installed
[mailhog] Restarting
[nginx] Restarting
**Setting password for root user failed.**

Valet installed successfully!

**What was supposed to happen?**
Installs correctly w/o error

**What actually happened?**
Doesn't install correctly

**How to reproduce this?**
I followed the guild to a 'T' https://github.com/weprovide/valet-plus/wiki/Installation

**What is the solution?**
I don't know.

**Comment by ityetti** [comment]
@LucasMaliszewski Hello. Try to do next steps.
Open terminal and run next commands:
1. `killall mysqld mysqld_safe` (To kill all mysqld process)
2. `mysql.server start --skip-grant-tables`
3. `mysql -uroot --password=""`
After that command your terminal would look likes on the screenshots
<img width="561" alt="MariaDB" src="https://user-images.githubusercontent.com/26219171/76131754-73698c00-6018-11ea-81d6-c70c8807c83c.png">

Then enter commands fo change root password:
1. use mysql;
2. SET PASSWORD FOR 'root'@'localhost' = PASSWORD("TOOR");
3. flush privileges;
4. quit

Enjoy your work)
Now you can connect to MySQL and edit your tables!

**Comment by SanderAtom** [comment]
@LucasMali did @ityetti's response above help with your issue?

Also I have seen this error before when it was not actually a problem (could connect to the database just fine), only that Valet+ couldn't set it up. Probably related to configuration of a previous mysql installation.

**Comment by andresams** [comment]
In my case what I did was to use `sudo mysql -u root` on the terminal. Then I changed the database to `mysql` and set up my password:

1. `use mysql;`
2. `SET PASSWORD FOR 'root'@'localhost' = PASSWORD("ROOTPASS");`

Reinstalling and other stuff didn't work out for me.

**Comment by Neodork** [comment]
The error that is displayed tends to happen when Valet+ does not know of an existing MySQL installation root users password.  Closing ticket since user @ityetti pretty much sums up what to do to reset your password to root.

In addition to that we'll need to add some MySQL test cases to the CI/CD.
