### ISSUE TITLE
Editing Nginx Config for Valet+

### ISSUE THREAD

**Issue by brandammo** [weprovide/valet-plus#471]
I've just installed Valet+ and Magento2 locally.

Everything is working well, except i commonly use Wordpress in Magento2 via Fishpig's Wordpress plugin. This enabled me to install Wordpress in the same root dir as Magento 2 and integrate with Magento2.

The issue i am facing is Valet+ is running Nginx and so Wordpress requires an edit to the Nginx config to allow it to be visible when alongside the Magento install.

This is a little over my head so hoping someone might be able to explain to me how i can add the below to the config for my Magento install on Valet+.

`location /wp/ {
  index index.html index.php;
  try_files $uri $uri/ /wp/index.php?q=$uri&args;

  location ~ \.php$ {
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  /wp/index.php;
    include        fastcgi.conf;
  }
}`

More here: https://fishpig.co.uk/magento/wordpress-integration/nginx/

**Comment by ryangjchandler** [comment]
What OS are you running?

**Comment by SanderAtom** [comment]
Hi @brandammo can you try `valet link wp` in the wordpress sub directory to create `wp.test` (or change the name) and open `wp.test`. It should pick up the `WordpressValetDriver` and load Wordpress with the right nginx configuration. You might need some more local configuration, but let's see if linking works first.

**Comment by brandammo** [comment]
Thanks @SanderAtom that was the fix. I had help from the Slack group on this too.

Appreciate your reply!

**Comment by ryanpalmerweb** [comment]
This was our solution

`<?php

class FishpigValetDriver extends Magento2ValetDriver
{
    public $wp_root = "wp";
    /**
     * Determine if the driver serves the request.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return bool
     */
    public function serves($sitePath, $siteName, $uri)
    {
        if (file_exists($sitePath.'/www/wp/wp-content/themes/fishpig/index.php')) {
            return true;
        }

        return parent::serves($sitePath, $siteName, $uri);
    }

    /**
     * Determine if the incoming request is for a static file.
     *
     * @param  string  $sitePath
     * @param  string  $siteName
     * @param  string  $uri
     * @return string|false
     */
    public function isStaticFile($sitePath, $siteName, $uri)
    {
        // If the URI contains one of the main WordPress directories and it doesn't end with a slash,
        // drop the subdirectory from the URI and check if the file exists. If it does, return the new uri.
        if (stripos($uri, 'wp-admin') !== false || stripos($uri, 'wp-content') !== false || stripos($uri, 'wp-includes') !== false) {
            if (substr($uri, -1, 1) == "/") {
                return false;
            }

            $new_uri = substr($uri, stripos($uri, '/wp-'));

            if ($this->wp_root !== false && file_exists($sitePath . "/{$this->wp_root}/wp-admin")) {
                $new_uri = "/{$this->wp_root}" . $new_uri;
            }

            if (file_exists($sitePath . $new_uri)) {
                return $sitePath . $new_uri;
            }
        }

        return parent::isStaticFile($sitePath, $siteName, $uri);
    }
}
`
