### ISSUE TITLE
Bug: Upgrade from 1.0.29 to 2.0.0 - install error with signal "6".

### ISSUE THREAD

**Issue by snHolst** [weprovide/valet-plus#472]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
A description of what you think the problem is.
`[php] Checking for errors within the php installation...
[nginx] Stopping
[valet-php@7.1] Stopping
[valet-php@7.2] Stopping
[mariadb] Stopping
[redis] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[devtools] zlib already installed
[binaries] Installing binaries
[BREW TAP] henkrehorst/php already installed
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions
	apcu is already installed, skipping...
	apcu is already enabled, skipping...
	geoip is already installed, skipping...
	geoip is already enabled, skipping...
	yaml is already installed, skipping...
	yaml is already enabled, skipping...
[PECL-CUSTOM] Installing extensions
[valet-php@7.2] Restarting
[dnsmasq] Restarting
[mariadb] Stopping
[mariadb] Configuring
[mariadb] Restarting
[redis] already installed
[redis] Restarting
[mailhog] already installed
[mailhog] Restarting
[nginx] Restarting

In Process.php line 429:
                                                  
  **The process has been signaled with signal "6".**  
                                                  

install [--with-mariadb]
`

**What was supposed to happen?**
A description of what you think was supposed to happen.

**What actually happened?**
A description of what actually happened.

**How to reproduce this?**
A step by step guide on how to reproduce this issue.

**What is the solution?**
A description of the proposed solution.

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by agengdp** [comment]
I have same issues, any idea how to fix this ?

**Comment by snHolst** [comment]
actually yes, do this...
brew link openssl --force
brew update && brew upgrade
brew services restart --all
brew tap henkrehorst/php
brew install valet-php@7.2
valet fix --reinstall
valet install --with-mariadb (with or without MariaDB)

**Comment by Neodork** [comment]
Due to no response, closing.
