### ISSUE TITLE
Bug: MySQL 5.7 can open too many files preventing DB connections

### ISSUE THREAD

**Issue by darthsteven** [weprovide/valet-plus#474]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
(Note I realised half way through writing this up that this won't apply to everyone, because I'm running config described in #456)

If you have a database with a lot of tables then you can run into this MySQL bug/issue:
https://expressionengine.com/blog/mysql-5.7-server-os-x-has-gone-away
Open the database with a GUI tool like Sequel pro and open a database with many 1000s of table, and then you'll be unable to make a new connection to the database.

**What was supposed to happen?**
You can make new connections to the database.

**What actually happened?**
The new DB connection is dropped and this error is logged to the MySQL log:

> File Descriptor %d exceedeed FD_SETSIZE=%d

**How to reproduce this?**
If you system FD_SETSIZE is < 4096 then:
Install Valet-plus, create a database with more tables that the system level FD_SETSIZE.
Open the database in Sequel pro
Attempt to make a new client connection to the database.

Oh and now that I'm writing this up, maybe you only actually run into this with `INNODB_FILE_PER_TABLE=ON` as per #456 because presumably otherwise all tables are basically loaded with a single file descriptor per thread anyway.

**What is the solution?**
We could warn people about this at the very least, or a workaround is to reduce the `table_open_cache` config option to be less than the system FD_SETSIZE value.
Or we could simply wait for Oracle to fix MySQL.

Now that I think it's related to #456 actually maybe that means that the `table_open_cache` is crazy high in Valet-plus default config anyway? Under what circumstances would the default config actually _want_ 4096 tables open? There's a single monolithic table space, so we're configuring for having 4000+ threads reading data!?

So maybe the solution is to simply remove that line of config? Or reduce it to a more sensible level?

**Sources**
* https://expressionengine.com/blog/mysql-5.7-server-os-x-has-gone-away
* https://github.com/mysql/mysql-server/commit/de3d16186#diff-b7559927391564ed82ae7d4b821a7cf4R927
* https://bugs.mysql.com/bug.php?id=79125

**Comment by SanderAtom** [comment]
Hi @darthsteven you can change the `table_open_cache` variable Valet+ uses here: `/usr/local/etc/my.cnf`. Can you test if setting that to something like 1024 solves this issue with `INNODB_FILE_PER_TABLE=ON`?
Then we can test if changing this has any negative effect with `INNODB_FILE_PER_TABLE=OFF` in other situations and lower it.

But mostly I read in the articles that this should be fixed in MySQL 8.x and won't be backported to 5.x. So I'm not sure if simply lowering that variable fixes the issue.

**Comment by Neodork** [comment]
Due to no crashes reported after April, closing.
