### ISSUE TITLE
Bug: Could not symlink sbin/php-fpm

### ISSUE THREAD

**Issue by WaPoNe** [weprovide/valet-plus#475]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Trying this installation step:
`brew link valet-php@7.2 --force`

**What was supposed to happen?**
Link my PHP version

**What actually happened?**
I receive this error:
```
Linking /usr/local/Cellar/valet-php@7.2/7.2.28... 
Error: Could not symlink sbin/php-fpm
/usr/local/sbin is not writable.
```
..and /usr/local/sbin doesn't exist.

**How to reproduce this?**
A step by step guide on how to reproduce this issue.

**What is the solution?**
A description of the proposed solution.

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by SanderAtom** [comment]
Hi @WaPoNe this seems to be a permission issue, can you make sure `/usr/local/sbin` is owned by your user? `ls -l /usr/local/` should show something like:
```
...
drwxrwxr-x    8 username  admin    256 Apr 23 09:18 sbin
...
```
You can also join our Slack channel (bottom of the description here https://github.com/weprovide/valet-plus) for quicker debugging of the issue.

**Comment by Neodork** [comment]
Long time no input, closing.
