### ISSUE TITLE
Bug: cannot execute .php within magento 2 installation

### ISSUE THREAD

**Issue by kerlama** [weprovide/valet-plus#476]
**What is the problem?**
.php script(s) located under magento 2 directory could not be accessed, 404 not found

**What was supposed to happen?**
script(s) should be executed

**What actually happened?**
404 not found

**How to reproduce this?**
Install clean magento 2 and put .php with contents <?php phpinfo();

**Comment by SanderAtom** [comment]
Hi @kerlama the Valet+ default Magento2 driver uses `/pub` as the webroot, can you move the file there and try again?

**Comment by Neodork** [comment]
Due to no response, closing ticket.
