### ISSUE TITLE
Bug: elasticsearch.test not available after installing elasticsearch

### ISSUE THREAD

**Issue by Evertt** [weprovide/valet-plus#478]
**What is the problem?**
I installed elasticsearch using `$ valet install elasticsearch` and it seems to be correctly installed in that it responds to the 9200 port. However, the Wiki said that a GUI would be available at `elasticsearch.test`, which it isn't.

**What was supposed to happen?**
I assume I'm supposed to be presented with elasticsearch's web GUI.

**What actually happened?**
I just get the `Valet could not find directory elasticsearch` error message.

**How to reproduce this?**
I'm guessing by just starting with a fresh install of valet-plus 2.0 and then running `valet install elasticsearch`...

**What is the solution?**
No idea...

**Sources**
N/A

**Comment by Evertt** [comment]
Some extra information that may or may not be the actual cause of this bug:

I've been messing around with my installation recently. I thought it was time for me to upgrade valet-plus once more. So I did, but then I wasn't sure if my previous version was before `2.0.x`, so just to be sure I followed the [upgrade guide](https://github.com/weprovide/valet-plus/blob/master/UPGRADE-2.0.md). Then I also added PHP 7.4. In the whole process I ran `valet fix` and `valet install` multiple times.

And now I've noticed a new bug. Namely, even though I ran `valet use php 7.4`, and when I run `php -v` I can see that it's at 7.4, for some reason my websites are still served with php 7.3. I don't understand how or why that's happening. It seems like new settings are not fully applied. Which makes me wonder if this is also the reason that `elasticsearch.test` isn't working.

**Comment by SanderAtom** [comment]
@Evertt we discussed some problems in Slack, do you still experience the issues described here?

**Comment by Evertt** [comment]
@SanderAtom, nope. Here you can see a 3 minute screencast that demonstrates the problem:

https://youtu.be/9UJZzrCcMSs

**Comment by allrude** [comment]
Hi @Evertt perhaps this solves your problem, found it on Valet-plus Slack

 https://valet-plus.slack.com/archives/CC9USL55M/p1594274313249100?thread_ts=1593778548.210700&cid=CC9USL55M

credits go to [Theo](https://valet-plus.slack.com/team/UKN836SSK for pointing to the log file)
and to [tuomasanakkala](https://valet-plus.slack.com/team/UJFDK8SN5 for the nice step by step how-to)

It solved my problem, good luck

**Comment by mischabraam** [comment]
Fixed in https://github.com/weprovide/valet-plus/commit/58a92897a233a969456f5ad8904b65ad2540a099 and 3.x-dev
