### ISSUE TITLE
Bug: ping does not work after successful install

### ISSUE THREAD

**Issue by andreasotto** [weprovide/valet-plus#479]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
ping `*.test` does not work, but no errors while installation.

**What was supposed to happen?**
ping should work

**What actually happened?**
no dns resolution

```
$ ping -c1 foobar.test
ping: cannot resolve foobar.test: Unknown host
```

Here is the output from another `valet install` command.

```
iMac:tellie ao$ valet install --with-mariadb
[php] Checking for errors within the php installation...
[nginx] Stopping
[valet-php@7.2] Stopping
[mariadb] Stopping
[redis] Stopping
[devtools] Installing tools
[devtools] wp-cli already installed
[devtools] pv already installed
[devtools] geoip already installed
[devtools] zlib already installed
[binaries] Installing binaries
[BREW TAP] henkrehorst/php already installed
[PECL] Updating PECL channel: pecl.php.net
[PECL] Installing extensions
	apcu is already installed, skipping...
	apcu is already enabled, skipping...
	geoip is already installed, skipping...
	geoip is already enabled, skipping...
	yaml is already installed, skipping...
	yaml is already enabled, skipping...
[PECL-CUSTOM] Installing extensions
[valet-php@7.2] Restarting
[dnsmasq] Restarting
[mariadb] Stopping
[mariadb] Configuring
[mariadb] Restarting
[redis] already installed
[redis] Restarting
[mailhog] already installed
[mailhog] Restarting
[nginx] Restarting
Setting password for root user failed. 

Valet installed successfully!

```

Despite the message `Setting passwort for root user failed` (?) there is no error.

At what point can i begin to search ?

**Comment by m1kash** [comment]
@andreasotto Hello. Try to do next steps.
Open terminal and run next commands:
1. `brew uninstall dnsmasq`
2. `brew install dnsmasq`
3. `valet restart`

It's working for me!)

**Comment by SanderAtom** [comment]
Hi @andreasotto you can also join our Slack channel (bottom of the description https://github.com/weprovide/valet-plus), which can speed up debugging what's wrong.

**Comment by Neodork** [comment]
No response for a while, closing.
