### ISSUE TITLE
Undefined index: USER

### ISSUE THREAD

**Issue by dannygsmith** [weprovide/valet-plus#48]
I have installed https://github.com/aaemnnosttv/wp-cli-valet-command and was adding a user, and when I ran it I get the following error:

Don't go anywhere, this should only take a second...
Success: sample ready! https://sample.Notice: Undefined index: USER in /Users/riskiii/.composer/vendor/weprovide/valet-plus/cli/includes/helpers.php on line 175

Notice: Undefined index: USER in /Users/riskiii/.composer/vendor/weprovide/valet-plus/cli/includes/helpers.php on line 175
dev

I suspect the error is on this side, since USER is not declared before it is returned, but if not, I can file it with wp-cli-valet-command.

**Comment by riskiii** [comment]
This issue is fixed.

**Comment by timneutkens** [comment]
Nice! Will do a new release soon 👌
