### ISSUE TITLE
.test domains using apache's document root /Library/WebServer/Documents

### ISSUE THREAD

**Issue by rav-redchamps** [weprovide/valet-plus#480]
Just installed valet+ on Mac Catalina the foobar.test domain runs file 

/Library/WebServer/Documents/index.html

instead of ~/Sites/foobar/index.php

restarted dnsmasq, valet not sure what is causing this.

also valet paths return below

[
    "/Users/John/.valet/Sites",
    "/Users/John/sites"
]

**Comment by SanderAtom** [comment]
Hi @rav-redchamps, did you have apache or regular laravel/valet installed before? I see that directory is used when enabling the native apache (https://jasonmccreary.me/articles/install-apache-php-mysql-mac-os-x-catalina/). You can try `apachectl stop` and `valet restart`.

You can also join our Slack channel (see at the bottom of the description https://github.com/weprovide/valet-plus), that can speed up debugging what's going on.

**Comment by rav-redchamps** [comment]
@SanderAtom I didn't had larval/valet installed before. But Mac's native apache was there.

Running below command solved it

apachectl stop and valet restart

Thanks a lot for your response.

**Comment by SanderAtom** [comment]
Awesome!

**Comment by SanderAtom** [comment]
I'm closing this issue since it's resolved, if you have any other problems feel free to open a new issue.
