### ISSUE TITLE
Bug: Command "fix" is not defined. [Valet 2.0.4]

### ISSUE THREAD

**Issue by suneet64** [weprovide/valet-plus#484]
- [ ] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
As per the installation instructions, things are working till point 7 but on 8, it is throwing following error:

Command "fix" is not defined.

![Screenshot 2020-04-27 at 1 10 54 AM](https://user-images.githubusercontent.com/34968044/80317879-04dcc980-8824-11ea-8187-41743335dcd6.png)

**What was supposed to happen?**
Fix command should be available

**How to reproduce this?**
Install valet using installation instructions on macOS Catalina 10.15.4. Clean mac without any data and apps.

**Comment by dwillitzer** [comment]
@suneet64 appears our tickets #485 are the same issue. The builds tagged 2.0.X all contain the core Valet project only nothing of the Valet+ project.

**Comment by suneet64** [comment]
@dwillitzer is there any fix available or we need to wait for the next release?

**Comment by dwillitzer** [comment]
@suneet64 I am not currently a contributor, but I am looking into a fix and try issued a Pull Request; As this was affecting myself as well.

**Comment by dwillitzer** [comment]
@suneet64 this should help you https://github.com/weprovide/valet-plus/issues/485#issuecomment-619746629

**Comment by suneet64** [comment]
@dwillitzer successfully installed with this but after installation, not able to open the site in the browser. It is showing 'The site can't be reached'.

Apache is already disabled and dnsmasq is executing.

**Comment by Neodork** [comment]
@suneet64 Thanks for the report since @dwillitzer report is more in depth on the original problem, I'll close this ticket as duplicate. 

https://github.com/weprovide/valet-plus/issues/485
