### ISSUE TITLE
Bug: Valet+ features missing. Tagged releases 2.0.X contains Valet original project only

### ISSUE THREAD

**Issue by dwillitzer** [weprovide/valet-plus#485]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
After updating from 1.0.29 and preforming the preupgrade configuration all of the Valet+ features disappeared.

**What was supposed to happen?**
Expected after upgrading from 1.X to 2.X that same features would be available but not the case.

**What actually happened?**
When running `$ valet --version` the response is `Laravel Valet 2.0.4`

**How to reproduce this?**
Running the upgrade command `composer global upgrade` when currently on versions 1.x and upgrading to 2.x.

**What is the solution?**
Core code review?

**Sources**

Attempted to resolve by removing entire .composer folder and starting fresh by following valet-plus installation guide. Below is the test after completely uninstalling with [script "valet destroy"](https://gist.githubusercontent.com/dannygsmith/5b74ba708d7bf8621c1cb6b959ece99f/raw/f1b0e88ba4e0a753b112bd2187c22bf8eaa9a234/valet-plus-destroy) the current version of valet 1.0.29, rebooting, preforming fresh test installs from of versions >= 2.X.

```zsh
rm -rf .composer                                                                                       21:09:27
~ composer global require weprovide/valet-plus:2.0.0                                                     21:09:34
Changed current directory to /Users/DJ/.composer
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-php72 (v1.15.0): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.15.0): Downloading (100%)
  - Installing symfony/var-dumper (v4.4.7): Downloading (100%)
  - Installing tightenco/collect (v5.8.38): Downloading (100%)
  - Installing psr/container (1.0.0): Downloading (100%)
  - Installing php-di/invoker (2.0.0): Downloading (100%)
  - Installing symfony/service-contracts (v2.0.1): Downloading (100%)
  - Installing symfony/polyfill-php73 (v1.15.0): Downloading (100%)
  - Installing symfony/console (v4.4.7): Downloading (100%)
  - Installing mnapoli/silly (1.7.2): Downloading (100%)
  - Installing nategood/httpful (0.3.2): Downloading (100%)
  - Installing symfony/process (v3.4.39): Downloading (100%)
  - Installing symfony/translation-contracts (v2.0.1): Downloading (100%)
  - Installing symfony/translation (v5.0.7): Downloading (100%)
  - Installing nesbot/carbon (2.32.2): Downloading (100%)
  - Installing psr/simple-cache (1.0.1): Downloading (100%)
  - Installing illuminate/contracts (v5.8.36): Downloading (100%)
  - Installing doctrine/inflector (1.3.1): Downloading (100%)
  - Installing illuminate/support (v5.8.36): Downloading (100%)
  - Installing illuminate/container (v5.8.36): Downloading (100%)
  - Installing weprovide/valet-plus (v2.0.0): Downloading (100%)
symfony/service-contracts suggests installing symfony/service-implementation
symfony/console suggests installing symfony/event-dispatcher
symfony/console suggests installing symfony/lock
symfony/console suggests installing psr/log (For using the console logger)
symfony/translation suggests installing symfony/config
symfony/translation suggests installing symfony/yaml
illuminate/support suggests installing illuminate/filesystem (Required to use the composer class (5.8.*).)
illuminate/support suggests installing moontoast/math (Required to use ordered UUIDs (^1.1).)
illuminate/support suggests installing ramsey/uuid (Required to use Str::uuid() (^3.7).)
illuminate/support suggests installing vlucas/phpdotenv (Required to use the env helper (^3.3).)
Writing lock file
Generating autoload files
8 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
~ valet fix                                                                                              21:10:16
Password:

  Command "fix" is not defined.

~ valet --version                                                                                        21:11:10
Laravel Valet 2.0.0
```

**Comment by dwillitzer** [comment]
After further review when downloading any versions tagged 2.0.1, 2.0.3, 2.0.4 with the normal install method, viewing the sources appears the build compiler is not merging the projects thus releasing the starting valet package.

**Comment by dwillitzer** [comment]
My current hack workaround.

 Download the git repo tagged 2.0.0 and replace the composer project folder contents of `bin` and `cli` inside `.composer/repo/weprovide/valet-plus`.

That should get you on the right track.

**Comment by suneet64** [comment]
@dwillitzer thanks for the workaround. I just tried this but stuck with the following error during valet install.

  Could not find installation path for: apcu             
                                                         
  No releases available for package "pecl.php.net/apcu"  
  install failed                                         

![Screenshot 2020-04-27 at 12 02 45 PM](https://user-images.githubusercontent.com/34968044/80340921-228b4c80-887f-11ea-9fc5-4d2740a67a75.png)

**Comment by suneet64** [comment]
> @dwillitzer thanks for the workaround. I just tried this but stuck with the following error during valet install.
> 
> Could not find installation path for: apcu
> 
> No releases available for package "pecl.php.net/apcu"
> install failed
> 
> ![Screenshot 2020-04-27 at 12 02 45 PM](https://user-images.githubusercontent.com/34968044/80340921-228b4c80-887f-11ea-9fc5-4d2740a67a75.png)

This has been fixed by following https://github.com/weprovide/valet-plus/issues/423#issuecomment-560128117

**Comment by Neodork** [comment]
@dwillitzer Thanks for your report. Looks like some contributor merged tags from laravel/valet into weprovide/valet-plus. 

We'll look into the issue and remove the tags.

**Comment by Neodork** [comment]
Hey All,

We removed the tags. We're now waiting on a refetch of https://packagist.org/packages/weprovide/valet-plus to ensure the composer installs work correctly again. 

Thanks for the report!

Kind regards,
Lou van der Laarse

**Comment by Neodork** [comment]
Hey All,

Thanks for your patience! https://packagist.org/packages/weprovide/valet-plus has been updated and now reflects the correct tags again.

Please run `composer cc` to [clear your composer cache]( https://getcomposer.org/doc/03-cli.md#clear-cache-clearcache-cc).

Kind regards,
Neodork
