### ISSUE TITLE
Bug: valet-plus test pipeline (Azure pipelines) brew dependency error

### ISSUE THREAD

**Issue by henkrehorst** [weprovide/valet-plus#486]
- [X] I've checked the issue queue and could not find anything similar to my bug.

**What is the problem?**
In the installation step of valet-php@7.2 there is a brew dependency error because not all brew dependencies are up to date.

**How to reproduce this?**
By running the test pipeline.

**What is the solution?**
Adding a new step where brew update is running and brew php is uninstalled.

**Sources**
![image](https://user-images.githubusercontent.com/23561171/80595620-556f4500-8a25-11ea-8dab-861f397801de.png)
![image](https://user-images.githubusercontent.com/23561171/80595677-6ddf5f80-8a25-11ea-933b-93e8026788c8.png)

**Comment by Neodork** [comment]
This was merged, closing.
