### ISSUE TITLE
Configuration to access my website from my local network

### ISSUE THREAD

**Issue by Ivan-Daniel-Ortiz** [weprovide/valet-plus#488]
First of all, thanks for Valet-Plus. :-)
I have installed Valet-Plus and developed a web application with Symfony, and I access the web locally without problems.
Now I have added an API to my project and I want to access it from a mobile application on the same local network during development.
I try to access my website from the device's browser but I receive the answer: Valet could not find directory 192.168 ...
I have tried to edit file /Users/user_name/.valet/Nginx/web.test to allow access and listen to my local ip with no results.
Could you tell me how to proceed please?
Thank you.

**Comment by kozie** [comment]
I think you might want to try `valet share`. Have you tried that?

**Comment by mischabraam** [comment]
@kozie is correct. You're API is not available on the internet. You'll need the open it up for public access which can be achieved with a tool like `ngrok`. This tool is embedded in valet with the `valet share` command. See https://github.com/weprovide/valet-plus/wiki/Sharing
