### ISSUE TITLE
Valet+ found errors within the installation

### ISSUE THREAD

**Issue by amdd-tim** [weprovide/valet-plus#489]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Running `valet install` returns: "Valet+ found errors within the installation.

I've tried every update/upgrade solution possible. Now I'm just going to cry. Spent 8 hours on this with no light at the end of the tunnel. I can't get any other work done.

**What was supposed to happen?**
Better error description. I'm in a loop of diagnosis steps.

**What actually happened?**
Running `valet install` returns:

In PhpFpm.php line 428:
                                                                        
  [php] Valet+ found errors within the installation.                    
                                                                        
              run: valet fix for valet to try and resolve these errors

Running `valet fix` doesn't return anything that looks like an error, expect for maybe:

Please check your linked php version, you might need to restart your terminal!
Linked PHP should be php 7.2:
PHP 7.2.30 (cli) (built: Apr 24 2020 12:27:07) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.30, Copyright (c) 1999-2018, by Zend Technologies

**How to reproduce this?**
Run `valet fix`. Run `valet install`. Despair.

**What is the solution?**
Some guidance on how to dig into the issue. I'm a web developer and relative newb on the command line.
[valet-fix.txt](https://github.com/weprovide/valet-plus/files/4578284/valet-fix.txt)

**Sources**
See attached output of `valet fix`.

Any and all suggestions are appreciated. I will try anything. I've already attempted completely removing all PHP version and Valet+ but I'm getting the same errors as when I started. I don't know what changed in the first place to start having issues. Everything has been solid for a year plus.

**Comment by amdd-tim** [comment]
Update: now I'm getting "Fatal error: Uncaught Error: Call to undefined function apcu_fetch()".

**Comment by luancschmitz** [comment]
I am too. Error:
Call to undefined function apcu_fetch() in 
.composer/vendor/weprovide/valet-plus/server.php:51 Stack trace: #0 {main} thrown in .composer/vendor/weprovide/valet-plus/server.php on line 51

**Comment by luancschmitz** [comment]
> I am too. Error:
> Call to undefined function apcu_fetch() in
> .composer/vendor/weprovide/valet-plus/server.php:51 Stack trace: #0 {main} thrown in .composer/vendor/weprovide/valet-plus/server.php on line 51

Solved the error by installing the acpu with the following command:
**pecl install apcu_bc**

**Comment by amdd-tim** [comment]
> > I am too. Error:
> > Call to undefined function apcu_fetch() in
> > .composer/vendor/weprovide/valet-plus/server.php:51 Stack trace: #0 {main} thrown in .composer/vendor/weprovide/valet-plus/server.php on line 51
> 
> Solved the error by installing the acpu with the following command:
> **pecl install apcu_bc**

I'll try it, but I feel like I did before and it didn't work. Plus, I thought v2.0.0 we aren't supposed to be using apcu_bc, per these instructions (https://github.com/weprovide/valet-plus/blob/master/UPGRADE-2.0.md)

**Comment by luancschmitz** [comment]
> > > I am too. Error:
> > > Call to undefined function apcu_fetch() in
> > > .composer/vendor/weprovide/valet-plus/server.php:51 Stack trace: #0 {main} thrown in .composer/vendor/weprovide/valet-plus/server.php on line 51
> > 
> > 
> > Solved the error by installing the acpu with the following command:
> > **pecl install apcu_bc**
> 
> I'll try it, but I feel like I did before and it didn't work. Plus, I thought v2.0.0 we aren't supposed to be using apcu_bc, per these instructions (https://github.com/weprovide/valet-plus/blob/master/UPGRADE-2.0.md)

I found the solution on this link:
https://stackoverflow.com/questions/36129259/php7-with-apcu-call-to-undefined-function-apc-fetch

and this worked for me. Now I'm configuring the magento 2.

**Comment by amdd-tim** [comment]
`pecl install apcu_bc` fixed the "Fatal error: Uncaught Error: Call to undefined function apcu_fetch()" issue. But now I'm dealing with a Database error.

"PHP Warning:  mysqli_real_connect(): (HY000/2002): No such file or directory"

Seems like it might be related to mysql version 8?

**Comment by luancschmitz** [comment]
I have installed mysql version 5.7 here. Maybe it could be the version. Try install version 5.7 with homebrew.

**Comment by amdd-tim** [comment]
I did have mysql@5.7 installed. Just along with mysql as well. I just deleted both and I'll try reinstalling. But I'm not convinced that's the true issue. `valet install` still throws the same "In PhpFpm.php line 428: [php] Valet+ found errors within the installation. run: valet fix for valet to try and resolve these errors." And running `valet fix` doesn't seem to suggest anything except that php 7.2 might not be recognized as linked, even though I've done so many times.

**Comment by luancschmitz** [comment]
when I type ```php -v``` in terminal, this error appears:

![Captura de Tela 2020-05-04 às 22 35 50](https://user-images.githubusercontent.com/13907586/81028417-b2209480-8e57-11ea-84de-a549e5d0c84b.png)

but the operations with php cli run normally.

**Comment by amdd-tim** [comment]
I'm running Wordpress, so we may very well be having separate issues.

**Comment by amdd-tim** [comment]
Deleted all brew installs of mysql and reinstalled mysql@5.7. Then rolled valet-plus back to 1.0.27. I can get all the way through `valet install` now, except the very last line says 'Setting password for root user failed.' Oy vey.

**Comment by Neodork** [comment]
Hey all, we've released version 2.1.0 which solves `valet fix` double linking. Which is the behaviour explained in the OP. This could break installations upon installing or upgrading. Please ensure all your valet-php versions are unlinked and only link the default version as mentioned in the installation guide on the wiki, when upgrading.
