### ISSUE TITLE
Bug: <Cannot install Laravel Due to mnapoli/silly ~1.5 dependency>

### ISSUE THREAD

**Issue by Codex101** [weprovide/valet-plus#490]
**What is the problem?**
Valet plus requires "mnapoli/silly": "~1.5.0", which doesn't allow symfony/console": > ~3.0. 

But Laravel installer v3+requires 
`laravel/installer v3.0.0 requires symfony/console ^4.0|^5.0`

**What was supposed to happen?**
Update weplus/valet-plus to have a more updated version of mnapoli/silly, which allows symfony/console > 3.0

```
"require": {
        "symfony/console": "~3.0|~4.0|~5.0",
```
https://github.com/mnapoli/silly/blob/master/composer.json

**What actually happened?**
Cannot install Laravel

**How to reproduce this?**
1. Install latest weprovide/valet-plus ^2.0
2. Try and install laravel 7 by docs 
https://laravel.com/docs/7.x
`composer global require laravel/installer`
3. Receive error
```
    - Conclusion: don't install laravel/installer v3.0.1
    - Installation request for laravel/installer ^3.0 -> satisfiable by laravel/installer[v3.0.0, v3.0.1].
    - Conclusion: remove symfony/console v3.4.40
```

**What is the solution?**
Update weplus/valet-plus to have a more updated version of mnapoli/silly, which allows symfony/console > 3.0

**Sources**
https://laravel.com/docs/7.x
https://github.com/weprovide/valet-plus/blob/master/composer.json
https://github.com/mnapoli/silly/blob/master/composer.json

**Comment by allrude** [comment]
This is factually the same as [#434](https://github.com/weprovide/valet-plus/issues/434) that is clossed, I can work around but it it still a pain

**Comment by jissereitsma** [comment]
As I see it, the dependencies point out that you should be able to use `symfony/console` version 4, correct? Does a simple `composer global require symfony/console:4` work?

**Comment by Codex101** [comment]
@jissereitsma No unfortunately 

`    - Installation request for mnapoli/silly (locked at 1.5.1) -> satisfiable by mnapoli/silly[1.5.1].`

@allrude I was hoping I wouldn't need to install other stuff, but it seems that I must, thank you for pointing that out
