### ISSUE TITLE
Feature request: Open up CORS by default

### ISSUE THREAD

**Issue by royduin** [weprovide/valet-plus#493]
I've added
```
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: *');
header('Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range,Authorization,X-ReCaptcha,Store');

if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
    http_response_code(200);
    exit;
}
```
At the beginnen of the `server.php` which seems to do the trick. Handling this in the Nginx config is also possible but then we've to catch the `OPTIONS` request there for the CORS preflight requests.

**Comment by mischabraam** [comment]
I'm not a fan of implementing this in Valet+. I'd rather motivate you to figure out how to implement CORS headers into your application or nginx configuration on your production server. Adding this to Valet+ will give users questions like "it works on my dev mac, but not in production, why?". 
As an alternative you could implement this in a local valet driver.
