### ISSUE TITLE
Bug: Wrong Elasticsearch version is installed using 'valet elasticsearch install' command

### ISSUE THREAD

**Issue by actionis** [weprovide/valet-plus#494]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Cannot install Elasticsearch 6.8 with `valet elasticsearch install` as indicated in the Wiki

**What was supposed to happen?**
Elasticsearch 6.8 was supposed to be installed.

**What actually happened?**
Elasticsearch 2.4 was actually installed.

```
$ valet elasticsearch install
[libyaml] Installing
[elasticsearch@2.4] Installing
[elasticsearch@2.4] Restarting
```

**How to reproduce this?**
Run `valet elasticsearch install`

**What is the solution?**
Install Elasticsearch 6.8 as indicated in the Wiki.

**Sources**
N/A

**Comment by Leland** [comment]
Can confirm

**Comment by allrude** [comment]
I can also confirm this 'bug' and since Brew removed the version _No available formula with the name "elasticsearch@2.4"_
perhaps the 6.8 version should be added as default  to the next version of valet-plus, with 7.6 as een option since we need that for local Magento 2.4 development

**Comment by Leland** [comment]
https://github.com/weprovide/valet-plus/blob/3d34b86403044a76a3c55dd2027a83f1bd9aa050/cli/Valet/Elasticsearch.php#L66

https://github.com/weprovide/valet-plus/blob/3d34b86403044a76a3c55dd2027a83f1bd9aa050/cli/Valet/Elasticsearch.php#L20

For reference, the default ES version is indeed set to v2.4 in the code. Perhaps this should be changed to v6.8?


There's also a good bit of functionality exposed for checking if the Elasticsearch version to be installed is one of 2.4, 5.6, or 6.8 – but there's no way to install a specific ES version anywhere. Perhaps `valet elasticsearch install` should be extended to permit a version number after as well?

**Comment by alexryans** [comment]
Hi, is there a fix/workaround for this issue yet, as it seems like Valet+ is completely broken (in its current state) for all Elasticsearch installs now brew has removed v2.4. Magento 2.4.x requires v7.x, so it would be good if there's a workaround available to get this working with Valet+ until a core fix is deployed.

**Comment by elandmannEI** [comment]
> Magento 2.4.x requires v7.x, so it would be good if there's a workaround available to get this working with Valet+ until a core fix is deployed.

I'm starting a new 2.4 project and as noted that requires 7.6.x What's the direction to take, install Elasticsearch separately via Homebrew?

**Comment by mischabraam** [comment]
Fixed in 3.x-dev
