### ISSUE TITLE
Bug: Valet+ doesn't install on fresh mac system

### ISSUE THREAD

**Issue by vinayshah** [weprovide/valet-plus#495]
- [ ] I've checked the issue queue and could not find anything similar to my bug.
- [ ] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Valet+ doesn't get installed on latest MACos. It has a lot of permission issues. The system doesn't detect proper changes even some time it reports 
![image](https://user-images.githubusercontent.com/4420182/84189650-448f0600-aa9e-11ea-9713-c1d2a5740ef4.png)

![image](https://user-images.githubusercontent.com/4420182/84189678-4fe23180-aa9e-11ea-9ce3-79f8f045089c.png)
![image](https://user-images.githubusercontent.com/4420182/84189711-5c668a00-aa9e-11ea-8a72-9c31ac147256.png)

**What was supposed to happen?**
A description of what you think was supposed to happen.

**What actually happened?**
A description of what actually happened.

**How to reproduce this?**
A step by step guide on how to reproduce this issue.

**What is the solution?**
A description of the proposed solution.

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by nntoan** [comment]
+1

**Comment by joomkit** [comment]
Same here Catalina fresh install
signal 9  error as above

**Comment by alainseys** [comment]
same here Catelina clean install sign 9 error

**Comment by joomkit** [comment]
sidenote; I went back to mojave fresh install and had a couple of minor issues but much better now

**Comment by alainseys** [comment]
@joomkit thats one way to fix it ☺️

**Comment by alainseys** [comment]
the way i got it working i by doing the following:

 brew install valet-php@7.4 
brew link valet-php@7.4 --force  

lines added to zsh config:
export PATH="/usr/local/opt/valet-php@7.4/bin:$PATH"
export PATH="/usr/local/opt/valet-php@7.4/sbin:$PATH"

i dot not run valet fix since this removes php for one reason so i directly run valet install

Then i ran the elasticsearch fix :
sudo cp ~/.composer/vendor/weprovide/valet-plus/cli/stubs/elasticsearch.conf /usr/local/etc/nginx/valet/elasticsearch.conf
valet domain test

**Comment by alainseys** [comment]
@joomkit what where the issues you had ?

**Comment by joomkit** [comment]
Signal 9 error as above then Catlina switch from bash and also certificate issue - I was rebuilding my machine so quickly reverted to mojave - cowardly but practical :)

**Comment by alainseys** [comment]
@joomkit  i have gone a other road https://github.com/markshust/docker-magento a docker container that is also pretty fast

**Comment by vinayshah** [comment]
> @joomkit i have gone a other road https://github.com/markshust/docker-magento a docker container that is also pretty fast

indeed it's pretty fast but when working on multiple projects its a road blocker.

**Comment by vestman** [comment]
Same here. I guess I'll stick with Mamp or Warden for now :(.

**Comment by Neodork** [comment]
Hey everybody, we've fixed some stuff in our `valet fix` command which might cause this behaviour. Please try out version 2.1.0. Please open a new bugfix if it persist.

**Comment by vestman** [comment]
I just reinstalled valet plus after reading the text below at https://docs.shopware.com/en/shopware-platform-dev-en/system-guide/system-installation-guides/valet-plus, and it worked. But now that I read your comment about 2.1.0 I realize you have released a new version during the day!

Thanks!

> **Install Error: "The process has been signaled with signal 9"**
> This is due to valet fix uninstalling valet-php@7.2 for some reason. You can fix it by reinstalling Valet-PHP (Step 3 + 4 of "Installing Valet-PHP"). Make sure to NOT run valet fix afterwards and just proceed with valet install

**Comment by Neodork** [comment]
Thanks for the feedback, appreciate it!
