### ISSUE TITLE
Feature request: Support Elasticsearch 7.6.x

### ISSUE THREAD

**Issue by lfolco** [weprovide/valet-plus#496]
- [x] I've checked the issue queue and could not find anything similar to my feature.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`

**Why implement this feature?**  
Magento 2.4 will only support Elasticsearch 7.6.x

**Sources**
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/elasticsearch.html)

**Comment by sudhanshu-bajaj** [comment]
Hi, 

Anyone able to fix this issue ? Even when I try to install I get error. I want to use 7.6 for Magento 2.4. Any help is appreciated ?

![image](https://user-images.githubusercontent.com/5261059/88787247-2b652480-d1c6-11ea-9e70-6f7e18162109.png)

**Comment by gabealeman** [comment]
Any updates on this

**Comment by DanCarlyon** [comment]
Don't use valet to install ES
The default version it tries to install is 2.4

Best option is to `brew services list` and then uninstall all Elastic search that are in the list `brew uninstall elasticsearch`

Then do `brew install elasticsearch` and you will get the latest ES version

**Comment by amcguireweb** [comment]
> Don't use valet to install ES
> The default version it tries to install is 2.4
> 
> Best option is to `brew services list` and then uninstall all Elastic search that are in the list `brew uninstall elasticsearch`
> 
> Then do `brew install elasticsearch` and you will get the latest ES version

@DanCarlyon Does a config file need updated or is there another command to run to make Valet+ use the updated ES version? I have removed the others and installed the most recent using `brew install elasticsearch`, but it's throwing an error: **No alive nodes found in your cluster**. Curl doesn't return any active ES instances either.

**Comment by mischabraam** [comment]
In Valet+ 1.x yes it installs 2.4 as default. In 2.x this changed. Currently a PR is open to install 7.8 as default.

**Comment by mischabraam** [comment]
This is fixed in release 2.1.0
