### ISSUE TITLE
Bug:   Unable to determine linked PHP.  

### ISSUE THREAD

**Issue by itsazzad** [weprovide/valet-plus#508]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Can not switch php version

**What was supposed to happen?**
A description of what you think was supposed to happen.

**What actually happened?**
```
$ valet use 7.3
...
PHP Warning:  readlink(): No such file or directory in ~/.composer/global/weprovide/valet-plus/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 317

Warning: readlink(): No such file or directory in ~/.composer/global/weprovide/valet-plus/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 317

In PhpFpm.php line 321:
                                   
  Unable to determine linked PHP.  

```

**How to reproduce this?**
https://github.com/weprovide/valet-plus/issues/434#issuecomment-572465558

**What is the solution?**
Not sure

**Comment by alainseys** [comment]
i fixed this by installing php 5.6 until 7.4 then i linked the correct version after restarting the shell i was abble to get past this

**Comment by toanthree** [comment]
After spending some time to debug, I was able to fix this issue by doing the following steps:

1. Install PHP 7.3 manually by this command: `brew install valet-php@7.3`
2. Create a symlink for /usr/local/bin/php by this command: `ln -s /usr/local/opt/valet-php@7.3/bin/php /usr/local/bin/php`
3. Run `valet use 7.3`

Hope that it helps!

**Comment by scernisevs** [comment]
Had the same issue,

if you run `brew services list`, make sure that
valet-php@7.2 is running, and all non 'valet' php are stopped.

This was the solution for me:
```
- brew install valet-php@7.2
- brew services stop php
  [brew services stop php@7.2 / and any other options that you might have had running]
- brew services start valet-php@7.2 
- brew link --force valet-php@7.2
```
run valet :) 

also, creating a symlink for openssl might help in some cases:

` ln -s /usr/local/etc/openssl@1.1 /usr/local/etc/openssl
`

**Comment by st3phani** [comment]
I have the same issue but with `valet-php@7.4`.
<img width="397" alt="Screenshot 2021-11-25 at 00 15 52" src="https://user-images.githubusercontent.com/6755905/143319607-b7ac98ab-9e1e-4c07-91e5-96c28347cd09.png">
<img width="570" alt="Screenshot 2021-11-25 at 00 17 55" src="https://user-images.githubusercontent.com/6755905/143319782-40b1c32c-e9ac-4888-b364-d69334dcff5c.png">

**Comment by leCheveuCodeur** [comment]
You have to uninstall first Valet if existing before installing Valet +, as indicated here ([link](https://github.com/weprovide/valet-plus/wiki/Installation#laravel-valet-to-valet)).
I made the same mistake, but now it's ok.
