### ISSUE TITLE
Bug: php-fpm has multiple processes & all are hitting the ceiling at 100%

### ISSUE THREAD

**Issue by goranhorvathr** [weprovide/valet-plus#509]
This was not happening before. Valet + rapes my Macbook Pro 15 inch i7 2.6 32gig of ram with php-fpm. In the activity monitor starting from yesterday it is hitting on 5 processes 98,1 to 100% cpu usage. Do we have any info what is going on. I have not changed absolutely anything with my local environment or Macbook. I had no issues until today. Doesn't matter which project. Magento, Wordpress or etc. Im using latest upgraded version  2 of the Valet +. Do we have any insight why this might start happening?

**Comment by kamui545** [comment]
I am experiencing a similar issue, however I am using laravel/valet.
PHP-FPM is suddenly using 90-100% CPU for no reasons, even if I am not browsing my websites.
Restarting Valet solves the issue but this is the 3rd time I am experiencing it since like 2 weeks.

**Comment by Neodork** [comment]
@goranhorvathr Do you have any log files from PHP-FPM?
