### ISSUE TITLE
Elastic search head plugin

### ISSUE THREAD

**Issue by mischabraam** [weprovide/valet-plus#51]
Would be very convenient to have the Head plugin installed with ES. This makes all indexes browsable and gives much insight. Very convenient for developers.

See https://github.com/mobz/elasticsearch-head for installation notes.

After installing the head plugin you should be able to browse to http://elasticsearch.dev/_plugin/head/

**Comment by timneutkens** [comment]
Apparently there is a chrome plugin: https://chrome.google.com/webstore/detail/elasticsearch-head/ffmkiejjmecolpfloofpjologoblkegm/ which provides all features.

The elasticsearch plugin is deprecated https://github.com/mobz/elasticsearch-head#running-as-a-plugin-of-elasticsearch-deprecated

Also the module itself requires Node.js te install/run which we don't provide in Valet+. So I'd go with the chrome plugin.
