### ISSUE TITLE
Bug: PHP7.0 missing mcrypt

### ISSUE THREAD

**Issue by rafaelstz** [weprovide/valet-plus#510]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Magento 2.1 doesn't install when `mcrypt` is missing.

**What was supposed to happen?**
I think it's not installing it anymore, in the last versions it was installed.

**How to reproduce this?**
Try to install M2.1

![Screen Shot 2020-07-10 at 9 40 20 PM](https://user-images.githubusercontent.com/610598/87214009-49daad00-c2f7-11ea-8d65-d2b334f5213f.png)

**What is the solution?**
Probably reviewing the install script.

**Comment by kozie** [comment]
You need at least PHP version 7.2 for mcrypt

**Comment by Neodork** [comment]
@rafaelstz I would recommend running on PHP 7.2. We do not have a mcrypt extension for PHP versions below 7.0. You could manually install that if you have a source. 

We will not support it due to the infavorable deprecation of php.net https://www.php.net/manual/en/migration71.deprecated.php.
