### ISSUE TITLE
Bug: Magento 2 driver does not support site maps

### ISSUE THREAD

**Issue by AntonEvers** [weprovide/valet-plus#511]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
The Magento 2 driver does not support site maps

**What was supposed to happen?**
https://example.com/sitemap.xml should display the sitemap

**What actually happened?**
https://example.com/sitemap.xml displays a 404 page

**How to reproduce this?**
Host a Magento 2 site, generate a sitemap and try to visit the sitemap url.
Alternatively you could generate a random xml file called `<magento_root>/pub/sitemap.xml` and visit that.

**What is the solution?**
https://github.com/weprovide/valet-plus/pull/512

**Sources**
https://github.com/magento/magento2/pull/29171

**Comment by mischabraam** [comment]
Valet+ 3 inherits the drivers from https://github.com/laravel/valet. You can target your issue there.
