### ISSUE TITLE
cURL error 51: SSL: certificate verification failed (result: 5)

### ISSUE THREAD

**Issue by dannygsmith** [weprovide/valet-plus#52]
I am using mainwp to locally to connect to a host on the same machine, and when I do I get the following notice:

Server self connect | The HTTP response test get an error "cURL error 51: SSL: certificate verification failed (result: 5)"Not expected HTTP response body:

I have removed and resured the local hosts and still get the same issue.  I went into Keychain access and remove all of the certificates and started again.  Still no joy.

**Comment by dannygsmith** [comment]
I think the problem is that it is using SecureTransport for SSL
```
/usr/local/etc/php/7.1 $ php -i | grep "SSL Version"
SSL Version => SecureTransport
```
I have tried this so far without success:
```
composer global require weprovide/valet-plus
brew install curl --with-nghttp2
brew link curl --force
brew install php71-mcrypt
brew install php71-apcu
brew install php71-geoip
brew install php71-intl
brew install php71-opcache
brew install n98-magerun
brew install n98-magerun2
brew install --with-homebrew-curl php71
brew services start homebrew/php/php71
```
and set this in my .bash_profile before running:
```
export LDFLAGS=-L/usr/local/opt/curl/lib
export CPPFLAGS=-I/usr/local/opt/curl/include
export PKG_CONFIG_PATH=/usr/local/opt/curl/lib/pkgconfig

export PATH="/usr/local/opt/php71/bin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
```

**Comment by timneutkens** [comment]
Closing cause of inactivity 👍
