### ISSUE TITLE
Bug: Chrome dropped SHA1 support

### ISSUE THREAD

**Issue by stormbyte** [weprovide/valet-plus#520]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.0.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
After 11 years chrome has really dropped support for SHA1 certifacates.

**What was supposed to happen?**
The secure sites should be secure

**What actually happened?**
The secure sites are no longer secure.

**How to reproduce this?**
run the `valet secure` command and open chrome browser.

**What is the solution?**
Use SHA265

**Sources**
https://www.chromium.org/Home/chromium-security/education/tls/sha-1

**Comment by Neodork** [comment]
@stormbyte Thanks for your PR! I've rerun the Ci/CD after merging the required bugfixes. Can you please elaborate on the method you used (mkcert). And why generating new certificates isn't possible anymore with just the openssl binary?

**Comment by stormbyte** [comment]
@Neodork I might be missing the question as I don't see the previous comment.
Openssl should support sha256 
https://www.openssl.org/docs/man1.0.2/man3/SHA256.html
