### ISSUE TITLE
Bug: Valet command not working

### ISSUE THREAD

**Issue by Mitchelvdh** [weprovide/valet-plus#525]
Currently using Valet+ for a while on a recently installed MacOS. Yesterday I opened terminal and discovered the Valet command doesn't work anymore (it did).

I get the following output with every single valet command I try to use (global and in project folder):
![image](https://user-images.githubusercontent.com/34155449/93461770-89200e00-f8e5-11ea-8a7d-68eef13ad6f1.png)

**What I tried:**
- I tried to do a `composer global update`, but left hanging on ''Something's changed, looking at all rules again (pass #85)''
- `Brew update`

Anyone might be able to help? Help much appreciated!

**Comment by Neodork** [comment]
@Mitchelvdh We've released version 2.1.0. Can you check if that resolves your problem. We've added a .lock file which should prevent such issues in the future.
