### ISSUE TITLE
Poll: Deprecate PHP 5.6

### ISSUE THREAD

**Issue by Neodork** [weprovide/valet-plus#526]
**What is the problem?**
PHP 5.6 has been end of life for a while now. This created non-BC issues on the application and PHP (brew formula) side. 

**What was supposed to happen?**
We want to deprecate PHP 5.6 from Valet+. But we would also like to get feedback from the Valet+ community to measure usage.

# How often do you switch to PHP 5.6?
[![](https://api.gh-polls.com/poll/01EJRBVZX3SCWRAKZDRM8WJ32R/I've%20used%20PHP%205.6%20in%20the%20last%20week)](https://api.gh-polls.com/poll/01EJRBVZX3SCWRAKZDRM8WJ32R/I've%20used%20PHP%205.6%20in%20the%20last%20week/vote)
[![](https://api.gh-polls.com/poll/01EJRBVZX3SCWRAKZDRM8WJ32R/I've%20used%20PHP%205.6%20somewhere%20in%20the%20last%20two%20weeks)](https://api.gh-polls.com/poll/01EJRBVZX3SCWRAKZDRM8WJ32R/I've%20used%20PHP%205.6%20somewhere%20in%20the%20last%20two%20weeks/vote)
[![](https://api.gh-polls.com/poll/01EJRBVZX3SCWRAKZDRM8WJ32R/I've%20used%20PHP%205.6%20somewhere%20in%20the%20last%20month)](https://api.gh-polls.com/poll/01EJRBVZX3SCWRAKZDRM8WJ32R/I've%20used%20PHP%205.6%20somewhere%20in%20the%20last%20month/vote)
[![](https://api.gh-polls.com/poll/01EJRBVZX3SCWRAKZDRM8WJ32R/I%20don't%20use%20PHP%205.6%20anymore)](https://api.gh-polls.com/poll/01EJRBVZX3SCWRAKZDRM8WJ32R/I%20don't%20use%20PHP%205.6%20anymore/vote)

**Comment by ChristopherDosin** [comment]
I switched to 5.6 today because i needed it to migrate an old project.

Now i can't switch back to 7.1 - Any idea how to solve this issue?
```
valet use 7.1   
PHP Parse error:  syntax error, unexpected ':', expecting '{' in /Users/christopherdosin/.composer/vendor/symfony/deprecation-contracts/function.php on line 23
```

**Comment by zcuric** [comment]
I say deprecate all [EOL PHP versions](https://www.php.net/supported-versions.php).

**Comment by joomkit** [comment]
I still want it for the odd legacy project waiting for funding before upgrade -but yeah it should go really

**Comment by phlbnks** [comment]
I'm keen to see it go - like @zcuric I think mapping to PHP lifespans makes sense and keeps it predictable.

**Comment by GrimLink** [comment]
Yes please!

**Comment by joostvanveen** [comment]
+1 for keeping 5.6 as long as possible. In theory, it is wise to ditch support for EOL versions. In practise, a lot of us have legacy projects to look after.

**Comment by mischabraam** [comment]
Support for php <7.1 will be dropped in 2.4.0-beta releases.

**Comment by pryley** [comment]
If people still need to use PHP 5.6, consider using [Local](https://localwp.com/) for those rare cases.
