### ISSUE TITLE
Why PHP 7.0?

### ISSUE THREAD

**Issue by yhoiseth** [weprovide/valet-plus#54]
First of all, thanks a lot for making and open sourcing Valet Plus.

In [the installation instructions](https://github.com/weprovide/valet-plus/blob/master/readme.md#installation), step 2 says

> Install PHP 7.0 using Homebrew via `brew install homebrew/php/php70`.

I used PHP 7.1 instead, and it seems to work fine. I'm curious, why does the documentation specify PHP 7.0?

**Comment by timneutkens** [comment]
It'll even work if you install PHP 5.6 😄 This is mostly cause we're doing Magento development and Magento doesn't support 7.1. So we'd first install php 7.1 to then always switch to 7.0, so it's there for convience 👌
