### ISSUE TITLE
Bug: CI/CD has no test cases for nginx

### ISSUE THREAD

**Issue by Neodork** [weprovide/valet-plus#543]
- [X] I've checked the issue queue and could not find anything similar to my bug.
- [X] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [X] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Nginx is never checked in the CI/CD and the state upon installation is unknown.

**What was supposed to happen?**
Checks should check whether Nginx is running correctly after the installation.

**What actually happened?**
Nothing, there are no check and nginx likely didn't start correctly.

**How to reproduce this?**
Run the CI/CD and observe. Local installs also show this behaviour of faulthy nginx.

**What is the solution?**
Implement test cases.

**Comment by mischabraam** [comment]
Nginx is a Laravel Valet core feature and adopted directly in Valet+ 3 making it responsible for Laravel Valet to test.
