### ISSUE TITLE
Bug: Xdebug version

### ISSUE THREAD

**Issue by chedaroo** [weprovide/valet-plus#548]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
A description of what you think the problem is.

Breaking changes in Xdebug 3 cause issues within Valet and with Magento

**What was supposed to happen?**
A description of what you think was supposed to happen.

Valet should install xdebug 2 until Magento supports xdebug

**What actually happened?**
A description of what actually happened.

Valet installs Xdebug 3 as this is now stable channel

**How to reproduce this?**
A step by step guide on how to reproduce this issue.

Enable xdebug (uninstall first if already installed)

`valet xdebug on`

**What is the solution?**
A description of the proposed solution.

Fix version of Xdebug to 2

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by kozie** [comment]
At first it thought this is just an issue with your editor. Apart from the fact that the configuration which valet generates in php.ini aren't valid anymore, Magento indeed doesn't seem to be compatible with xDebug3. It's framework ois relying on some built in functions unfortunately.

For now i removed xDebug and installed the old one manually using `pecl install xdebug-2.9.8` which seems to work fine here

**Comment by chedaroo** [comment]
@kozie Yeah, there's a bunch functions missing, manually downgrading worked for me too.

I submitted a pull request to downgrade as I can't see Magento addressing this anytime soon. However, it looks like I have some how made a dogs dinner of it, will have another look

**Comment by ityetti** [comment]
@kozie @chedaroo 
I added compatibility for xDebug 3.x and PHP7.x
For example M2.3.x (valet-php@7.2 (7.2.34) and xDebug (v3.0.2) work correct without any problems).

**Comment by ityetti** [comment]
@kozie Which problems did you have with Magento and xDebug 3?

**Comment by kozie** [comment]
@ityetti I don't anymore but some vendor files from Magento are using a couple of functions provided by xDebug which were deleted from version 3.

**Comment by ityetti** [comment]
@kozie Ok, thank you. I hope that it was some old magento version)

**Comment by chedaroo** [comment]
FYI on this one I think it was MFTF that had problems with xdebug 3. Looks like the issue may have been fixed in that module here https://github.com/magento/magento2-functional-testing-framework/issues/808 but like I said before, can’t seen that landing in core anytime soon, is that a good enough reason to support both 2 and 3?

**Comment by ityetti** [comment]
@chedaroo Yeah, you are right. I forgot that I modified magento2-functional-testing-framework for correct work with xDebug 3. Yeah support both 2 and 3 would be great solution)

**Comment by mischabraam** [comment]
valet-plus:3-dev has this fixed. It uses the Xdebug version compatible with the used php version (through shivamathur).
