### ISSUE TITLE
Bug: Wrong elasticsearch version installed (mixed 7.10.1 with 6.8)

### ISSUE THREAD

**Issue by pawel-snowdog** [weprovide/valet-plus#551]
- [X] I've checked the issue queue and could not find anything similar to my bug.
- [X] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [X] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I'm trying to use elasticsearch in version 6.8 for Magento2 < 2.3.5. After `valet elasticsearch install` version 7.10.1 was installed, so I wanted to switch to 6.8 by running `valet use es 6.8`.
The 6.8 version was installed successfully, but when running `curl "localhost:9200/_nodes/settings?pretty=true"` the result shows that version 7.10.1 is now mixed with 6.8:
```
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "elasticsearch_brew",
  "nodes" : {
    "ga0oBjhRReGcUYio8YA0Zw" : {
      "name" : "MBP-Pawel.Dlink",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1",
      "version" : "7.10.1",
      "build_flavor" : "oss",
      "build_type" : "tar",
      "build_hash" : "unknown",
      "roles" : [
        "data",
        "ingest",
        "master",
        "remote_cluster_client"
      ],
      "settings" : {
        "client" : {
          "type" : "node"
        },
        "cluster" : {
          "name" : "elasticsearch_brew"
        },
        "http" : {
          "type" : {
            "default" : "netty4"
          }
        },
        "node" : {
          "name" : "MBP-Pawel.Dlink"
        },
        "path" : {
          "data" : [
            "/usr/local/var/elasticsearch@6.8"
          ],
          "logs" : "/usr/local/var/log/elasticsearch",
          "home" : "/usr/local/Cellar/elasticsearch/7.10.1/libexec"
        },
        "transport" : {
          "type" : {
            "default" : "netty4"
          }
        }
      }
    }
  }
}
```
Reindex process in Magento 2 shows error typical to wrong version of elasticsearch:

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"In Shingle TokenFilter the difference between max_shingle_size and min_shingle_size (and +1 if outputting unigrams) must be less than or equal to: [3] but was [9]. This limit can be set by changing the [index.max_shingle_diff] index level setting."}],"type":"illegal_argument_exception","reason":"In Shingle TokenFilter the difference between max_shingle_size and min_shingle_size (and +1 if outputting unigrams) must be less than or equal to: [3] but was [9]. This limit can be set by changing the [index.max_shingle_diff] index level setting."},"status":400}
```

**What was supposed to happen?**
Elasticsearch should work in 6.8 version not 7.10.1

**How to reproduce this?**
- install valet-plus (clean MacOS Big Sur)
- run `valet elasticsearch install`
- run `valet use es 6.8`

**Comment by mischabraam** [comment]
Known issue indeed. Valet has const's declared for versions, but the default versions in Brew change periodically. The 6.8 and 7.x issue has been fixed in version 2.1. In this version you can switch to 7.x using `valet use es 7.6`.
I recommend removing your current Elasticsearch instances, upgrade Valet+ to 2.1 and then `valet use es 7.6`. Hope that helps.
