### ISSUE TITLE
Bug: Brew 2.7.0 release incompatible with Valet Plus do to removal of deprecated "brew list" without arguments

### ISSUE THREAD

**Issue by peterkeijsers** [weprovide/valet-plus#553]
**What is the problem?**
The recent Brew v2.7.0 release removed a deprecated: "brew list" without arguments. This method is used by Valet for determining which formula are installed. Upgrading to brew 2.7.0 results in not being able te start/restart or install valet services at all.

**Sources**
https://github.com/Homebrew/brew/pull/9357
https://github.com/Homebrew/brew/releases/tag/2.7.0

**pullrequest**
https://github.com/weprovide/valet-plus/pull/554

**Comment by jvanschelven** [comment]
:+1: plus 1. after upgrading to brew 2.7.0 and trying to install php 7.4 and switching between 7.2 and 7.4 valet only restarts MySQL and not all other services resulting in setup thats not working.

**Comment by peterkeijsers** [comment]
> 👍 plus 1. after upgrading to brew 2.7.0 and trying to install php 7.4 and switching between 7.2 and 7.4 valet only restarts MySQL and not all other services resulting in setup thats not working.

See my pullrequest in de original issue description for a fix

**Comment by joostvanveen** [comment]
👍 plus 1. Can confirm the fix works.

**Comment by Neodork** [comment]
Merged. Will be in next release once the other issues are solved. Thanks for your report.
