### ISSUE TITLE
Bug: incoming request site / host parsing issue with port numbers

### ISSUE THREAD

**Issue by jeroenkosse** [weprovide/valet-plus#556]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When the server.php is parsing the $_SERVER['HTTP_HOST'] to extract the siteName the only suffix that is removed from the url is the $valetConfig['domain']. When i visit the host with a specific port name defined the $valetConfig['domain'] is not stripped from the $siteName and the path could no longer be found.

**What was supposed to happen?**
When for example I wanna visit localhost.test:8080 this should set the $siteName to localhost. 

**What actually happened?**
The $siteName has the value localhost.test:8080

**How to reproduce this?**
Use a url with a specific port number and check the $siteName in the server.php file and this is now different from the url without the port number.

**What is the solution?**
Before the basename function is called remove the port number from the specific $_SERVER['HTTP_HOST'] so the url always ends with the $valetConfig['domain'] in the end.

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

I found the bug when enabling Varnish and the backend url is set to 8080. This is not correctly routed to the selected siteName in the url so varnish cannot be properly enabled when using the current version of valet without changes the siteName extraction in the server.php

**Comment by mischabraam** [comment]
@jeroenkosse Is this still an issue? I can't reproduce this.
