### ISSUE TITLE
Bug: Valet Secure Not Working

### ISSUE THREAD

**Issue by zensabbah** [weprovide/valet-plus#557]
- [ ] I've checked the issue queue and could not find anything similar to my bug.
- [ ] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I download phpMyAdmin under "Sites" folder and it works at http://phpMyAdmin.test
I tried valet secure phpMyAdmin and I receive this message:
"The [phpMyAdmin.test] site has been secured with a fresh TLS certificate."

**What was supposed to happen?**
looking for https://phpMyAdmin.test

**What actually happened?**
https://phpMyAdmin.test is not reachable

**Comment by thaikolja** [comment]
Try to narrow the bug down by creating another folder, e.g. `~/Sites/secure`, `cd` into the new directory and use `valet link` and then `valet secure`. You should then see a prompt for your administrator password. Enter it, wait until valet has restarted, and then check if you can access that new folder via `https://secure.test`. Don't forget to place an `index.html` or `index.php` inside the folder with some text in it.

The result of this will give us important information where we should continue to look.

**Comment by jdperezdev** [comment]
Hey, I have the same problem, There are news with respect this issue?

@zensabbah has you can solved the problem?

Thanks!

**Comment by zensabbah** [comment]
I don't remember bro, probably not sorry!

**Comment by mischabraam** [comment]
Solved moving to Valet+ 3 (which adopts this directly from Laravel's Valet).
