### ISSUE TITLE
macOS Big Sur compatibility

### ISSUE THREAD

**Issue by omolto** [weprovide/valet-plus#566]
Hi folks,

I'm trying to install valet-plus to a new fresh MacBook with BigSur and I can't stop finding problems...

The default php version installed on Big Sur is 7.3. I know I need valet-php@7.2 to install valet-plus, so installed the lower version with "brew install valet-php@7.2".

After it I can't run valet fix because the error "Unable to determine linked PHP." which is trying to find "/usr/local/bin/php" that no exists because nobody created it. Ok, I created the symlink manually.

After it I can't run valet fix because when "Checking pear config" doesn't find any of the versions. Do I have to create the symlinks also manually?

Will I find more problems after doing so much manual steps?

Valet-plus is supposed to be the "Blazing fast macOS PHP development environment". It should work perfectly. I have been using it on old MacBooks but actually I feel like I was a kid playing with Windows and Internet Explorer...

When will valet-plus will be compatibility with Big Sur? May we help?

Thanks,

**Comment by philiprabbett** [comment]
Valet+ has been broke for some time on that front regarding PHP versions and PECL, I think a few other issues are to happen after but once sorted, it works

**Comment by Adam2Marsh** [comment]
Hi @philiprabbett 

Don't worry I had the exact same issues, I assume you've installed brew into /opt as recommended? if so valet plus currently has a bunch of hard coded paths which causes issues. I've working on a pull request but hit a stumbling block. More info is on the linked ticket #568

**Comment by mischabraam** [comment]
I'm on Monterey, which works fine. Still an issue? Of not, you may close this issue.
