### ISSUE TITLE
Feature request: MySQL 8 Support

### ISSUE THREAD

**Issue by christopherholst** [weprovide/valet-plus#567]
- [x] I've checked the issue queue and could not find anything similar to my feature.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.1.0`

**Why implement this feature?**  
More applications already work with MySQL 8, but it is currently not possible to use it to locally fix errors in the application.

**Comment by thaikolja** [comment]
I second this.

**Comment by elandmannEI** [comment]
Needing this now to work on Magento 2.4.5

**Comment by thaikolja** [comment]
@elandmannEI: Like so many others, I've also given up on valet-plus. I loved it when I started out with It, but installing it is such a hassle, so many times I had to uninstall and reinstall it again for some strange reason. The missing support for PHP 8 and other tools was the straw that broke the camel's back. The standard [Laravel Valet](https://laravel.com/docs/8.x/valet#installation) is more than sufficient and works great with any custom environment. You should consider migrating.

**Comment by mischabraam** [comment]
Released in [2.3.0](https://github.com/weprovide/valet-plus/releases/tag/2.3.0)

**Comment by christopherholst** [comment]
@mischabraam nice, but how to use? i didnt find how can i switch or install mysql8 ?

**Comment by mischabraam** [comment]
You can use 
- `valet install`
- `valet install --with-mariadb` 
- `valet install --with-mysql-8`
