### ISSUE TITLE
Bug: Can't set up new sites after install

### ISSUE THREAD

**Issue by robertkent87** [weprovide/valet-plus#569]
- [✅ ] I've checked the issue queue and could not find anything similar to my bug.
- [✅ ] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.1.0`
- [✅ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I can't create a new site. I've just installed valet plus but ping is failing

➜ valet links
+-----------------+-----+------------------------+----------------------------------------+
| Site            | SSL | URL                    | Path                                   |
+-----------------+-----+------------------------+----------------------------------------+
| mf_website.test |     | http://mf_website.test | /Users/rkent05/Projects/mf_website/web |
+-----------------+-----+------------------------+----------------------------------------+

➜ ping mf_website.test
ping: cannot resolve mf_website.test: Unknown host

**Comment by thaikolja** [comment]
Do you use any custom DNS server IPs in your Network settings, like CloudFlare's or Google's? The left panel should be empty:

![DNS IPs](https://user-images.githubusercontent.com/37884870/114199931-0334e480-9955-11eb-96e3-40bfffa82450.png)

If not, are you using any VPN? Both the custom DNS IP and using a VPN had caused _valet_ to not work in the past, so it's worth looking into it.

**Comment by jornwildenbeest** [comment]
Same problem here

**Comment by mischabraam** [comment]
Did you `valet park` in `/Users/rkent05/Projects`? You won't be needing to create a link if the URL you want to use is the same as your directory name inside your parked directory.
So, if you parked in `/Users/bla/Projects` and have a directory named `funkysite`. The URL `http://funkysite.test` should be available without making a link to it. If you want to use `http://notsofunkysite.test` on the same directory, then create a link for that domain.

Besides that, not resolving might indicate an dnsmasq error. Can you check the logs?
