### ISSUE TITLE
Bug: Cannot switch to PHP 7.1 or below successfully after a fresh Valet install

### ISSUE THREAD

**Issue by alexryans** [weprovide/valet-plus#571]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
After running `valet use 7.1`, or switching to any PHP version lower than 7.2, Valet breaks.

**What was supposed to happen?**
Valet should switch to PHP 7.1 successfully and be able to run all `valet` commands.

**What actually happened?**
After running `valet use 7.1` on a fresh install of Valet on macOS Big Sur, the command line returns `PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.2.0". You are running 7.1.33. in /Users/alexryans/.composer/vendor/composer/platform_check.php on line 24`. This issue persists when running any further `valet` command, making it impossible to switch to any other version of PHP other than running `brew link valet-php@7.2 --force`. Originally, I was running Composer v2, but the issue persisted after running `composer self-update --1` to switch to Composer v1.

Have attempted to turn off global Composer platform checks using `composer global config platform-check false`, but this also didn't prevent the issue. Also attempted to delete global Composer vendor file from `~/.composer` and run `composer global dump-autoload`, but this also had no effect.

**How to reproduce this?**
- Install Valet as per the official installation instructions.
- Run `valet use 7.1`
- Attempt to switch back to PHP 7.2 (or above) using `valet use 7.2`

**Comment by clnt** [comment]
@alexryans I believe this has come about since version 2.1.

The workaround fix I found for this is just the following when switching back from 7.1:

```
brew unlink valet-php@7.1 && brew link valet-php@7.3
sudo brew services stop valet-php@7.1
valet restart
```

That should put it back on PHP 7.3, reboot if still having issues
