### ISSUE TITLE
Bug: SSL certificates aren't accepted in Google Chrome Canary

### ISSUE THREAD

**Issue by thaikolja** [weprovide/valet-plus#574]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.1.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When securing a local website with `valet secure`, the process completes without errors but when accessing the site itself with **Google Chrome Canary** (current version: `92.0.4486.0`) it says "Not secure" and "Invalid certificate". I've tried trusting it manually, but that didn't help either.

**What was supposed to happen?**
Adding an SSL certificate and being able to access valet pages through `https://`.

**What actually happened?**
The certificate was deemed "invalid" and hence the site "unsafe".

**How to reproduce this?**
1. [Download](https://www.google.com/chrome/canary/), install and start Google Chrome Canary
2. `cd` into a website that you'd like secure, e.g. a WordPress site (`cd ~/Sites/wordpress`)
3. Run `valet secure` which will prompt for your password
4. Enter your administrator password and let the services restart
5. Now access the supposedly secured site with Chrome Canary and see the SSL warnings

**What is the solution?**
I have no idea. It works well in the original Google CHrome browser, though.

**Sources**
- Google Chrome Canary

**Comment by drazulay** [comment]
Does the `thisisunsafe` command in the tab not work?

**Comment by davekleijn** [comment]
I have the same problem in the official Chrome build. Version 107.0.5304.87.

**Comment by lfolco** [comment]
> I have the same problem in the official Chrome build. Version 107.0.5304.87.

Same here, just started happening.

**Comment by lfolco** [comment]
This PR fixes it: https://github.com/weprovide/valet-plus/pull/522/files
