### ISSUE TITLE
Bug: Installation Impossible (403)

### ISSUE THREAD

**Issue by MokDevelopment** [weprovide/valet-plus#575]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When trying to install Valet+ via "brew install valet-php@7.2" or any other version (7.3, 7.4) the download of the file 
**https://dl.bintray.com/henkrehorst/valet-php/valet-php407.4-7.4.16.catalina.bottle.tar.gz**
stops the command in the terminal.

**What was supposed to happen?**
Installation of Valet as documented in GitHub.

**What actually happened?**
**https://dl.bintray.com/henkrehorst/valet-php/valet-php407.4-7.4.16.catalina.bottle.tar.gz**
The file request seems to return a 403 (no permission).
We tested it on 4 different OSX systems (Catalina, Big Sur). 

**How to reproduce this?**
Installation of Valet as documented in GitHub.

**What is the solution?**
Check permissions:
**https://dl.bintray.com/henkrehorst/valet-php/valet-php407.4-7.4.16.catalina.bottle.tar.gz**

**Comment by Fgruntjes** [comment]
I think that we need to find an alternative for bintray
![image](https://user-images.githubusercontent.com/984466/116887887-1a50b480-ac2b-11eb-83c1-21ae37ee276b.png)

**Comment by ndthanhcom** [comment]
i'm also having same issue :(

**Comment by rensieeee** [comment]
@ndthanhnet As a temporary fix you can build from source:

`brew install valet-php@x.x --build-from-source`
`brew link valet-php@x.x --force --overwrite`

**Comment by ndthanhcom** [comment]
hi @rensieeee it worked ! thank you very much !

**Comment by manugentoo** [comment]
> @ndthanhnet As a temporary fix you can build from source:
> 
> `brew install valet-php@x.x --build-from-source`
> `brew link valet-php@x.x --force --overwrite`

@rensieeee internet is full of genius people like you! that worked cheers man!

**Comment by drazulay** [comment]
> I think that we need to find an alternative for bintray
> ![image](https://user-images.githubusercontent.com/984466/116887887-1a50b480-ac2b-11eb-83c1-21ae37ee276b.png)

It appears Nixpkgs is getting better and better.. perhaps a worthy alternative (for homebrew in general)? It has some fancy dependency handling magic and seems pretty solid to me. Bit of a brain**** to get to know though.

https://blog.errright.com/switching-from-homebrew-to-nix/

**Comment by darthsteven** [comment]
> I think that we need to find an alternative for bintray
> ![image](https://user-images.githubusercontent.com/984466/116887887-1a50b480-ac2b-11eb-83c1-21ae37ee276b.png)

Homebrew itself has moved to github packages, as it's free for public repos, is that an option for valet-plus?

**Comment by mischabraam** [comment]
Valet `2.2.1` has `--build-fromsource` added to switch and install command.
