### ISSUE TITLE
Failed to download resource "valet-php@7.2"

### ISSUE THREAD

**Issue by chriskch** [weprovide/valet-plus#577]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [ ] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
I try to install valet-php@7.2 but it does not work. I have already tried `rm /usr/local/bin/2to3` [#558](https://github.com/weprovide/valet-plus/issues/558)

**What was supposed to happen?**
During installation: `brew install valet-php@7.2` this is what comes out:
`curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "valet-php@7.2"
Download failed: https://dl.bintray.com/henkrehorst/valet-php/valet-php%407.2-7.2.34_4.sierra.bottle.tar.gz`

**What actually happened?**
The requested URL returned error: 403 Forbidden

**How to reproduce this?**
Trying to install it.

**What is the solution?**
I don't know

**Sources**

**Comment by sebfie** [comment]
Also got this

**Comment by EtienneDutour** [comment]
brew install valet-php@7.x --build-from-source

**Comment by schalkneethling** [comment]
Also, see https://github.com/weprovide/valet-plus/issues/575

**Comment by chriskch** [comment]
> brew install [valet-php@7.x](mailto:valet-php@7.x) --build-from-source

Thank u ! That works for me

**Comment by matthewswallace** [comment]
> brew install [valet-php@7.x](mailto:valet-php@7.x) --build-from-source

This should be added to the install guide.
