### ISSUE TITLE
Bug: PHP 7.4.16 not working with Magento 2 

### ISSUE THREAD

**Issue by JoostWan** [weprovide/valet-plus#578]
**What is the problem?**
Magento 2 styling is not working with latest Valet version and PHP 7.4.16. It was working on 7.4.15

**What was supposed to happen?**
Magento 2 is loaded

**What actually happened?**
Styling files are not loaded and added to head

**Comment by cagartner** [comment]
I had the same problem, almost sure that is related to this PHP version.

**Comment by JoostWan** [comment]
Tested also with `7.4.20` but same problem as `7.4.16`. 

For now downgraded to `7.4.15` and it's working. You can install `7.4.15` this way.

1. Download this file https://github.com/henkrehorst/homebrew-php/blob/update/7.4.15%401612441806/Formula/valet-php@7.4.rb to your local machine.
2. Rename it to `valet-php@7.4.rb`
3. Run `brew install valet-php@7.4.rb --build-from-source`

**Comment by nathanjosiah** [comment]
For those of you that the above solution didn't work, try setting `pcre.jit=0` in your php.ini. The regex for file inclusion in the layout engine breaks if this setting is on. It was on by default for me when I upgraded to 7.4.20.

(specifically https://github.com/magento/magento2/blob/a31f4a35c018ad09654e5bd5871086b73fbd3d2d/lib/internal/Magento/Framework/View/File/Collector/ThemeModular.php#L90)

**Comment by henkvalk** [comment]
> Tested also with `7.4.20` but same problem as `7.4.16`.
> 
> For now downgraded to `7.4.15` and it's working. You can install `7.4.15` this way.
> 
> 1. Download this file https://github.com/henkrehorst/homebrew-php/blob/update/7.4.15%401612441806/Formula/valet-php@7.4.rb to your local machine.
> 2. Rename it to `valet-php@7.4.rb`
> 3. Run `brew install valet-php@7.4.rb --build-from-source`

Hi @JoostWan 

I tried, but receive following error
```
Error: valet-php@7.4: Calling `sha256 "digest" => :tag` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.

```

**Comment by henkvalk** [comment]
My mistake lol... 
```
wget https://raw.githubusercontent.com/henkrehorst/homebrew-php/update/7.4.15%401612441806/Formula/valet-php%407.4.rb
```

**Comment by patricksteenks** [comment]
@henkvalk did you try running `brew style --fix valet-php@7.4` on the file? That fixes the error for me.

**Comment by henkvalk** [comment]
@patricksteenks It is already fixed

**Comment by patricksteenks** [comment]
Yes, I understand, but for future reference it may be helpful :)
