### ISSUE TITLE
Issue with openldap by valet-php after update on macOS Big Sur 11.4 (20F71)

### ISSUE THREAD

**Issue by heyfets** [weprovide/valet-plus#579]
After installing valet-php@72 / valet-php@73 valet-php@74 I get an error and cannot work via valet-plus:
`dyld: Library not loaded: /usr/local/opt/openldap/lib/libldap-2.4.2.dylib
  Referenced from: /usr/local/opt/valet-php@7.2/bin/php
  Reason: image not found
`
I also noticed that the version of the openldap I have is 2.5.5.  
Perhaps need to update the version of this library in valet or how can be solved this problem?
Thanks!

**Comment by lezcanosaraa** [comment]
try
```
brew unlink valet-php@7.2 && brew link --force valet-php@7.2
```
then
```
brew reinstall valet-php@7.x --build-from-source
```

Good luck
