### ISSUE TITLE
valet db ls throwing an error in Filesystem.php line 258 as a result of last pr

### ISSUE THREAD

**Issue by dannygsmith** [weprovide/valet-plus#58]
This is an issue caused by the last pr, on ~/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php line 200, it is calling `$this->chown($to, user());` and getting the empty string.  I am not sure which user to default to here.

**Comment by timneutkens** [comment]
I'm thinking this is related to something missing in your installation. The current user should always be there

**Comment by timneutkens** [comment]
Fixed
