### ISSUE TITLE
Bug: PHP 7.4 has no ioncube support

### ISSUE THREAD

**Issue by LexKoomen** [weprovide/valet-plus#582]
- [X] I've checked the issue queue and could not find anything similar to my bug.
- [X] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [X] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
There is currently no support for ioncube in PHP 7.4. Whenever you try to enable ioncube with ```valet ioncube on``` while on PHP 7.4 you get an error message: 

```
[PECL-CUSTOM] Ioncube loader not found, installing...
[PECL-CUSTOM] ioncube_loader_dar is not available for PHP 7.4.
```

**What was supposed to happen?**
The latest version was supposed to download but was never configured in the PeclCustom.
In this thread (https://forum.ioncube.com/viewtopic.php?t=4587&sid=1ec889c38e508ec989569fd9914cb3fe) the thread states that the packages went from 'dar' to 'mac' files so that needed to be changed aswell.

**What actually happened?**
Error occured that package couldnt be found.

**How to reproduce this?**
```
valet use 7.4
valet ioncube on
```

**What is the solution?**
Add a 7.4 node in the installation proces and instead of downloading from the dar archive, download from the mac archive instead.

**Sources**
https://forum.ioncube.com/viewtopic.php?t=4587&sid=1ec889c38e508ec989569fd9914cb3fe

**Comment by mischabraam** [comment]
This is fixed in `2.2.1`
