### ISSUE TITLE
Error in Readme example

### ISSUE THREAD

**Issue by timothyjensen** [weprovide/valet-plus#59]
In general the Readme is excellent.  I found one typo, however that is a quick fix.

Where it reads:

3. `echo "<?php echo 'Valet+ at your service'" > index.php`

It should read

3. `echo "<?php echo 'Valet+ at your service';" > index.php`

The only difference is the semicolon after `service'`.

As it is now, the command results in a PHP error.

**Comment by timneutkens** [comment]
@timothyjensen good catch! Fixing right now 😄
