### ISSUE TITLE
Bug: valet logs {service} - Non-static method Valet\Architecture::getBrewPath() should not be called statically

### ISSUE THREAD

**Issue by osrecio** [weprovide/valet-plus#592]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.3.0`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When the command: valet logs {service} fails

**What was supposed to happen?**
Should open the log of {service} declared

**What actually happened?**
PHP Errror:
```
PHP Deprecated:  Non-static method Valet\Architecture::getBrewPath() should not be called statically in /Users/osrecio/.composer/vendor/weprovide/valet-plus/cli/valet.php on line 945
```
**How to reproduce this?**
valet logs nginx

**What is the solution?**
in file: [valet.php: ~945](https://github.com/weprovide/valet-plus/blob/2.x/cli/valet.php#L943-L950)
```php
        $brewPath = Architecture::getBrewPath();
        $logs = [
            'php' => '$HOME/.valet/Log/php.log',
            'php-fpm' => $brewPath . '/var/log/php-fpm.log',
            'nginx' => '$HOME/.valet/Log/nginx-error.log',
            'mysql' => '$HOME/.valet/Log/mysql.log',
            'mailhog' => $brewPath . '/var/log/mailhog.log',
            'redis' => $brewPath . '/var/log/redis.log',
        ];
```
**Sources**
[valet.php: ~945](https://github.com/weprovide/valet-plus/blob/2.x/cli/valet.php#L943-L950)

**Comment by mischabraam** [comment]
Released in [2.3.1](https://github.com/weprovide/valet-plus/releases/tag/2.3.1)
