### ISSUE TITLE
Bug: ElasticSearch cannot be installed on Mac Silicone (M1 Chip CPU, new Mac devices)

### ISSUE THREAD

**Issue by christopherholst** [weprovide/valet-plus#597]
- [ ] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.3.0`
- [ ] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
A description of what you think the problem is.
ElasticSearch cannot be installed on Mac Silicone.

**What was supposed to happen?**
A description of what you think was supposed to happen.
ElasticSearch installation for valet on Mac Silicone.

**What actually happened?**
A description of what actually happened.
````
[libyaml] Installing
[elasticsearch] Installing
1 : Warning: elasticsearch has been deprecated because it is switching to an incompatible license. Check out `opensearch` instead!
Error: elasticsearch: no bottle available!
You can try to install from source with:
  brew install --build-from-source elasticsearch
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.


In Brew.php line 109:

  Brew was unable to install [elasticsearch].


elasticsearch [<mode>]
````

**How to reproduce this?**
A step by step guide on how to reproduce this issue.
`valet elasticsearch install`

**What is the solution?**
A way but, this works not for me, because "elasticsearch-full error  19968" in services list.
They think we started as root but we didnt.

````
softwareupdate --install-rosetta
brew tap elastic/tap
brew install elastic/tap/elasticsearch-full
brew services start elasticsearch-full
curl localhost:9200
````

**Sources**
All sources related to the bug. If the bug uses external tools like PHP extensions it should at
least contain a link to the tool. Any other media which proves helpful can be included here.

**Comment by leandrofreire08** [comment]
same problem here...looks like we need to replace by this opensearch

**Comment by paganel10** [comment]
Anyone has been able to successfully install elastic/opensearch ? Any link will be appreciated.

**Comment by christopherholst** [comment]
1.) https://www.oracle.com/java/technologies/downloads/#jdk17-mac
Arm 64 DMG Installer <- download and install this
2.) softwareupdate --install-rosetta
3.) brew tap elastic/tap
4.) brew install elastic/tap/elasticsearch-full --build-from-source
5.) Edit Configuration in:  /opt/homebrew/etc/elasticsearch/elasticsearch.yml
6.) start in terminal only "elasticsearch" because "brew services start elasticsearch-full" actualy doesnt work
after that you can check with
7.) curl localhost:9200
this works for me

**Comment by mrabdulhannan** [comment]
For Mac using Valet+ and already installed elasticsearch that stopped:
```
brew tap elastic/tap
brew unlink elasticsearch
brew install elastic/tap/elasticsearch-full
brew services start elasticsearch-full

**Comment by mischabraam** [comment]
https://github.com/elastic/homebrew-tap/pull/144 Needs te be fixed. Tapping this causes a warning output.

**Comment by mischabraam** [comment]
See https://github.com/weprovide/valet-plus/issues/625 
Moved to Docker for Elasticsearch in version 3.x-dev
