### ISSUE TITLE
Parked folders are also being served

### ISSUE THREAD

**Issue by srikat** [weprovide/valet-plus#60]
Hello,

I have a folder called `clients` inside my `~/Sites`.

I have parked both Sites and clients folders using the `valet park` command.

However, in the browser, it shows that clients.dev is also available.

![screenshot](http://d.pr/i/3j0oHV+)

Any idea what's wrong?

**Comment by srikat** [comment]
Fixed.

The mistake I was making was that I wasn't parking the folders properly. I should go inside the folder and then `valet park`, not be in parent and do `valet park directory`.

**Comment by timneutkens** [comment]
@srikat this is cause we just read the directory and render all the directory names with `.dev` appended 😄
