### ISSUE TITLE
Feature request: Support For PHP 8.1

### ISSUE THREAD

**Issue by osrecio** [weprovide/valet-plus#600]
- [x] I've checked the issue queue and could not find anything similar to my feature.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.3.1`

**Why implement this feature?**  
PHP 8.1 was released in 25th of Nov. and some projects support it. I think is important to be added

**What will be required for this feature?**  
After this PR merging: https://github.com/henkrehorst/homebrew-php/issues/155 can we add a Support for PHP 8.1, that I will be help on this when the PR merging :)

**Sources**
https://www.php.net/supported-versions.php
https://www.php.net/downloads.php#v8.1.2

**Comment by dverkade** [comment]
With the release of Magento 2.4.4 it will be mandatory to run on PHP 8.1 This version will be released on April 12th and we should be have support for PHP 8.1 by this time.

**Comment by osrecio** [comment]
I hope, that the other PR, is merged to add here a PR, with the changes for 8.1.

in my local env. I have a fork of valet+ and its working like a charm :)

**Comment by dverkade** [comment]
@osrecio are you able to share the fork?

**Comment by osrecio** [comment]
I’m on vacation! But monday I come back, ping me, and I will push to Github :)

greetings!

**Comment by stephansteiner** [comment]
Hi,
3 days ago henkrehorst added supporrt for PHP 8.1
https://githubhot.com/repo/henkrehorst/homebrew-php

**Comment by osrecio** [comment]
Hi @stephansteiner for the last changes of icu70 php 8.1 can’t be installed correctly.

I did a new PR to fix it: https://github.com/henkrehorst/homebrew-php/pull/160

this is the reason why this PR is in WIP: https://github.com/weprovide/valet-plus/pull/605

greetings!

**Comment by mischabraam** [comment]
Support php8.1 (with deprecated suppression) now available in 2.4.0-beta4.

**Comment by stephansteiner** [comment]
Thank you so much, I really appreciate your effort.
