### ISSUE TITLE
Feature request: Per-Site PHP Versions

### ISSUE THREAD

**Issue by claudio-ferraro** [weprovide/valet-plus#606]
- [x] I've checked the issue queue and could not find anything similar to my feature.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.3.1`

**Why implement this feature?**  
By default, Valet+ uses your chosen PHP installation to serve your sites. However, if you need to support multiple PHP versions across various sites this is not possible.

In Laravel Valet this is possible with the `isolate` command: https://laravel.com/docs/9.x/valet#per-site-php-versions. It would be nice if this could also be implemented in Valet+.

**Sources**
https://laravel.com/docs/9.x/valet#per-site-php-versions

**Comment by mischabraam** [comment]
This will be supported in Valet+ 3
