### ISSUE TITLE
Created scripts to automate the install valet-plus by first checking to see if any other web server is running

### ISSUE THREAD

**Issue by dannygsmith** [weprovide/valet-plus#61]
Created scripts to automate the install valet-plus by first checking to see if any other web server is running, and kill them.

https://campfirepixels.com/automated-way-to-install-valet-plus-by-weprovide/

valet-plus-list
git@gist.github.com:ca96e5face7cd1f02ce62aad490cfe2d.git
valet-plus-destroy
git@gist.github.com:5b74ba708d7bf8621c1cb6b959ece99f.git
valet-plus-install
git@gist.github.com:ccaa9712cb5bdc73e43276a63643366b.git

**Comment by timneutkens** [comment]
This is pretty cool 👍

**Comment by SanderAtom** [comment]
@timneutkens maybe you can add this to the Wiki?

**Comment by timneutkens** [comment]
Yeah feel free to add them 👍
