### ISSUE TITLE
Bug: Cannot Download Any Version of php 502 error

### ISSUE THREAD

**Issue by jordanvector** [weprovide/valet-plus#611]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.3.1`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Unable to download any version of php.  All commands return 502 error

brew install valet-php@7.3
brew install valet-php@7.2
brew install valet-php@7.4
brew install valet-php@8.1

==> Downloading https://dl.bintray.com/henkrehorst/valet-php/valet-php%407.3-7.3.27_2.sierra.bottle.tar.gz
curl: (22) The requested URL returned error: 502                              
Warning: Problem : HTTP error. Will retry in 1 seconds. 3 retries left.
curl: (22) The requested URL returned error: 502                              
Warning: Problem : HTTP error. Will retry in 2 seconds. 2 retries left.
curl: (22) The requested URL returned error: 502                              
Warning: Problem : HTTP error. Will retry in 4 seconds. 1 retries left.
curl: (22) The requested URL returned error: 502  

**What was supposed to happen?**
Php downloads successfully

**What actually happened?**
502 error

**How to reproduce this?**

brew install valet-php@7.3
brew install valet-php@7.2
brew install valet-php@7.4

**What is the solution?**
Fix download location

**Sources**

**Comment by jordanvector** [comment]
Adding --build-from-source on the end of the command solves the issue.  So 

brew install valet-php@7.4 --build-from-source

worked for me

**Comment by mischabraam** [comment]
Try the 2.4 beta version, see https://github.com/weprovide/valet-plus/blob/release/2.4/INSTALL.MD
