### ISSUE TITLE
Bug: bedrockvaletdriver doesn't route custom admin log in correctly

### ISSUE THREAD

**Issue by EHLOVader** [weprovide/valet-plus#613]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `Valet+ 2.4.0-beta4`
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When customizing the WordPress admin url on a site that uses the Bedrock Valet, like in iThemes using a hidden backend, the admin log in produces a 404 folder not found error. 

**What was supposed to happen?**
It should route correctly through WordPress and display the admin log in

**What actually happened?**
not found

**How to reproduce this?**
WordPress install with bedrock and iThemes configured to hide backed URL

**Comment by mischabraam** [comment]
In 2.4.0-beta6
