### ISSUE TITLE
Bug: Incorrect commit for tagged version 2.4.0-beta5

### ISSUE THREAD

**Issue by nntoan** [weprovide/valet-plus#614]
Hey guys,

It seems the latest version 2.4.0-beta5 has been tagged to an incorrect commit.

![Screen Shot 2022-11-03 at 14 26 55](https://user-images.githubusercontent.com/3891429/199666862-02d730c6-178b-46ae-a8b8-6e9dfe1a3f3e.png)

While it suppose to be tagged to this one https://github.com/weprovide/valet-plus/commit/70a890db12757bfb711296fdffecd8daf34cd79a

![Screen Shot 2022-11-03 at 14 28 37](https://user-images.githubusercontent.com/3891429/199667057-0a481e93-3b5e-4fca-92b0-2572f08c91be.png)

Please take a look.

**Comment by EHLOVader** [comment]
Is this possibly why it is trying to tap henkrehorst/php again? and why it is installing valet-phps?

**Comment by mischabraam** [comment]
This is corrected now.
