### ISSUE TITLE
Bug: 2.4.0-beta4 with wrong symlink on Mac M1 -> [libjpeg] Relinking

### ISSUE THREAD

**Issue by christopherholst** [weprovide/valet-plus#615]
this is the error: 
[libjpeg] Relinking
ln: /usr/local/opt/jpeg/lib/libjpeg.8.dylib: No such file or directory

the path /usr/local/opt/... doesnt exist on mac m1 machines

**Comment by mischabraam** [comment]
Should this be /opt/homebrew/opt/jpeg/lib/libjpeg.8.dylib for m1 macs?

**Comment by pryley** [comment]
Intel Macs use `/usr/local/`

M1 Macs use `/opt/homebrew/`

It should be: `/opt/homebrew/opt/jpeg/lib/libjpeg.dylib`

`libjpeg.dylib` links to whichever version is installed (in my case, `libjpeg.9.dylib`).

**Comment by mischabraam** [comment]
This should be fixed at https://github.com/weprovide/valet-plus/blob/70a890db12757bfb711296fdffecd8daf34cd79a/cli/Valet/PhpFpm.php#L218 .
I'm not sure where libjpeg is used for... I will need to dive into this to find that out. Maybe you could help?

The class [Architecture](https://github.com/weprovide/valet-plus/blob/release/2.4/cli/Valet/Architecture.php) supports functions and constants that can be used to resolve this.

**Comment by mischabraam** [comment]
Is this link even needed? I tested this and see that it creates a symbolic link to a file I don't even have on my system.
It's added "temporary" in the following commit (from 2017, for php5.6) https://github.com/weprovide/valet-plus/commit/76dbd8d0adcd7d99063e025a9daa78eead52af28

**Comment by mischabraam** [comment]
Fixed in https://github.com/weprovide/valet-plus/commit/50bc2a431d36fe381c199e8a61d0c0eba457ce23
