### ISSUE TITLE
Bug: valet fix (2.4.0 -beta6) cannot find proper linked PHP version on Mac M1 

### ISSUE THREAD

**Issue by paganel10** [weprovide/valet-plus#616]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>` Valet+ 2.4.0-beta6
- [x] I've run `valet fix` and `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Valet fix cannot find the installed php Version (8.1)

**What was supposed to happen?**
Valet fix was supposed to find the PHP version

**What actually happened?**
A description of what actually happened.
Check Valet+ PHP version...
Run valet fix with the --reinstall option to trigger a full reinstall of the default PHP version.
ARM Mac detected
[php@7.4] Unlinking
Error: No available formula with the name "shivammathur/php/php@7.4". Did you mean shivammathur/php/php@7.0, shivammathur/php/php@7.1, shivammathur/php/php@7.3, shivammathur/php/php@7.2, shivammathur/php/php, shivammathur/php/php@5.6, shivammathur/php/php@8.3, shivammathur/php/php@8.0, shivammathur/php/php@8.1 or shivammathur/php/php-debug?

Could not unlink PHP version!
There appears to be an issue with your PHP 7.4 installation!
See the output above for more information.
[php@7.4] Linking
Error: No available formula with the name "shivammathur/php/php@7.4". Did you mean shivammathur/php/php@7.0, shivammathur/php/php@7.1, shivammathur/php/php@7.3, shivammathur/php/php@7.2, shivammathur/php/php, shivammathur/php/php@5.6, shivammathur/php/php@8.3, shivammathur/php/php@8.0, shivammathur/php/php@8.1 or shivammathur/php/php-debug?

Could not link PHP version!
There appears to be an issue with your PHP 7.4 installation!
See the output above for more information.

Please check your linked php version, you might need to restart your terminal!
Linked PHP should be php 7.4:
PHP 8.1.13 (cli) (built: Dec  7 2022 23:32:13) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.13, Copyright (c), by Zend Technologies

**Comment by Ducraisse** [comment]
Issue is in "PhpFpm.php", i solved this locally be editing this file and adding the following line.

`self::PHP_V81_VERSION => self::PHP_FORMULA_NAME .'@'. self::PHP_V81_VERSION`

**Comment by mischabraam** [comment]
Fixed in v3
