### ISSUE TITLE
Bug: Docs - INSTALL.md instructions conflict with wiki/Installation

### ISSUE THREAD

**Issue by elburro1887** [weprovide/valet-plus#619]
The information in https://github.com/weprovide/valet-plus/wiki/Installation is out of date, INSTALL.md contains the newer info, using shivammathur/php instead of henkrehorst for example. 

Maybe there should be only one single installation "source of truth", and INSTALL.md should be merged into the wiki?

**Comment by mischabraam** [comment]
To make it even worse.. .the version 3-dev branch needs other install instructions. So, yes it needs updating

**Comment by mischabraam** [comment]
Updated the wiki for installation
