### ISSUE TITLE
Bug: Cannot use valet after switching to PHP < 7.3 because of Composer

### ISSUE THREAD

**Issue by EHLOVader** [weprovide/valet-plus#620]
- [x ] I've checked the issue queue and could not find anything similar to my bug.
- [x ] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [ x] I've run `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
Switching to php 7.2 or less I get the warning that it is EOL but trying to use valet after, even to switch to another version returns this composer fatal error.

> PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.2

**What was supposed to happen?**
It should probably still work, maybe it needs platform check false in it

**What actually happened?**
> PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.2

**How to reproduce this?**
valet use 7.2

valet use 7.3

I think that this is how you might get past it. 
`brew link --overwrite php@7.3`

But wanted to submit this to document it.

**Comment by EHLOVader** [comment]
Realized looking through issues for possible contribution opportunities this is a duplicate of https://github.com/weprovide/valet-plus/issues/571 essentially. 

It is just that as time has progressed the platform dependency for Composer has moved further ahead, so the error message is now a bit of a mismatch. 

Should older versions be removed? or is there a workaround to keep the composer happy with these past versions of PHP?

**Comment by mischabraam** [comment]
To which valet+ version is this?

**Comment by EHLOVader** [comment]
On the latest version at the time of writing. 
Valet+ 2.4.0

I see there is a new Valet+ 2.4.1 I can check to see if that fixes it. 
But considering 571 is still open, I think this may just be a moving target. As versions of PHP are EOL and the requirements of Composer shift with that it will cause an increasing number of PHP versions to stop working, or stop Valet from working.

**Comment by mischabraam** [comment]
Alright, thanks. No 2.4.1 won't fix it. And yes, it's the same as #571, though with other php versions. 

It's a shame, because the code actually works just fine with PHP 7.2. It's just the composer dependencies that are a hassle here. To fit them for all PHP versions is kind of impossible.

I'm not sure though why it's doing the platform check, because the `composer.json` had the platform check disabled with the following.
```
    "config": {
        "platform-check": false
    },
```
And it has a PHP dependency of
```
    "require": {
        "php": ">=7.1",
```

**Comment by EHLOVader** [comment]
Yeah, I feel like i saw all of the things that should work. 

Perhaps is it something to do with Brew formulas and steps there? 
I don't think that makes sense, because the error happens on Valet commands specifically, but it was a thought.

**Comment by mischabraam** [comment]
Out of the box... do you think we can get rid of this php dependencies issues when we would distribute valet+ inside a PHAR?

**Comment by EHLOVader** [comment]
> I'm not sure though why it's doing the platform check, because the `composer.json` had the platform check disabled with the following.

I actually was able to get this to work when I added the platform check false to my composer.json in the CGR global file. I wonder if it was because I used CGR to install. 

So adding
```
"config": {
        "platform-check": false
    }
```

And then running `dump-autoload` worked

**Comment by mischabraam** [comment]
So, we can resolve this?

**Comment by mischabraam** [comment]
The dependency of your current running/linked (switched to) php version is no longer of influence to Valet+ commands. Yesterday I committed a change to fix this. Valet+ commands will now use the required php version to run smooth despite of your current running/linked (switched to) php version. See https://github.com/weprovide/valet-plus/commit/fcd8eb4be799e341080c46fc6440a322e8e8e0c2
