### ISSUE TITLE
Bug: "valet share" throws an error.

### ISSUE THREAD

**Issue by NSHenry** [weprovide/valet-plus#621]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
`valet share` doesn't run successfully. 

**What was supposed to happen?**
Valet+ should run ngrok should without a problem.

**What actually happened?**
This error is thrown: `ERROR:  unknown shorthand flag: 'o' in -ost-header=rewrite`.

**How to reproduce this?**
Run `valet share`.

**What is the solution?**
The `-host-header=rewrite` flag on line 52 of the `valet` file should be changed to `--host-header=rewrite`.

**Sources**
https://ngrok.com/docs/guides/upgrade-v2-v3/
The ngrok documentation makes mention of this: "The ngrok agent only accepts long name flags prefixed with `--` and will error if a single hyphen is used. When updating your scripts, ensure flags like `--host-header` are using double hyphens."

**Comment by mischabraam** [comment]
Fixed in 2.4.1
