### ISSUE TITLE
Bug: MySQL 8.1 is installed by default and not supported in Magento

### ISSUE THREAD

**Issue by odbynl** [weprovide/valet-plus#623]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [x] I've run `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
When installing Valet+ with the `--with-mysql-8` option homebrew installs MySQL 8.1. When running setup:upgrade in Magento you get an error that only MySQL 8.0 is supported.

**What was supposed to happen?**
Probably install version 8.0 of MySQL instead of 8.1.

**What actually happened?**
MySQL 8.1 is installed (which is not supported with Magento 2).

**How to reproduce this?**
- Run `valet install --with-mysql-8`.
- Add latest installation of Magento 2
- When running `bin/magento setup:upgrade` you'll get an error that MySQL 8.1 is not supported.

**What is the solution?**
Probably install mysql with `brew install mysql@8.0`. But I cannot get it working. I tried to remove `mysql` and install `mysql@8.0`, but when starting the service it stopped and I cannot get connection with mysql.

**Comment by josecruzchavez** [comment]
Hi this problem have in Magento Mysql Compatibility, to fixed add next line in app/etc/di.xml aprox line 1855
`<item name="MySQL-(8.0-8.1)" xsi:type="string">^8\.[0-1]\.</item>`

It should look like this
`<type name="Magento\Framework\DB\Adapter\SqlVersionProvider">
        <arguments>
            <argument name="supportedVersionPatterns" xsi:type="array">
                <item name="MySQL-(8.0-8.1)" xsi:type="string">^8\.[0-1]\.</item>
                <item name="MySQL-5.7" xsi:type="string">^5\.7\.</item>
                <item name="MariaDB-(10.2-10.6)" xsi:type="string">^10\.[2-6]\.</item>
            </argument>
        </arguments>
    </type>`

**Comment by mischabraam** [comment]
`brew search mysql` now gives mysql, mysql@8.0 and mysql@5.7. Currently the `valet install --with-mysql-8` install `mysql` (which now is 8.1 indeed). I'm working on this, targetting the 3.x-dev branch, to support the following.

`valet install --with-mysql80`
`valet install --with-mysql81`
`valet install --with-mariadb`
`valet install` (will install mysql@5.7)

**Comment by mischabraam** [comment]
Fix in the 3.x-dev branch.
