### ISSUE TITLE
Bug: Unable To Determine Linked PHP - PHP 8.3

### ISSUE THREAD

**Issue by ThyNameIsMud** [weprovide/valet-plus#626]
- [✔️] I've checked the issue queue and could not find anything similar to my bug.
- [✔️] I'm on the latest version of valet-plus (`valet --version`): `<Valet-Plus-Version>`
- [✔️] I've run `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
PHP 8.3 has been released to brew. We are doing a `brew update && brew upgrade` that results in Valet throwing an 'Unable to determine linked PHP.' warning.

**What was supposed to happen?**
Valet should identify PHP 8.3

**What actually happened?**
Valet does not identify PHP 8.3.

**How to reproduce this?**
1. `brew update && brew upgrade`
2. `valet use 8.0`

**What is the solution?**
Add in code to identify PHP 8.3 and allow use of it.

**Sources**
https://github.com/weprovide/valet-plus/blob/2.x/cli/Valet/PhpFpm.php#L19

**Comment by mischabraam** [comment]
This is supported in the 3.x version, see https://github.com/weprovide/valet-plus/tree/3.x
