### ISSUE TITLE
Bug: 502 Bad Gateway or everything redirects to mailhog.test

### ISSUE THREAD

**Issue by jeroen-pon** [weprovide/valet-plus#628]
- [x] I've checked the issue queue and could not find anything similar to my bug.
- [x] I'm on the latest version of valet-plus (`valet --version`): `2.4.2`
- [x] I've run `valet install` after updating and before submitting my issue/feature.

**What is the problem?**
After the latest code changes to the Nginx files `/usr/local/etc/nginx/valet/mailhog.conf` and `/usr/local/etc/nginx/valet/elasticsearch.conf`, all sites redirect to mailhog.test. If you stop the mailhog service, you get a 502 bad gateway error.

**What was supposed to happen?**
Get the expected website.

**What actually happened?**
Got a redirect to mailhog.test and a 502 bad gateway.

**What is the solution?**
Change `listen 127.0.0.1:80;` back to `listen 80;` in `cli/stubs/mailhog.conf` and `cli/stubs/elasticsearch.conf`

**Comment by mischabraam** [comment]
https://github.com/weprovide/valet-plus/commit/58a92897a233a969456f5ad8904b65ad2540a099 causes the issue? Strange, I don't encounter your described issue. All test domains redirect to mailhog?

**Comment by cfaria** [comment]
Same issue here. On Sonoma and last Valet+ version.

All test domains redirect to mailhog and have a 502 Bad Gateway when mailhog is disabled.

@jeroen-pon solution made my day. Thank you!

**Comment by jeroen-pon** [comment]
@mischabraam I just tried to reproduce this issue with a Apple M1 chip computer. I was running Valet+ on version 2.4.1 on this system. Ran `cat /opt/homebrew/etc/nginx/valet/mailhog.conf` to check if I had the "old" line in the file: `listen =80;`. Ran `valet install` and double checked if the line in the file was changed to `listen 127.0.0.1:80;`. This was the case. Conclusion: the latest Valet+ version 2.4.2 does work on my Apple M1 chip system, but not on my Intel chip MacBook. Could it be possible that it is system chip based related?

EDIT: I use the exact same OSx version on both systems -> Sonoma 14.2.1

**Comment by cfaria** [comment]
Here my settings where the listen 127.0.0.1:80; line doesn't work

Sonoma 14.3
2,4 GHz Intel Core i9

I also had the same problem in a: 

Ventura 13.3.1
Apple Mac Mini M2

**Comment by mischabraam** [comment]
Yeah, the chip is of no influence here. The chip has impact on the paths where configs and such are stored, like `/opt/homebrew` vs `/usr/local`.  
This is a nginx setting, specifically to be able to open mailhog and elasticsearch on reachable domains.

**Comment by mischabraam** [comment]
I tested to remove `127.0.0.1:` from the configuration (for both mailhog.test and elasticsearch.test) in the 3.x-dev branch. With this configuration I'll have a 404 for the mailhog.test domain. The elasticsearch.test domain seems to work just fine.

<img width="335" alt="Screenshot 2024-01-30 at 21 23 10" src="https://github.com/weprovide/valet-plus/assets/19824986/e6d89dc0-e2db-49a0-8c88-b38005a1e4b8">


See also https://github.com/weprovide/valet-plus/issues/478

I'm running an 2,6 GHz 6-Core Intel Core i7 with Sonoma 14.1.1

**Comment by mischabraam** [comment]
I might have found a way using https://laravel.com/docs/10.x/valet#proxying-services

**Comment by mischabraam** [comment]
Fixed it in the https://github.com/weprovide/valet-plus/tree/3.x branch.
