### ISSUE TITLE
Issues with command substitution when errors exist

### ISSUE THREAD

**Issue by EHLOVader** [weprovide/valet-plus#634]
There are issues when the command substitution is used like the[ composer passthrough for isolated sites](https://github.com/weprovide/valet-plus/blob/3.x/valet-plus#L180C9-L180C73)
`$(php "$DIR/cli/valet.php" which-php) $(which composer) "${@:2}"`

I experienced this when docker was not running. There is an error about connecting to Docker but it interferes with `which-php`
This is the output from the composer call:
```bash
$ valet-plus composer install
/vendor/weprovide/valet-plus/valet-plus: line 180: Cannot: command not found
```

This is my output from valet-plus when docker is off
```bash
$ valet-plus on-latest-version
Cannot connect to the Docker daemon at unix:///Users/me/.docker/run/docker.sock. Is the docker daemon running?

Yes
```

I was going to suggest a new flag for suppressing errors, or making them pass through using an `echo ... &&` maybe.

**Comment by mischabraam** [comment]
Thanks. I can reproduce this.
@christopherholst actually fixed this in https://github.com/weprovide/valet-plus/pull/629. I took some of his code, but not fully. I thought it wouldn't matter to see that Docker error ('cause I actually saw it more like a warning or such). But didn't test it with your scenario. 
I'll fix this.

**Comment by mischabraam** [comment]
Fixed in https://github.com/weprovide/valet-plus/commit/8db24e23973f2028468804e64b75fc1d219c18f0
