### ISSUE TITLE
Mailhog configuration is not added to php versions used in isolation

### ISSUE THREAD

**Issue by EHLOVader** [weprovide/valet-plus#637]
I found that the emails weren't showing up in my Mailhog. 
From investigating I found that the mailhog.ini isn't in any of the isolated php versions conf.d. 

It didn't seem as though sendmail was actually generating real emails, but it doesn't seem to have produced emails either.

**Comment by mischabraam** [comment]
Hmm weird. It should be. Tested this and verified it works as expected. See screenshots below. I have php8.1 running and php7.4 isolated on one site. The `mailhog.ini` is installed on both versions. Sending email and receiving them on both versions works too.
<img width="1132" alt="Screenshot_2024-04-13_at_09_14_14" src="https://github.com/weprovide/valet-plus/assets/19824986/cbacf615-40d3-4d80-8a42-546a4b885c23">

**Comment by EHLOVader** [comment]
That is really odd.
I wonder what I did in mine then. 

I confirmed that emails were sent to the users of the site when they didn't show up in my mailhog.

**Comment by mischabraam** [comment]
Ok, did you manage to figure out what went wrong in your case? Do you agree in closing this issue, or do we need a fix?

**Comment by EHLOVader** [comment]
You can close this. I will get more details if I run into this again. 

Thank you
