### ISSUE TITLE
Composer requirement error on php 8.3.x

### ISSUE THREAD

**Issue by kenseiatwork** [weprovide/valet-plus#639]
Laravel/valet php requirement is: "php": "^7.1|^8.0"
valet-plus uses:  "php": ">=7.1 <8.3"

When running on php 8.3.x and running 
composer global update

Results in a composer requirement error
`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires weprovide/valet-plus 3.x -> satisfiable by weprovide/valet-plus[3.0.0, 3.0.1, 3.0.2, 3.0.3].
    - weprovide/valet-plus[3.0.0, ..., 3.0.3] require php >=7.1 <8.3 -> your php version (8.3.9) does not satisfy that requirement.`

**Comment by mluzitano** [comment]
We ran into the same thing, and here's how we resolved it:
`composer global require weprovide/valet-plus --update-with-dependencies --ignore-platform-req=php`

**Comment by mischabraam** [comment]
Fixed in https://github.com/weprovide/valet-plus/releases/tag/3.0.4
