### ISSUE TITLE
Install --with-mysql80 not working

### ISSUE THREAD

**Issue by bajaj-sudhanshu** [weprovide/valet-plus#640]
The installation is not moving at valet+ services. I can't see an error and followed all the steps with success.

```
➜  ~ valet-plus install --with-mysql80
Password:

Installing nginx...
[nginx] is not installed, installing it now via Brew... 🍻
Installing nginx configuration...
Installing nginx directory...

Installing and configuring phpfpm...
Updating PHP configuration for php@8.2...
Restarting php@8.2...
Installing extensions for PHP 8.2
	apcu is already installed, skipping...
	yaml is already installed, skipping...
	ds is already installed, skipping...
	imagick is already installed, skipping...

Installing dnsmasq...
[dnsmasq] is not installed, installing it now via Brew... 🍻
Updating Dnsmasq configuration...
Restarting dnsmasq...
Valet is configured to serve for TLD [.test]

Restarting nginx...


Valet installed successfully!

Installing Valet+ services
Stopping ...
Installing mysql@8.0...
[mysql@8.0] is not installed, installing it now via Brew... 🍻
Stopping mysql@8.0...
```

**Comment by mischabraam** [comment]
Yeah, I have it sometimes too. Somehow mysql is unwilling to stop. The workaround I use is to stop mysql manually with the following command.

```
brew services stop mysql@8.0
```

(you might need to use `sudo` as prefix)

I have searched for the reason why it sometimes refuses to stop the service using Valet+, but I haven't found it yet.


Also.. do you have another version of Mysql already running? Currently, it's not supported to have multiple Mysql versions running on your machine. If so, you should removed unwanted mysql versions first.

**Comment by bajaj-sudhanshu** [comment]
@mischabraam  There was no other MySQL.

I had to stop the MySQL@8.0 from another tab and then the script continued. 

<img width="1119" alt="image" src="https://github.com/user-attachments/assets/bac78f3c-3bcd-435b-a5c6-2f8ef9bb7605">

However, default page is not showing all the hosts I have.

![image](https://github.com/user-attachments/assets/394df19a-cfa1-49fb-9b64-8c94c0d72dbc)

**Comment by mischabraam** [comment]
The 404 page on 127.0.0.1 is correct and tells me Valet+ is working. Check the manual at https://laravel.com/docs/11.x/valet#serving-sites and you should be able to serve your websites, see the "park" command.

**Comment by its-leofisher** [comment]
I was having same issue and stopping mysql in a separate terminal tab works but I get this:
<img width="936" alt="image" src="https://github.com/user-attachments/assets/9c32d016-b200-4558-9da8-71048bf74991">

I have uninstalled and reinstalled Mysql8 via Brew and restarted computer

 Valet+ 3.0.3
 Laravel Valet 4.8.0

<img width="761" alt="image" src="https://github.com/user-attachments/assets/d1941b47-bb20-419f-a102-eaa30f7ed777">

<img width="624" alt="image" src="https://github.com/user-attachments/assets/61c4f246-0b92-4a9d-96b0-27852c189a86">

any ideas?

**Comment by mischabraam** [comment]
Could be a resolving problem like mentioned in https://stackoverflow.com/questions/1676688/mysql-connection-not-working-2002-no-such-file-or-directory 
At line 284 `localhost` is used to connect. The above solution suggests to use `127.0.0.1` instead. Can you edit the code and try this?

**Comment by mischabraam** [comment]
Fixed in https://github.com/weprovide/valet-plus/releases/tag/3.0.4
