### ISSUE TITLE
Change .dev to .local?

### ISSUE THREAD

**Issue by royduin** [weprovide/valet-plus#68]
See: https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by adamlindqvist** [comment]
Do you want it for a specific app or in general?

> For example, if you'd like to use .app instead of .dev, run valet domain app and Valet will start serving your projects at *.app automatically.
https://laravel.com/docs/5.5/valet#installation

**Comment by royduin** [comment]
I just opened this issue for discussion about this subject.

**Comment by jerrylopez** [comment]
Not sure if `.local` should be the tld it is changed to. I believe that Macs have this reserved, vaguely remember seeing this somewhere.

**Comment by srikat** [comment]
@jerrylopez From the article in the first post:

> Alternatively, if you're looking for a quick "search and replace" alternative for existing setups, consider the .test gTLD, which is a reserved name by IETF for testing (or development) purposes.

**Comment by barryvdh** [comment]
See https://github.com/laravel/valet/pull/436

I would suggest to follow Valet, to keep it in line. But my personal suggestion would be to use `.localhost`

**Comment by kanduvisla** [comment]
@jerrylopez is right: `.local.` on Mac is reserved and will route all traffic through the Bonjour service first (if I remember correctly). When your frontend will load 300+ assets (like Magento 2 does for example), this has tremendous effect on your performance.

**Comment by samgranger** [comment]
Does anyone here have an objection if we go with ```.test```? Using a reserved name will prevent future issues. Thumbs up for agree, thumbs down for disagree.

**Comment by barryvdh** [comment]
Just change to what Valet does, which is `.test`. No need to argue ;)

**Comment by samgranger** [comment]
We have changed the TLD to .test in 1.0.10: https://github.com/weprovide/valet-plus/releases/tag/1.0.10

Please run ```valet domain test``` to switch over to .test

**Comment by iAn-Pinto** [comment]
Try solution in https://github.com/laravel/valet/issues/566#issuecomment-418303683
