### ISSUE TITLE
Error when trying to change .dev domain extension

### ISSUE THREAD

**Issue by srikat** [weprovide/valet-plus#72]
I am trying to change the domain extension from the default `.dev` to `.test` for a site that has been secured (https://custom-slider.dev/ - I see "connection not private" browser security warning).

My site's folder is inside a parked folder.

I navigated to the parked folder and ran

```
valet custom-slider.dev test
```

and it results in

> [Symfony\Component\Console\Exception\CommandNotFoundException]  
>   Command "custom-slider.dev" is not defined.

Any ideas?

**Comment by srikat** [comment]
Solved.

Apparently, `domain` is to be typed literally.

I navigated to the folder where the site is parked (i.e., parent folder of the site) and executed

```
sudo valet domain test 
```

Without the `sudo`, I was getting

```
PHP Warning:  file_put_contents(/etc/resolver/test): failed to open stream: Permission denied in /Users/sridharkatakam/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 125

Warning: file_put_contents(/etc/resolver/test): failed to open stream: Permission denied in /Users/sridharkatakam/.composer/vendor/weprovide/valet-plus/cli/Valet/Filesystem.php on line 125
```

**Comment by adriaanzon** [comment]
I'm getting the same error without sudo.

Shouldn't Valet automatically run using sudo when it's needed?
