### ISSUE TITLE
Unable to switch back to PHP 7.0 from PHP 5.6

### ISSUE THREAD

**Issue by derpepe** [weprovide/valet-plus#74]
I installed Valet+ and switched to PHP 5.6 by executing "valet use 5.6".

After that, any call to the valet-CLI-command led to an error.

The problem is, that tightenco/collect v5.5.13 which is used by valet requires php >=7.0.
The then installed PHP version (5.6.31) does not suffice.

I had to manally run
```
  brew unlink php56
  brew link php70
```

After that I was able to execute "valet use 7.1" and fix the system.

**Comment by omolto** [comment]
+1

**Comment by timneutkens** [comment]
Fixed in 1.0.6 https://github.com/weprovide/valet-plus/releases/tag/1.0.6 Thanks for surfacing this 👍

**Comment by rafaelstz** [comment]
I use these commands to fix it.
<img width="995" alt="screen shot 2018-05-07 at 22 00 32" src="https://user-images.githubusercontent.com/610598/39732173-355ed0f4-5242-11e8-98dc-d8e412a98269.png">

**Comment by alexblueacorn** [comment]
Valet+ 1.0.18
I still have it.
