### ISSUE TITLE
valet unsecure does not work on newly secured host

### ISSUE THREAD

**Issue by dannygsmith** [weprovide/valet-plus#75]
It appears that when you run `valet stop` it does not restart `dnsmasq`.  I killed it via `sudo killall dnsmasq` and it got a new `pid`.  Even then when trying to open the page it would not work.  This seems like a bug to me, unless I am just holding my mouth wrong :)

**Comment by SanderAtom** [comment]
Not exactly sure what the error is you are experiencing, but I do think you should be able to stop all the services when you execute `valet stop`. I've made PR #83 but @timneutkens can decide if this doesn't break anything.
