### ISSUE TITLE
Fatal error: Class 'LocalValetDriver' not found

### ISSUE THREAD

**Issue by SanderAtom** [weprovide/valet-plus#76]
A fresh install and using a LocalValetDriver.php for a different webroot, throws this error:
`Fatal error: Class 'LocalValetDriver' not found in /Users/sander/.composer/vendor/weprovide/valet-plus/cli/drivers/ValetDriver.php on line 49`

This is the code:
```
$cachedDriver = apcu_fetch('valet_driver_'.$siteName);

if(!$noCache && $cachedDriver) {
  $driver = new $cachedDriver;
  return $driver;
}
```

**Comment by SanderAtom** [comment]
Temp work-around is to comment out those lines I mention above. It won't use caching but it works.

**Comment by timneutkens** [comment]
Fixed in https://github.com/weprovide/valet-plus/commit/58613888eed808a050f9a73c97ca4d78458b6834
