### ISSUE TITLE
How to handle multiple stores in Magento site?

### ISSUE THREAD

**Issue by jahvi** [weprovide/valet-plus#77]
What's the recommended way of handling multiple stores with Valet+?

Usually I'd just add a line in my nginx.conf file so the `MAGE_RUN_CODE` or `MAGE_RUN_TYPE` server variables change depending on the domain name, is it possible to do something like this with Valet+? Should I use a custom driver?

Thanks.

**Comment by vanpoppel** [comment]
Haven't tried it yet, but you might be able to run Magento from subdirectories and link your multi-store domain names to those directories.

**Comment by jahvi** [comment]
Thanks, pointing the domain names is not a problem, e.g. I can point `magento.dev` and `store2.magento.dev` to the same directory just fine. The problem is that I also need to let Magento know that if the domain name is `store2.magento.dev` set the `MAGE_RUN_CODE` server variable to `store2` so it loads the right store view, right now going to the store2 domain just redirects me to the main `magento.dev` store as "expected".

**Comment by lazyguru** [comment]
@jahvi I usually handle this by modifying the index.php file to do the hostname checks:

```
$host = $_SERVER['HTTP_HOST'];
if (preg_match('/some-regex-that-matches-host-but-extracts-runcode-from-hostname/', $host, $matches)) {
    $_SERVER['MAGE_RUN_CODE'] = $matches[1];
}
```

**Comment by jahvi** [comment]
I see I didn't want to edit the index file but it might be the easiest way, at least in development thanks!

**Comment by Igloczek** [comment]
I think it will be a less dirty way to handle multi stores:
1. Add all stores domains using `valet link` i.e. `valet link second` to point a `second.dev` traffic to the current project
2. Create `LocalValetDriver.php` file in the project root
3. Extend create new `LocalValetDriver` class extending the `Magento2ValetDriver` class
4. Copy the `frontControllerPath` function from https://github.com/weprovide/valet-plus/blob/master/cli/drivers/Magento2ValetDriver.php
5. Add your stores configuration to the function body like this:
```php
if ($_SERVER['HTTP_HOST'] === 'first.dev') {
    $_SERVER['MAGE_RUN_CODE'] = 'default';
    $_SERVER['MAGE_RUN_TYPE'] = 'store';
}

if ($_SERVER['HTTP_HOST'] === 'second.dev') {
    $_SERVER['MAGE_RUN_CODE'] = 'second';
    $_SERVER['MAGE_RUN_TYPE'] = 'store';
}

if ($_SERVER['HTTP_HOST'] === 'extra.dev') {
    $_SERVER['MAGE_RUN_CODE'] = 'extra';
    $_SERVER['MAGE_RUN_TYPE'] = 'website';
}
```
6. Enjoy working multi store :)

**Comment by timneutkens** [comment]
@Igloczek's solution is 👌

**Comment by timneutkens** [comment]
Though you shouldn't copy `frontControllerPath` instead do something like this:

```
class LocalValetDriver extends Magento2ValetDriver {
     public function frontControllerPath($sitePath, $siteName, $uri) {
        if ($_SERVER['HTTP_HOST'] === 'first.dev') {
            $_SERVER['MAGE_RUN_CODE'] = 'default';
            $_SERVER['MAGE_RUN_TYPE'] = 'store';
        }
        
        if ($_SERVER['HTTP_HOST'] === 'second.dev') {
            $_SERVER['MAGE_RUN_CODE'] = 'second';
            $_SERVER['MAGE_RUN_TYPE'] = 'store';
        }
        
        if ($_SERVER['HTTP_HOST'] === 'extra.dev') {
            $_SERVER['MAGE_RUN_CODE'] = 'extra';
            $_SERVER['MAGE_RUN_TYPE'] = 'website';
        }

        return parent::frontControllerPath($sitePath, $siteName, $uri)
     }
}
```

**Comment by Igloczek** [comment]
Thanks, I was looking for something like this! Works like a charm.

Do you think it's possible to store this type of configuration somewhere and add the logic directly to the main driver?
I have a lot multisite stores for both M1/M2, will be great to find out the best possible way and write it down somewhere in the docs.

**Comment by timneutkens** [comment]
@Igloczek in theory you could read from a json file, I'd be willing to add something like that to the driver, since we have a need for that too at We Provide 👍

**Comment by timneutkens** [comment]
cc @samgranger

**Comment by Igloczek** [comment]
Are you thinking about adding a new one, like `multistore.json` at the project root or there is a config file somewhere already and we can extend it?

**Comment by timneutkens** [comment]
@Igloczek yeah something like that. Or `stores.json`

**Comment by lazyguru** [comment]
Why not go a little generic and something like `server_vars.json` or `request_vars.json` so that you could pass in things other than just MAGE_RUN_CODE? (could be useful for other drivers)

**Comment by Januszpl** [comment]
How to make it work if I had previously in nginx this
```
map $request_uri $MAGE_RUN_CODE {
    default   default;
    ~^/cz/     cz;
}

map $request_uri $MAGE_RUN_TYPE {
    default   store;
    ~^/cz/     store;
}
```

and then I had
`pub/static/frontend/VendorName/themename/pl_PL/`
`pub/static/frontend/VendorName/themename-cz/cz_CZ/`

Now I have using valet+ and setting store and type based on request uri as

`pub/static/frontend/VendorName/themename/pl_PL/`
`pub/static/frontend/VendorName/themename/cz_CZ/`

so instead of `themename-cz/cz_CZ` I have `themename/cz_CZ`

**Comment by samgranger** [comment]
Closing this ticket as we have added this functionality to 1.0.19. Documentation coming soon!

**Comment by danistor** [comment]
@samgranger Could you link the documentation for this functionality? Thanks!

**Comment by samgranger** [comment]
Quick example @danistor - create a new file called `.env.valet` in your project root.

Example contents:
```
<?php
  
return [
    'otherstoreview' => [
        'MAGE_RUN_CODE' => 'store-code-goes-here',
        'MAGE_RUN_TYPE' => 'store',
    ],
];
```

`valet link otherstoreview` creates a new link, you can now view a store with code `store-code-goes-here` at `otherstoreview.test`

**Comment by samgranger** [comment]
`valet link otherstoreview` has to be run in the root of your current magento project by the way - in case that part was unclear.

**Comment by danistor** [comment]
It doesn't seem to work, I am redirected to the default store. Also tried with
```
<?php 
return [
    'otherstoreview' => [
        'MAGE_RUN_CODE' => 'website_code',
        'MAGE_RUN_TYPE' => 'website',
    ],
];
```

`valet links` correctly shows that the link was created. Am I missing something?

**Comment by jahvi** [comment]
Did you change the URL for the second store in the backend?

**Comment by danistor** [comment]
My bad! after changing the url for the store everything works like a charm. Thanks!

**Comment by matt-bailey** [comment]
> @samgranger Could you link the documentation for this functionality? Thanks!

I'm struggling to find this documentation, could you point me in the right direction please? Thanks.

**Comment by amarroni** [comment]
> Quick example @danistor - create a new file called `.env.valet` in your project root.
> 
> Example contents:
> 
> ```
> <?php
>   
> return [
>     'otherstoreview' => [
>         'MAGE_RUN_CODE' => 'store_code_goes_here',
>         'MAGE_RUN_TYPE' => 'store',
>     ],
> ];
> ```
> 
> `valet link otherstoreview` creates a new link, you can now view a store with code `store_code_goes_here` at `otherstoreview.test`

I just used this configuration to handle a multi-store magento installation and wokerd as expected. Solution verified.

**Comment by actionis** [comment]
When I attempt this, the admin URL returns a 404. Any ideas?

**Comment by amcguireweb** [comment]
When I attempt to configure this as described, the admin URL returns a 404, any ideas?

**Comment by SanderAtom** [comment]
@matt-bailey I've added a Wiki page with a summary of the Environment variables information here https://github.com/weprovide/valet-plus/wiki/Environment-variables
You can open a new issue if anything is missing or needs changed.
