### ISSUE TITLE
Commit Magento2Driver to upstream

### ISSUE THREAD

**Issue by lazyguru** [weprovide/valet-plus#78]
Do you have any issues with committing your changes to the Magento2 driver back to the Laravel Valet project?  The Magento community at large would benefit from your updates. If this isn't something you are interested in doing, would it be ok if I went it did it for you?

**Comment by lazyguru** [comment]
Here is my proposed branch, I've maintained credit by author (though not the original commits): https://github.com/laravel/valet/compare/master...lazyguru:update-magento2-driver-from-valet-plus

**Comment by timneutkens** [comment]
@lazyguru sure, go ahead! it's all MIT licensed 👌 The `public function configure($devtools, $url) {` can be removed in valet's case since they don't have `valet configure`, we only have that in Valet+ 👍
