### ISSUE TITLE
Custom drivers not working

### ISSUE THREAD

**Issue by omolto** [weprovide/valet-plus#79]
After updating from 1.0.3 to 1.0.6 custom valet drivers are not working. It seems a cache problem with the path where it is looking for as the first load works but not the following.

Fatal error: Uncaught Error: Class 'xxxxxMagentoValetDriver' not found in /Users/Name/.composer/vendor/weprovide/valet-plus/cli/drivers/ValetDriver.php on line 54
Error: Class 'xxxxxMagentoValetDriver' not found in /Users/Name/.composer/vendor/weprovide/valet-plus/cli/drivers/ValetDriver.php on line 54

**Comment by timneutkens** [comment]
Fixed in 1.0.7 🙌 https://github.com/weprovide/valet-plus/releases/tag/1.0.7

**Comment by omolto** [comment]
It works!

**Comment by timneutkens** [comment]
👍
