### ISSUE TITLE
Valet cannot declare class Brew

### ISSUE THREAD

**Issue by rdorck** [weprovide/valet-plus#86]
Fatal error: Cannot declare class Brew, because the name is already in use in /Users/rockr/.composer/vendor/weprovide/valet-plus/cli/includes/facades.php on line 32

I have tried to uninstall and reinstall amongst other things to try and get over this, but all failed.
This happens on every single valet command.

**Comment by SanderAtom** [comment]
Do you still have normal Valet installed?

**Comment by timneutkens** [comment]
Closing cause of inactivity

**Comment by jonatanolsson** [comment]
Had this problem, solved it by removing old valet from ~/.composer/composer.json (global) if anyone else encounter this problem :)

Also removed all packages and started from fresh, probably because i had old valet in the dependencies. Super stupid human error :P
