### ISSUE TITLE
Magento 1: Add support for multiple store views

### ISSUE THREAD

**Issue by TomFranssen** [weprovide/valet-plus#88]
In my old apache config I would create multiple v hosts for multiple store views in Magento. 
By adding the `SetEnv MAGE_RUN_CODE "store code"` in the v host the right store view would be selected when browsing to your site. It is possible to add this someway in Valet +? Now I need to manually switch store views if I want to see a different store view.

**Comment by samgranger** [comment]
Hi Tom,

Please add a LocalValetDriver.php file to the root of your project, ie:

```
<?php
class LocalValetDriver extends MagentoValetDriver
{
     public function frontControllerPath($sitePath, $siteName, $uri) {
        if ($_SERVER['HTTP_HOST'] === 'first.dev') {
            $_SERVER['MAGE_RUN_CODE'] = 'default';
            $_SERVER['MAGE_RUN_TYPE'] = 'store';
        }
        
        if ($_SERVER['HTTP_HOST'] === 'second.dev') {
            $_SERVER['MAGE_RUN_CODE'] = 'second';
            $_SERVER['MAGE_RUN_TYPE'] = 'store';
        }

        return parent::frontControllerPath($sitePath, $siteName, $uri);
     }
}
```

**Comment by TomFranssen** [comment]
Thanks Sam :-)
