### ISSUE TITLE
Did not get front controller from driver. Please return a front controller to be executed.

### ISSUE THREAD

**Issue by tombeachell** [weprovide/valet-plus#92]
I installed valet-plus, but I get this error, i'm not sure exactly how to resolve it?

**Comment by Tristan-N** [comment]
This happens to me too, but not regularly. If it doesn't work, I can't visit any Valet+ site. Valet install, valet restart, valet use (any version available) all cause the same issue. Sometimes a reboot helps, sometimes it just fix itself. Not sure how or why this is happening. Well, not sure is an understatement: I have no clue at all.

**Comment by MetalCar** [comment]
Happen for me too. Can we reopen this?
