### ISSUE TITLE
Request: Make xdebug autostart configurable

### ISSUE THREAD

**Issue by haringsrob** [weprovide/valet-plus#93]
Hi,

First of all, great work on valet+, it is a great addition to valet especially when working on multiple projects. 

However, I have one issue, the xdebug switch is good, but it is to me not as efficient as it should be.

For day to day development, I do not need the autostart, but I do need xdebug to be active. Therefor it would be great to make this an additional switch.

Example:
Currently we have:
`valet xdebug on` and `valet xdebug off`

What would be nice is:
`valet xdebug_autostart on` and `valet xdebug_autostart off`

This will unblock the systems hookups when running command line and sites at the same time.
But still allows me to activate it when needed.

Please feel free to change the wording :).

**Comment by SanderAtom** [comment]
I'm not sure if this solves your problem, but when I untick the 'Start listening for debug connections' button in PhpStorm, no processes hang up. But I can imagine if you use a different IDE this might not work.

**Comment by haringsrob** [comment]
Hi @SanderAtom,

I use phpstorm and I know I can disable the listener, however this is mostly just turned on for web debugging. I run command line at the same time.

Regards,

**Comment by SanderAtom** [comment]
@haringsrob this has been implemented through https://github.com/weprovide/valet-plus/pull/94
You can close the issue if this solves your problem.

**Comment by haringsrob** [comment]
That is awesome! Thank you. Will save me some time.
